//! RediSearch C API bindings (auto-generated via `rust-bindgen`).
//!
//! This module exposes the RediSearch library functions used by
//! [`Index`](super::Index) to create indexes, manage documents, build
//! query trees, and iterate over results.  **Do not edit by hand** -- the
//! bindings are regenerated from the RediSearch C headers.
//!
//! # Module layout
//!
//! ```text
//! redisearch/
//!   mod.rs   -- RediSearch constants, opaque types, and extern "C" functions
//!   redis.rs -- Redis module context types (RedisModuleCtx, RedisModuleString, ...)
//! ```
//!
//! # Key opaque types
//!
//! - `RSIndex`            -- handle to a RediSearch index
//! - `RSDoc`              -- a document to be indexed
//! - `RSQNode`            -- a node in a query tree (numeric, tag, geo, intersect, ...)
//! - `RSResultsIterator`  -- iterator over query results
//! - `RSIndexOptions`     -- index creation options (GC policy, stopwords, language)
//!
//! # Field type bitmask constants
//!
//! - `RSFLDTYPE_FULLTEXT` (1)  -- tokenized text field
//! - `RSFLDTYPE_NUMERIC`  (2)  -- numeric range field
//! - `RSFLDTYPE_GEO`      (4)  -- geographic point field
//! - `RSFLDTYPE_TAG`      (8)  -- exact-match tag field
//! - `RSFLDTYPE_VECTOR`   (16) -- vector embedding field

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::unreadable_literal)]

use std::os::raw::c_char;

use self::redis::{RedisModuleCtx, RedisModuleString};
pub mod redis;

/* automatically generated by rust-bindgen */

pub const RSIZE_MAX: i32 = -1;
pub const REDISEARCH_CAPI_VERSION: u32 = 1;
pub const RSFIELD_INVALID: i32 = -1;
pub const RSVALTYPE_NOTFOUND: u32 = 0;
pub const RSVALTYPE_STRING: u32 = 1;
pub const RSVALTYPE_DOUBLE: u32 = 2;
pub const RSRANGE_INF: f64 = f64::INFINITY;
pub const RSRANGE_NEG_INF: f64 = f64::NEG_INFINITY;
pub const RSQNTYPE_INTERSECT: u32 = 1;
pub const RSQNTYPE_UNION: u32 = 2;
pub const RSQNTYPE_TOKEN: u32 = 3;
pub const RSQNTYPE_NUMERIC: u32 = 4;
pub const RSQNTYPE_NOT: u32 = 5;
pub const RSQNTYPE_OPTIONAL: u32 = 6;
pub const RSQNTYPE_GEO: u32 = 7;
pub const RSQNTYPE_PREFX: u32 = 8;
pub const RSQNTYPE_TAG: u32 = 11;
pub const RSQNTYPE_FUZZY: u32 = 12;
pub const RSQNTYPE_LEXRANGE: u32 = 13;
pub const RSFLDTYPE_DEFAULT: u32 = 0;
pub const RSFLDTYPE_FULLTEXT: u32 = 1;
pub const RSFLDTYPE_NUMERIC: u32 = 2;
pub const RSFLDTYPE_GEO: u32 = 4;
pub const RSFLDTYPE_TAG: u32 = 8;
pub const RSFLDTYPE_VECTOR: u32 = 16;
pub const RSFLDOPT_NONE: u32 = 0;
pub const RSFLDOPT_SORTABLE: u32 = 1;
pub const RSFLDOPT_NOINDEX: u32 = 2;
pub const RSFLDOPT_TXTNOSTEM: u32 = 4;
pub const RSFLDOPT_TXTPHONETIC: u32 = 8;
pub const RSFLDOPT_WITHSUFFIXTRIE: u32 = 16;
pub const RSIDXOPT_DOCTBLSIZE_UNLIMITED: u32 = 1;
pub const GC_POLICY_NONE: i32 = -1;
pub const GC_POLICY_FORK: u32 = 0;
pub const RS_INFO_CURRENT_VERSION: u32 = 1;
pub const RS_INFO_INIT_VERSION: u32 = 1;
pub const REDISEARCH_ADD_REPLACE: u32 = 1;
pub const REDISEARCH_INIT_MODULE: u32 = 1;
pub const REDISEARCH_INIT_LIBRARY: u32 = 2;
unsafe extern "C" {
    pub static mut RSDummyContext: *mut RedisModuleCtx;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RefManager {
    _unused: [u8; 0],
}
#[repr(C)]
pub struct InfoGCStats {
    pub totalCollectedBytes: usize,
    pub totalCycles: usize,
    pub totalTime: usize,
}

#[repr(C)]
pub struct TotalIndexesFieldsInfo {
    pub total_vector_idx_mem: usize,
    pub total_mark_deleted_vectors: usize,
}

#[repr(C)]
pub struct TotalIndexesInfo {
    pub total_mem: usize,
    pub min_mem: usize,
    pub max_mem: usize,
    pub indexing_time: usize,
    pub gc_stats: InfoGCStats,
    pub fields_stats: TotalIndexesFieldsInfo,
    pub indexing_failures: usize,
    pub max_indexing_failures: usize,
    pub background_indexing_failures_OOM: usize,
    pub num_active_indexes: usize,
    pub num_active_indexes_querying: usize,
    pub num_active_indexes_indexing: usize,
    pub total_active_write_threads: usize,
    pub total_active_queries: usize,
}

pub type RSIndex = RefManager;
pub type RSFieldID = usize;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Document {
    _unused: [u8; 0],
}
pub type RSDoc = Document;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RSQueryNode {
    _unused: [u8; 0],
}
pub type RSQNode = RSQueryNode;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RS_ApiIter {
    _unused: [u8; 0],
}
pub type RSResultsIterator = RS_ApiIter;
pub type RSIndexOptions = RSIdxOptions;
pub const RSGeoDistance_RS_GEO_DISTANCE_INVALID: RSGeoDistance = -1;
pub const RSGeoDistance_RS_GEO_DISTANCE_KM: RSGeoDistance = 0;
pub const RSGeoDistance_RS_GEO_DISTANCE_M: RSGeoDistance = 1;
pub const RSGeoDistance_RS_GEO_DISTANCE_FT: RSGeoDistance = 2;
pub const RSGeoDistance_RS_GEO_DISTANCE_MI: RSGeoDistance = 3;
pub type RSGeoDistance = i32;
pub type RSGetValueCallback = ::std::option::Option<
    unsafe extern "C" fn(
        ctx: *mut ::std::os::raw::c_void,
        fieldName: *const ::std::os::raw::c_char,
        id: *const ::std::os::raw::c_void,
        strVal: *mut *mut ::std::os::raw::c_char,
        doubleVal: *mut f64,
    ) -> ::std::os::raw::c_int,
>;
unsafe extern "C" {
    pub fn RediSearch_GetCApiVersion() -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RSIdxOptions {
    pub gvcb: RSGetValueCallback,
    pub gvcbData: *mut ::std::os::raw::c_void,
    pub flags: u32,
    pub gcPolicy: ::std::os::raw::c_int,
    pub stopwords: *mut *mut ::std::os::raw::c_char,
    pub stopwordsLen: ::std::os::raw::c_int,
    pub score: f64,
    pub lang: *const ::std::os::raw::c_char,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RSIdxField {
    pub path: *mut ::std::os::raw::c_char,
    pub name: *mut ::std::os::raw::c_char,
    pub types: ::std::os::raw::c_int,
    pub options: ::std::os::raw::c_int,
    pub textWeight: f64,
    pub tagSeperator: ::std::os::raw::c_char,
    pub tagCaseSensitive: ::std::os::raw::c_int,
}

#[repr(C)]
pub struct RSIdxInfo {
    pub version: u64,
    pub gcPolicy: ::std::os::raw::c_int,
    pub score: f64,
    pub lang: *const ::std::os::raw::c_char,
    pub fields: *mut RSIdxField,
    pub numFields: usize,
    pub numDocuments: usize,
    pub maxDocId: usize,
    pub docTableSize: usize,
    pub sortablesSize: usize,
    pub docTrieSize: usize,
    pub numTerms: usize,
    pub numRecords: usize,
    pub invertedSize: usize,
    pub invertedCap: usize,
    pub skipIndexesSize: usize,
    pub scoreIndexesSize: usize,
    pub offsetVecsSize: usize,
    pub offsetVecRecords: usize,
    pub termsSize: usize,
    pub indexingFailures: usize,
    pub totalCollected: usize,
    pub numCycles: usize,
    pub totalMSRun: ::std::os::raw::c_longlong,
    pub lastRunTimeMs: ::std::os::raw::c_longlong,
}

unsafe extern "C" {
    #[doc = " Allocate an index options struct. This structure can be used to set global"]
    #[doc = " options on the index prior to it being created."]
    pub fn RediSearch_CreateIndexOptions() -> *mut RSIndexOptions;
}
unsafe extern "C" {
    #[doc = " Frees the index options previously allocated. The options are _not_ freed"]
    #[doc = " in a call to CreateIndex()"]
    pub fn RediSearch_FreeIndexOptions(arg1: *mut RSIndexOptions);
}
unsafe extern "C" {
    pub fn RediSearch_IndexOptionsSetGetValueCallback(
        opts: *mut RSIndexOptions,
        cb: RSGetValueCallback,
        ctx: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn RediSearch_IndexOptionsSetStopwords(
        opts: *mut RSIndexOptions,
        stopwords: *mut *const ::std::os::raw::c_char,
        stopwordsLen: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn RediSearch_IndexOptionsSetScore(
        arg1: *mut RSIndexOptions,
        arg2: f64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_IndexOptionsSetLanguage(
        arg1: *mut RSIndexOptions,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_ValidateLanguage(
        arg1: *const ::std::os::raw::c_char
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Set flags modifying index creation."]
    pub fn RediSearch_IndexOptionsSetFlags(
        opts: *mut RSIndexOptions,
        flags: u32,
    );
}
unsafe extern "C" {
    pub fn RediSearch_CreateIndex(
        name: *const ::std::os::raw::c_char,
        options: *const RSIndexOptions,
    ) -> *mut RSIndex;
}
unsafe extern "C" {
    pub fn RediSearch_DropIndex(arg1: *mut RSIndex);
}
unsafe extern "C" {
    #[doc = " Handle Stopwords list"]
    pub fn RediSearch_StopwordsList_Contains(
        idx: *mut RSIndex,
        term: *const ::std::os::raw::c_char,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_StopwordsList_Free(
        list: *mut *mut ::std::os::raw::c_char,
        size: usize,
    );
}
unsafe extern "C" {
    #[doc = " Getter functions"]
    pub fn RediSearch_IndexGetStopwords(
        arg1: *mut RSIndex,
        arg2: *mut usize,
    ) -> *mut *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn RediSearch_IndexGetScore(arg1: *mut RSIndex) -> f64;
}
unsafe extern "C" {
    pub fn RediSearch_IndexGetLanguage(arg1: *mut RSIndex) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " Create a new field in the index"]
    #[doc = " @param idx the index"]
    #[doc = " @param name the name of the field"]
    #[doc = " @param ftype a mask of RSFieldType that should be supported for indexing."]
    #[doc = "  This also indicates the default indexing settings if not otherwise specified"]
    #[doc = " @param fopt a mask of RSFieldOptions"]
    pub fn RediSearch_CreateField(
        idx: *mut RSIndex,
        name: *const ::std::os::raw::c_char,
        ftype: ::std::os::raw::c_uint,
        fopt: ::std::os::raw::c_uint,
    ) -> RSFieldID;
}
unsafe extern "C" {
    pub fn RediSearch_TextFieldSetWeight(
        sp: *mut RSIndex,
        fs: RSFieldID,
        w: f64,
    );
}
unsafe extern "C" {
    pub fn RediSearch_TagFieldSetSeparator(
        sp: *mut RSIndex,
        fs: RSFieldID,
        sep: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn RediSearch_TagFieldSetCaseSensitive(
        sp: *mut RSIndex,
        fs: RSFieldID,
        enable: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn RediSearch_VectorFieldSetDim(
        sp: *mut RSIndex,
        fs: RSFieldID,
        dim: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn RediSearch_VectorFieldSetHNSWParams(
        sp: *mut RSIndex,
        fs: RSFieldID,
        m: usize,
        ef_construction: usize,
        ef_runtime: usize,
        metric: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn RediSearch_CreateDocument(
        docKey: *const ::std::os::raw::c_void,
        len: usize,
        score: f64,
        lang: *const ::std::os::raw::c_char,
    ) -> *mut RSDoc;
}
unsafe extern "C" {
    pub fn RediSearch_CreateDocument2(
        docKey: *const ::std::os::raw::c_void,
        len: usize,
        sp: *mut RSIndex,
        score: f64,
        lang: *const ::std::os::raw::c_char,
    ) -> *mut RSDoc;
}
unsafe extern "C" {
    pub fn RediSearch_FreeDocument(doc: *mut RSDoc);
}
unsafe extern "C" {
    pub fn RediSearch_DeleteDocument(
        sp: *mut RSIndex,
        docKey: *const ::std::os::raw::c_void,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Add a field (with value) to the document"]
    #[doc = " @param d the document"]
    #[doc = " @param fieldName the name of the field"]
    #[doc = " @param s the contents of the field to be added (if numeric, the string representation)"]
    #[doc = " @param indexAsTypes the types the field should be indexed as. Should be a"]
    #[doc = "  bitmask of RSFieldType."]
    pub fn RediSearch_DocumentAddField(
        d: *mut RSDoc,
        fieldName: *const ::std::os::raw::c_char,
        s: *mut RedisModuleString,
        indexAsTypes: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn RediSearch_DocumentAddFieldString(
        d: *mut RSDoc,
        fieldName: *const ::std::os::raw::c_char,
        s: *const ::std::os::raw::c_char,
        n: usize,
        indexAsTypes: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn RediSearch_DocumentAddFieldNumber(
        d: *mut RSDoc,
        fieldName: *const ::std::os::raw::c_char,
        val: f64,
        indexAsTypes: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn RediSearch_DocumentAddFieldVector(
        d: *mut RSDoc,
        fieldName: *const ::std::os::raw::c_char,
        vec: *const c_char,
        dim: u32,
        nbytes: usize,
    );
}
unsafe extern "C" {
    #[doc = " Add geo field to a document."]
    #[doc = " Return REDISMODULE_ERR if longitude or latitude is out-of-range"]
    #[doc = " otherwise, returns REDISMODULE_OK"]
    pub fn RediSearch_DocumentAddFieldGeo(
        d: *mut RSDoc,
        fieldName: *const ::std::os::raw::c_char,
        lat: f64,
        lon: f64,
        indexAsTypes: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_DocumentAddFieldNumericArray(
        d: *mut RSDoc,
        fieldName: *const ::std::os::raw::c_char,
        arr: *mut *mut f64,
        indexAsTypes: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn RediSearch_DocumentAddFieldStringArray(
        d: *mut RSDoc,
        fieldName: *const ::std::os::raw::c_char,
        arr: *mut *mut *mut ::std::os::raw::c_char,
        len: usize,
        indexAsTypes: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn RediSearch_IndexAddDocument(
        sp: *mut RSIndex,
        d: *mut RSDoc,
        flags: ::std::os::raw::c_int,
        arg1: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_CreateTokenNode(
        sp: *mut RSIndex,
        fieldName: *const ::std::os::raw::c_char,
        token: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateNumericNode(
        sp: *mut RSIndex,
        field: *const ::std::os::raw::c_char,
        max: f64,
        min: f64,
        includeMax: ::std::os::raw::c_int,
        includeMin: ::std::os::raw::c_int,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateGeoNode(
        sp: *mut RSIndex,
        field: *const ::std::os::raw::c_char,
        lat: f64,
        lon: f64,
        radius: f64,
        unitType: RSGeoDistance,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreatePrefixNode(
        sp: *mut RSIndex,
        fieldName: *const ::std::os::raw::c_char,
        s: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateContainsNode(
        sp: *mut RSIndex,
        fieldName: *const ::std::os::raw::c_char,
        s: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateSuffixNode(
        sp: *mut RSIndex,
        fieldName: *const ::std::os::raw::c_char,
        s: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateLexRangeNode(
        sp: *mut RSIndex,
        fieldName: *const ::std::os::raw::c_char,
        begin: *const ::std::os::raw::c_char,
        end: *const ::std::os::raw::c_char,
        includeBegin: ::std::os::raw::c_int,
        includeEnd: ::std::os::raw::c_int,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateTagNode(
        sp: *mut RSIndex,
        field: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateTagTokenNode(
        sp: *mut RSIndex,
        token: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateTagPrefixNode(
        sp: *mut RSIndex,
        s: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateTagContainsNode(
        sp: *mut RSIndex,
        s: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateTagSuffixNode(
        sp: *mut RSIndex,
        s: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateTagLexRangeNode(
        sp: *mut RSIndex,
        begin: *const ::std::os::raw::c_char,
        end: *const ::std::os::raw::c_char,
        includeBegin: ::std::os::raw::c_int,
        includeEnd: ::std::os::raw::c_int,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateIntersectNode(
        sp: *mut RSIndex,
        exact: ::std::os::raw::c_int,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateUnionNode(sp: *mut RSIndex) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateEmptyNode(sp: *mut RSIndex) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateNotNode(sp: *mut RSIndex) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_QueryNodeFree(qn: *mut RSQNode);
}
unsafe extern "C" {
    pub fn RediSearch_QueryNodeAddChild(
        arg1: *mut RSQNode,
        arg2: *mut RSQNode,
    );
}
unsafe extern "C" {
    pub fn RediSearch_QueryNodeClearChildren(arg1: *mut RSQNode);
}
unsafe extern "C" {
    pub fn RediSearch_QueryNodeGetChild(
        arg1: *const RSQNode,
        arg2: usize,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_QueryNodeNumChildren(arg1: *const RSQNode) -> usize;
}
unsafe extern "C" {
    pub fn RediSearch_QueryNodeType(qn: *mut RSQNode) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_QueryNodeGetFieldMask(qn: *mut RSQNode) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_GetResultsIterator(
        qn: *mut RSQNode,
        sp: *mut RSIndex,
    ) -> *mut RSResultsIterator;
}
unsafe extern "C" {
    pub fn RediSearch_SetCriteriaTesterThreshold(num: usize);
}
unsafe extern "C" {
    #[doc = " Return an iterator over the results of the specified query string"]
    #[doc = " @param sp the index"]
    #[doc = " @param s the query string"]
    #[doc = " @param n the length of the string"]
    #[doc = " @param[out] error if not-NULL, will be set to the error message, if there is a"]
    #[doc = "  problem parsing the query"]
    #[doc = " @return an iterator over the results, or NULL if no iterator can be had"]
    #[doc = "  (see err, or no results)."]
    pub fn RediSearch_IterateQuery(
        sp: *mut RSIndex,
        s: *const ::std::os::raw::c_char,
        n: usize,
        err: *mut *mut ::std::os::raw::c_char,
    ) -> *mut RSResultsIterator;
}
unsafe extern "C" {
    #[doc = " Return an iterator over the results of the specified query string"]
    #[doc = " @param sp the index"]
    #[doc = " @param s the query string"]
    #[doc = " @param n the length of the string"]
    #[doc = " @param dialect dialect version to be used for parsing the query"]
    #[doc = " @param[out] error if not-NULL, will be set to the error message, if there is a"]
    #[doc = "  problem parsing the query"]
    #[doc = " @return an iterator over the results, or NULL if no iterator can be had"]
    #[doc = "  (see err, or no results)."]
    pub fn RediSearch_IterateQueryWithDialect(
        sp: *mut RSIndex,
        s: *const ::std::os::raw::c_char,
        n: usize,
        dialect: ::std::os::raw::c_uint,
        err: *mut *mut ::std::os::raw::c_char,
    ) -> *mut RSResultsIterator;
}
unsafe extern "C" {
    pub fn RediSearch_DocumentExists(
        sp: *mut RSIndex,
        docKey: *const ::std::os::raw::c_void,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_ResultsIteratorNext(
        iter: *mut RSResultsIterator,
        sp: *mut RSIndex,
        len: *mut usize,
    ) -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn RediSearch_ResultsIteratorFree(iter: *mut RSResultsIterator);
}
unsafe extern "C" {
    pub fn RediSearch_ResultsIteratorReset(iter: *mut RSResultsIterator);
}
unsafe extern "C" {
    pub fn RediSearch_ResultsIteratorGetScore(it: *const RSResultsIterator) -> f64;
}
unsafe extern "C" {
    pub fn RediSearch_IndexOptionsSetGCPolicy(
        options: *mut RSIndexOptions,
        policy: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn RediSearch_MemUsage(sp: *mut RSIndex) -> usize;
}
unsafe extern "C" {
    pub fn RediSearch_TotalMemUsage() -> usize;
}
unsafe extern "C" {
    pub fn RediSearch_TotalInfo() -> TotalIndexesInfo;
}
unsafe extern "C" {
    pub fn RediSearch_GC_total() -> InfoGCStats;
}
unsafe extern "C" {
    #[doc = " Return an info struct"]
    #[doc = " @param sp the index"]
    #[doc = " @param info a pointer to RSIdxInfo struct with `.version = RS_INFO_CURRENT`"]
    pub fn RediSearch_IndexInfo(
        sp: *mut RSIndex,
        info: *mut RSIdxInfo,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_IndexInfoFree(info: *mut RSIdxInfo);
}
unsafe extern "C" {
    #[doc = " Export the C API to be dynamically discoverable by other modules."]
    #[doc = " This is an internal function"]
    pub fn RediSearch_ExportCapi(ctx: *mut RedisModuleCtx) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_Init(
        ctx: *mut RedisModuleCtx,
        mode: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
