//! RediSearch C API bindings (auto-generated via `rust-bindgen`).
//!
//! This module exposes the RediSearch library functions used by
//! [`Index`](super::Index) to create indexes, manage documents, build
//! query trees, and iterate over results.  **Do not edit by hand** -- the
//! bindings are regenerated from the RediSearch C headers.
//!
//! # Module layout
//!
//! ```text
//! redisearch/
//!   mod.rs   -- RediSearch constants, opaque types, and extern "C" functions
//!   redis.rs -- Redis module context types (RedisModuleCtx, RedisModuleString, ...)
//! ```
//!
//! # Key opaque types
//!
//! - `RSIndexHandle`            -- handle to a RediSearch index
//! - `RSDoc`              -- a document to be indexed
//! - `RSQNode`            -- a node in a query tree (numeric, tag, geo, intersect, ...)
//! - `RSResultsIterator`  -- iterator over query results
//! - `RSIndexOptions`     -- index creation options (GC policy, stopwords, language)
//!
//! # Field type bitmask constants
//!
//! - `RSFLDTYPE_FULLTEXT` (1)  -- tokenized text field
//! - `RSFLDTYPE_NUMERIC`  (2)  -- numeric range field
//! - `RSFLDTYPE_GEO`      (4)  -- geographic point field
//! - `RSFLDTYPE_TAG`      (8)  -- exact-match tag field
//! - `RSFLDTYPE_VECTOR`   (16) -- vector embedding field

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::unreadable_literal)]

use std::os::raw::c_char;

use self::redis::{RedisModuleCtx, RedisModuleString};
pub mod redis;

/* automatically generated by rust-bindgen */

pub const RSIZE_MAX: i32 = -1;
pub const REDISEARCH_CAPI_VERSION: u32 = 1;
pub const RSFIELD_INVALID: i32 = -1;
pub const RSVALTYPE_NOTFOUND: u32 = 0;
pub const RSVALTYPE_STRING: u32 = 1;
pub const RSVALTYPE_DOUBLE: u32 = 2;
pub const RSRANGE_INF: f64 = f64::INFINITY;
pub const RSRANGE_NEG_INF: f64 = f64::NEG_INFINITY;
pub const RSQNTYPE_INTERSECT: u32 = 1;
pub const RSQNTYPE_UNION: u32 = 2;
pub const RSQNTYPE_TOKEN: u32 = 3;
pub const RSQNTYPE_NUMERIC: u32 = 4;
pub const RSQNTYPE_NOT: u32 = 5;
pub const RSQNTYPE_OPTIONAL: u32 = 6;
pub const RSQNTYPE_GEO: u32 = 7;
pub const RSQNTYPE_PREFX: u32 = 8;
pub const RSQNTYPE_TAG: u32 = 11;
pub const RSQNTYPE_FUZZY: u32 = 12;
pub const RSQNTYPE_LEXRANGE: u32 = 13;
pub const RSFLDTYPE_DEFAULT: u32 = 0;
pub const RSFLDTYPE_FULLTEXT: u32 = 1;
pub const RSFLDTYPE_NUMERIC: u32 = 2;
pub const RSFLDTYPE_GEO: u32 = 4;
pub const RSFLDTYPE_TAG: u32 = 8;
pub const RSFLDTYPE_VECTOR: u32 = 16;
pub const RSFLDOPT_NONE: u32 = 0;
pub const RSFLDOPT_SORTABLE: u32 = 1;
pub const RSFLDOPT_NOINDEX: u32 = 2;
pub const RSFLDOPT_TXTNOSTEM: u32 = 4;
pub const RSFLDOPT_TXTPHONETIC: u32 = 8;
pub const RSFLDOPT_WITHSUFFIXTRIE: u32 = 16;
pub const RSIDXOPT_DOCTBLSIZE_UNLIMITED: u32 = 1;
pub const GC_POLICY_NONE: i32 = -1;
pub const GC_POLICY_FORK: u32 = 0;
pub const RS_INFO_CURRENT_VERSION: u32 = 1;
pub const RS_INFO_INIT_VERSION: u32 = 1;
pub const REDISEARCH_ADD_REPLACE: u32 = 1;
pub const REDISEARCH_INIT_MODULE: u32 = 1;
pub const REDISEARCH_INIT_LIBRARY: u32 = 2;
unsafe extern "C" {
    pub static mut RSDummyContext: *mut RedisModuleCtx;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RefManager {
    _unused: [u8; 0],
}
#[repr(C)]
pub struct InfoGCStats {
    pub totalCollectedBytes: usize,
    pub totalCycles: usize,
    pub totalTime: usize,
}

#[repr(C)]
pub struct TotalIndexesFieldsInfo {
    pub total_vector_idx_mem: usize,
    pub total_mark_deleted_vectors: usize,
}

#[repr(C)]
pub struct TotalIndexesInfo {
    pub total_mem: usize,
    pub min_mem: usize,
    pub max_mem: usize,
    pub indexing_time: usize,
    pub gc_stats: InfoGCStats,
    pub fields_stats: TotalIndexesFieldsInfo,
    pub indexing_failures: usize,
    pub max_indexing_failures: usize,
    pub background_indexing_failures_OOM: usize,
    pub num_active_indexes: usize,
    pub num_active_indexes_querying: usize,
    pub num_active_indexes_indexing: usize,
    pub total_active_write_threads: usize,
    pub total_active_queries: usize,
}

pub type RSIndexHandle = RefManager;
pub type RSFieldID = usize;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Document {
    _unused: [u8; 0],
}
pub type RSDoc = Document;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RSQueryNode {
    _unused: [u8; 0],
}
pub type RSQNode = RSQueryNode;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RS_ApiIter {
    _unused: [u8; 0],
}
pub type RSResultsIterator = RS_ApiIter;
pub type RSIndexOptions = RSIdxOptions;
pub const RSGeoDistance_RS_GEO_DISTANCE_INVALID: RSGeoDistance = -1;
pub const RSGeoDistance_RS_GEO_DISTANCE_KM: RSGeoDistance = 0;
pub const RSGeoDistance_RS_GEO_DISTANCE_M: RSGeoDistance = 1;
pub const RSGeoDistance_RS_GEO_DISTANCE_FT: RSGeoDistance = 2;
pub const RSGeoDistance_RS_GEO_DISTANCE_MI: RSGeoDistance = 3;
pub type RSGeoDistance = i32;
pub type RSGetValueCallback = ::std::option::Option<
    unsafe extern "C" fn(
        ctx: *mut ::std::os::raw::c_void,
        fieldName: *const ::std::os::raw::c_char,
        id: *const ::std::os::raw::c_void,
        strVal: *mut *mut ::std::os::raw::c_char,
        doubleVal: *mut f64,
    ) -> ::std::os::raw::c_int,
>;
unsafe extern "C" {
    pub fn RediSearch_GetCApiVersion() -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RSIdxOptions {
    pub gvcb: RSGetValueCallback,
    pub gvcbData: *mut ::std::os::raw::c_void,
    pub flags: u32,
    pub gcPolicy: ::std::os::raw::c_int,
    pub stopwords: *mut *mut ::std::os::raw::c_char,
    pub stopwordsLen: ::std::os::raw::c_int,
    pub score: f64,
    pub lang: *const ::std::os::raw::c_char,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RSIdxField {
    pub path: *mut ::std::os::raw::c_char,
    pub name: *mut ::std::os::raw::c_char,
    pub types: ::std::os::raw::c_int,
    pub options: ::std::os::raw::c_int,
    pub textWeight: f64,
    pub tagSeperator: ::std::os::raw::c_char,
    pub tagCaseSensitive: ::std::os::raw::c_int,
}

#[repr(C)]
pub struct RSIdxInfo {
    pub version: u64,
    pub gcPolicy: ::std::os::raw::c_int,
    pub score: f64,
    pub lang: *const ::std::os::raw::c_char,
    pub fields: *mut RSIdxField,
    pub numFields: usize,
    pub numDocuments: usize,
    pub maxDocId: usize,
    pub docTableSize: usize,
    pub sortablesSize: usize,
    pub docTrieSize: usize,
    pub numTerms: usize,
    pub numRecords: usize,
    pub invertedSize: usize,
    pub invertedCap: usize,
    pub skipIndexesSize: usize,
    pub scoreIndexesSize: usize,
    pub offsetVecsSize: usize,
    pub offsetVecRecords: usize,
    pub termsSize: usize,
    pub indexingFailures: usize,
    pub totalCollected: usize,
    pub numCycles: usize,
    pub totalMSRun: ::std::os::raw::c_longlong,
    pub lastRunTimeMs: ::std::os::raw::c_longlong,
}

unsafe extern "C" {
    #[doc = " Allocate an index options struct. This structure can be used to set global"]
    #[doc = " options on the index prior to it being created."]
    pub fn RediSearch_CreateIndexOptions() -> *mut RSIndexOptions;
}
unsafe extern "C" {
    #[doc = " Frees the index options previously allocated. The options are _not_ freed"]
    #[doc = " in a call to CreateIndex()"]
    pub fn RediSearch_FreeIndexOptions(arg1: *mut RSIndexOptions);
}
unsafe extern "C" {
    pub fn RediSearch_IndexOptionsSetGetValueCallback(
        opts: *mut RSIndexOptions,
        cb: RSGetValueCallback,
        ctx: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn RediSearch_IndexOptionsSetStopwords(
        opts: *mut RSIndexOptions,
        stopwords: *mut *const ::std::os::raw::c_char,
        stopwordsLen: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn RediSearch_IndexOptionsSetScore(
        arg1: *mut RSIndexOptions,
        arg2: f64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_IndexOptionsSetLanguage(
        arg1: *mut RSIndexOptions,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_ValidateLanguage(
        arg1: *const ::std::os::raw::c_char
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Set flags modifying index creation."]
    pub fn RediSearch_IndexOptionsSetFlags(
        opts: *mut RSIndexOptions,
        flags: u32,
    );
}
unsafe extern "C" {
    pub fn RediSearch_CreateIndex(
        name: *const ::std::os::raw::c_char,
        options: *const RSIndexOptions,
    ) -> *mut RSIndexHandle;
}
unsafe extern "C" {
    pub fn RediSearch_DropIndex(arg1: *mut RSIndexHandle);
}
unsafe extern "C" {
    #[doc = " Acquire a new strong reference on `sp`. The returned handle must be"]
    #[doc = " released with RediSearch_IndexRelease when the caller is done with it."]
    #[doc = " Returns NULL if the underlying spec has been invalidated (e.g. by a"]
    #[doc = " concurrent RediSearch_DropIndex)."]
    pub fn RediSearch_IndexClone(sp: *mut RSIndexHandle) -> *mut RSIndexHandle;
}
unsafe extern "C" {
    #[doc = " Release a strong reference acquired by RediSearch_IndexClone (or the"]
    #[doc = " creation-time reference returned by RediSearch_CreateIndex). When the"]
    #[doc = " last reference is dropped, the spec is freed."]
    pub fn RediSearch_IndexRelease(sp: *mut RSIndexHandle);
}
unsafe extern "C" {
    #[doc = " Populate the TIERED runtime fields of `params` (worker thread pool,"]
    #[doc = " submit callback, weak ref to `sp`, flat-buffer limit, logCtx) so it can"]
    #[doc = " be passed to RediSearch_VectorFieldSetParams. Preconditions:"]
    #[doc = " params->algo == VecSimAlgo_TIERED and tieredParams.primaryIndexParams"]
    #[doc = " is allocated and populated. Returns REDISEARCH_OK / REDISEARCH_ERR."]
    pub fn RediSearch_VecSimTieredParams_Init(
        params: *mut VecSimParams,
        sp: *mut RSIndexHandle,
        field_name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Set the number of background worker threads RediSearch uses (e.g. for"]
    #[doc = " TIERED vector index migration jobs). Returns REDISEARCH_OK / REDISEARCH_ERR."]
    pub fn RediSearch_SetNumWorkerThreads(n: usize) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Handle Stopwords list"]
    pub fn RediSearch_StopwordsList_Contains(
        idx: *mut RSIndexHandle,
        term: *const ::std::os::raw::c_char,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_StopwordsList_Free(
        list: *mut *mut ::std::os::raw::c_char,
        size: usize,
    );
}
unsafe extern "C" {
    #[doc = " Getter functions"]
    pub fn RediSearch_IndexGetStopwords(
        arg1: *mut RSIndexHandle,
        arg2: *mut usize,
    ) -> *mut *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn RediSearch_IndexGetScore(arg1: *mut RSIndexHandle) -> f64;
}
unsafe extern "C" {
    pub fn RediSearch_IndexGetLanguage(arg1: *mut RSIndexHandle) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " Create a new field in the index"]
    #[doc = " @param idx the index"]
    #[doc = " @param name the name of the field"]
    #[doc = " @param ftype a mask of RSFieldType that should be supported for indexing."]
    #[doc = "  This also indicates the default indexing settings if not otherwise specified"]
    #[doc = " @param fopt a mask of RSFieldOptions"]
    pub fn RediSearch_CreateField(
        idx: *mut RSIndexHandle,
        name: *const ::std::os::raw::c_char,
        ftype: ::std::os::raw::c_uint,
        fopt: ::std::os::raw::c_uint,
    ) -> RSFieldID;
}
unsafe extern "C" {
    pub fn RediSearch_TextFieldSetWeight(
        sp: *mut RSIndexHandle,
        fs: RSFieldID,
        w: f64,
    );
}
unsafe extern "C" {
    pub fn RediSearch_TagFieldSetSeparator(
        sp: *mut RSIndexHandle,
        fs: RSFieldID,
        sep: ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn RediSearch_TagFieldSetCaseSensitive(
        sp: *mut RSIndexHandle,
        fs: RSFieldID,
        enable: ::std::os::raw::c_int,
    );
}
// ---- VecSim parameter types (from VectorSimilarity vec_sim_common.h) ----
// RediSearch 8.6 configures vector fields via RediSearch_VectorFieldSetParams,
// which takes a full VecSimParams and copies it by value. These definitions
// must stay ABI-exact with the C headers; the size assertion below guards
// against transcription drift on the supported LP64 targets.

pub type VecSimType = ::std::os::raw::c_uint;
pub const VecSimType_FLOAT32: VecSimType = 0;
pub const VecSimType_FLOAT64: VecSimType = 1;
pub const VecSimType_BFLOAT16: VecSimType = 2;
pub const VecSimType_FLOAT16: VecSimType = 3;
pub const VecSimType_INT8: VecSimType = 4;
pub const VecSimType_UINT8: VecSimType = 5;
pub const VecSimType_INT32: VecSimType = 6;
pub const VecSimType_INT64: VecSimType = 7;

pub type VecSimAlgo = ::std::os::raw::c_uint;
pub const VecSimAlgo_BF: VecSimAlgo = 0;
pub const VecSimAlgo_HNSWLIB: VecSimAlgo = 1;
pub const VecSimAlgo_TIERED: VecSimAlgo = 2;
pub const VecSimAlgo_SVS: VecSimAlgo = 3;

pub type VecSimMetric = ::std::os::raw::c_uint;
pub const VecSimMetric_L2: VecSimMetric = 0;
pub const VecSimMetric_IP: VecSimMetric = 1;
pub const VecSimMetric_Cosine: VecSimMetric = 2;

pub type VecSimOptionMode = ::std::os::raw::c_uint;
pub type VecSimSvsQuantBits = ::std::os::raw::c_uint;

/// Default per-block vector capacity for VecSim's `DataBlock` container
/// (VectorSimilarity `vec_sim_common.h`: `#define DEFAULT_BLOCK_SIZE 1024`).
/// Unlike the `FT.CREATE` path (`spec.c` `parseVectorField_validate_hnsw`), the
/// `RediSearch_VectorFieldSetParams` LLAPI does *not* normalize this field, and
/// a `blockSize` of 0 corrupts the heap on the first HNSW insert/search. The
/// embedder must supply a non-zero value.
pub const DEFAULT_BLOCK_SIZE: usize = 1024;

/// Default HNSW range-search accuracy/latency tradeoff
/// (VectorSimilarity: `HNSW_DEFAULT_EPSILON 0.01`).
pub const HNSW_DEFAULT_EPSILON: f64 = 0.01;

#[repr(C)]
#[derive(Copy, Clone)]
pub struct HNSWParams {
    pub type_: VecSimType,
    pub dim: usize,
    pub metric: VecSimMetric,
    pub multi: bool,
    pub initialCapacity: usize,
    pub blockSize: usize,
    pub M: usize,
    pub efConstruction: usize,
    pub efRuntime: usize,
    pub epsilon: f64,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct BFParams {
    pub type_: VecSimType,
    pub dim: usize,
    pub metric: VecSimMetric,
    pub multi: bool,
    pub initialCapacity: usize,
    pub blockSize: usize,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct SVSParams {
    pub type_: VecSimType,
    pub dim: usize,
    pub metric: VecSimMetric,
    pub multi: bool,
    pub blockSize: usize,
    pub quantBits: VecSimSvsQuantBits,
    pub alpha: f32,
    pub graph_max_degree: usize,
    pub construction_window_size: usize,
    pub max_candidate_pool_size: usize,
    pub prune_to: usize,
    pub use_search_history: VecSimOptionMode,
    pub num_threads: usize,
    pub search_window_size: usize,
    pub search_buffer_capacity: usize,
    pub leanvec_dim: usize,
    pub epsilon: f64,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct TieredHNSWParams {
    pub swapJobThreshold: usize,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct TieredHNSWDiskParams {
    pub _placeholder: ::std::os::raw::c_char,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct TieredSVSParams {
    pub trainingTriggerThreshold: usize,
    pub updateTriggerThreshold: usize,
    pub updateJobWaitTime: usize,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub union TieredSpecificParams {
    pub tieredHnswParams: TieredHNSWParams,
    pub tieredSVSParams: TieredSVSParams,
    pub tieredHnswDiskParams: TieredHNSWDiskParams,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct TieredIndexParams {
    pub jobQueue: *mut ::std::os::raw::c_void,
    pub jobQueueCtx: *mut ::std::os::raw::c_void,
    // SubmitCB function pointer; represented as a void pointer (size-equivalent).
    pub submitCb: *mut ::std::os::raw::c_void,
    pub flatBufferLimit: usize,
    pub primaryIndexParams: *mut VecSimParams,
    pub specificParams: TieredSpecificParams,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub union AlgoParams {
    pub hnswParams: HNSWParams,
    pub bfParams: BFParams,
    pub tieredParams: TieredIndexParams,
    pub svsParams: SVSParams,
}

#[repr(C)]
pub struct VecSimParams {
    pub algo: VecSimAlgo,
    pub algoParams: AlgoParams,
    pub logCtx: *mut ::std::os::raw::c_void,
}

const _: () = assert!(::std::mem::size_of::<VecSimParams>() == 136);

// Field-offset guards against transcription drift (LP64). These mirror the C
// `vec_sim_common.h` layout; `dim` in particular feeds `vecSimParams_ExpBlobSize`
// (expBlobSize = dim * sizeof(type)), so a wrong offset would surface as a
// "blob size mismatch" at document-add time.
const _: () = {
    use ::std::mem::offset_of;
    // HNSWParams
    assert!(offset_of!(HNSWParams, type_) == 0);
    assert!(offset_of!(HNSWParams, dim) == 8);
    assert!(offset_of!(HNSWParams, metric) == 16);
    assert!(offset_of!(HNSWParams, blockSize) == 32);
    assert!(offset_of!(HNSWParams, M) == 40);
    assert!(::std::mem::size_of::<HNSWParams>() == 72);
    // VecSimParams
    assert!(offset_of!(VecSimParams, algo) == 0);
    assert!(offset_of!(VecSimParams, algoParams) == 8);
    assert!(offset_of!(VecSimParams, logCtx) == 128);
    // TieredIndexParams: the primaryIndexParams pointer must land at the C offset
    // so RediSearch reads the right HNSW sub-params (and thus the right dim).
    assert!(offset_of!(TieredIndexParams, primaryIndexParams) == 32);
};

unsafe extern "C" {
    pub fn RediSearch_VectorFieldSetParams(
        sp: *mut RSIndexHandle,
        fs: RSFieldID,
        params: *const VecSimParams,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_CreateDocument(
        docKey: *const ::std::os::raw::c_void,
        len: usize,
        score: f64,
        lang: *const ::std::os::raw::c_char,
    ) -> *mut RSDoc;
}
unsafe extern "C" {
    pub fn RediSearch_CreateDocument2(
        docKey: *const ::std::os::raw::c_void,
        len: usize,
        sp: *mut RSIndexHandle,
        score: f64,
        lang: *const ::std::os::raw::c_char,
    ) -> *mut RSDoc;
}
unsafe extern "C" {
    pub fn RediSearch_FreeDocument(doc: *mut RSDoc);
}
unsafe extern "C" {
    pub fn RediSearch_DeleteDocument(
        sp: *mut RSIndexHandle,
        docKey: *const ::std::os::raw::c_void,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Add a field (with value) to the document"]
    #[doc = " @param d the document"]
    #[doc = " @param fieldName the name of the field"]
    #[doc = " @param s the contents of the field to be added (if numeric, the string representation)"]
    #[doc = " @param indexAsTypes the types the field should be indexed as. Should be a"]
    #[doc = "  bitmask of RSFieldType."]
    pub fn RediSearch_DocumentAddField(
        d: *mut RSDoc,
        fieldName: *const ::std::os::raw::c_char,
        s: *mut RedisModuleString,
        indexAsTypes: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn RediSearch_DocumentAddFieldString(
        d: *mut RSDoc,
        fieldName: *const ::std::os::raw::c_char,
        s: *const ::std::os::raw::c_char,
        n: usize,
        indexAsTypes: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn RediSearch_DocumentAddFieldNumber(
        d: *mut RSDoc,
        fieldName: *const ::std::os::raw::c_char,
        val: f64,
        indexAsTypes: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn RediSearch_DocumentAddFieldVector(
        d: *mut RSDoc,
        fieldName: *const ::std::os::raw::c_char,
        vec: *const c_char,
        nbytes: usize,
    );
}
unsafe extern "C" {
    #[doc = " Add geo field to a document."]
    #[doc = " Return REDISMODULE_ERR if longitude or latitude is out-of-range"]
    #[doc = " otherwise, returns REDISMODULE_OK"]
    pub fn RediSearch_DocumentAddFieldGeo(
        d: *mut RSDoc,
        fieldName: *const ::std::os::raw::c_char,
        lat: f64,
        lon: f64,
        indexAsTypes: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_DocumentAddFieldNumericArray(
        d: *mut RSDoc,
        fieldName: *const ::std::os::raw::c_char,
        arr: *mut *mut f64,
        indexAsTypes: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn RediSearch_DocumentAddFieldStringArray(
        d: *mut RSDoc,
        fieldName: *const ::std::os::raw::c_char,
        arr: *mut *mut *mut ::std::os::raw::c_char,
        len: usize,
        indexAsTypes: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn RediSearch_IndexAddDocument(
        sp: *mut RSIndexHandle,
        d: *mut RSDoc,
        flags: ::std::os::raw::c_int,
        arg1: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_CreateTokenNode(
        sp: *mut RSIndexHandle,
        fieldName: *const ::std::os::raw::c_char,
        token: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateNumericNode(
        sp: *mut RSIndexHandle,
        field: *const ::std::os::raw::c_char,
        max: f64,
        min: f64,
        includeMax: ::std::os::raw::c_int,
        includeMin: ::std::os::raw::c_int,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateGeoNode(
        sp: *mut RSIndexHandle,
        field: *const ::std::os::raw::c_char,
        lat: f64,
        lon: f64,
        radius: f64,
        unitType: RSGeoDistance,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreatePrefixNode(
        sp: *mut RSIndexHandle,
        fieldName: *const ::std::os::raw::c_char,
        s: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateContainsNode(
        sp: *mut RSIndexHandle,
        fieldName: *const ::std::os::raw::c_char,
        s: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateSuffixNode(
        sp: *mut RSIndexHandle,
        fieldName: *const ::std::os::raw::c_char,
        s: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateLexRangeNode(
        sp: *mut RSIndexHandle,
        fieldName: *const ::std::os::raw::c_char,
        begin: *const ::std::os::raw::c_char,
        end: *const ::std::os::raw::c_char,
        includeBegin: ::std::os::raw::c_int,
        includeEnd: ::std::os::raw::c_int,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateTagNode(
        sp: *mut RSIndexHandle,
        field: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    /// Create a vector-similarity (KNN) query node.
    /// `vector` points to `nbytes` of dense float32 data; `k` is the
    /// number of nearest neighbours to retrieve. The returned QueryNode
    /// can be passed to `RediSearch_GetResultsIterator` exactly like
    /// any other QueryNode; per-row distance is then read via
    /// `RediSearch_ResultsIteratorGetScore`.
    pub fn RediSearch_CreateVecSimNode(
        sp: *mut RSIndexHandle,
        field: *const ::std::os::raw::c_char,
        vector: *const ::std::os::raw::c_char,
        nbytes: usize,
        k: usize,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateTagTokenNode(
        sp: *mut RSIndexHandle,
        token: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateTagPrefixNode(
        sp: *mut RSIndexHandle,
        s: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateTagContainsNode(
        sp: *mut RSIndexHandle,
        s: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateTagSuffixNode(
        sp: *mut RSIndexHandle,
        s: *const ::std::os::raw::c_char,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateTagLexRangeNode(
        sp: *mut RSIndexHandle,
        begin: *const ::std::os::raw::c_char,
        end: *const ::std::os::raw::c_char,
        includeBegin: ::std::os::raw::c_int,
        includeEnd: ::std::os::raw::c_int,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateIntersectNode(
        sp: *mut RSIndexHandle,
        exact: ::std::os::raw::c_int,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateUnionNode(sp: *mut RSIndexHandle) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateEmptyNode(sp: *mut RSIndexHandle) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_CreateNotNode(sp: *mut RSIndexHandle) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_QueryNodeFree(qn: *mut RSQNode);
}
unsafe extern "C" {
    pub fn RediSearch_QueryNodeAddChild(
        arg1: *mut RSQNode,
        arg2: *mut RSQNode,
    );
}
unsafe extern "C" {
    pub fn RediSearch_QueryNodeClearChildren(arg1: *mut RSQNode);
}
unsafe extern "C" {
    pub fn RediSearch_QueryNodeGetChild(
        arg1: *const RSQNode,
        arg2: usize,
    ) -> *mut RSQNode;
}
unsafe extern "C" {
    pub fn RediSearch_QueryNodeNumChildren(arg1: *const RSQNode) -> usize;
}
unsafe extern "C" {
    pub fn RediSearch_QueryNodeType(qn: *mut RSQNode) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_QueryNodeGetFieldMask(qn: *mut RSQNode) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_GetResultsIterator(
        qn: *mut RSQNode,
        sp: *mut RSIndexHandle,
    ) -> *mut RSResultsIterator;
}
unsafe extern "C" {
    pub fn RediSearch_SetCriteriaTesterThreshold(num: usize);
}
unsafe extern "C" {
    #[doc = " Return an iterator over the results of the specified query string"]
    #[doc = " @param sp the index"]
    #[doc = " @param s the query string"]
    #[doc = " @param n the length of the string"]
    #[doc = " @param[out] error if not-NULL, will be set to the error message, if there is a"]
    #[doc = "  problem parsing the query"]
    #[doc = " @return an iterator over the results, or NULL if no iterator can be had"]
    #[doc = "  (see err, or no results)."]
    pub fn RediSearch_IterateQuery(
        sp: *mut RSIndexHandle,
        s: *const ::std::os::raw::c_char,
        n: usize,
        err: *mut *mut ::std::os::raw::c_char,
    ) -> *mut RSResultsIterator;
}
unsafe extern "C" {
    #[doc = " Return an iterator over the results of the specified query string"]
    #[doc = " @param sp the index"]
    #[doc = " @param s the query string"]
    #[doc = " @param n the length of the string"]
    #[doc = " @param dialect dialect version to be used for parsing the query"]
    #[doc = " @param[out] error if not-NULL, will be set to the error message, if there is a"]
    #[doc = "  problem parsing the query"]
    #[doc = " @return an iterator over the results, or NULL if no iterator can be had"]
    #[doc = "  (see err, or no results)."]
    pub fn RediSearch_IterateQueryWithDialect(
        sp: *mut RSIndexHandle,
        s: *const ::std::os::raw::c_char,
        n: usize,
        dialect: ::std::os::raw::c_uint,
        err: *mut *mut ::std::os::raw::c_char,
    ) -> *mut RSResultsIterator;
}
unsafe extern "C" {
    pub fn RediSearch_DocumentExists(
        sp: *mut RSIndexHandle,
        docKey: *const ::std::os::raw::c_void,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_ResultsIteratorNext(
        iter: *mut RSResultsIterator,
        sp: *mut RSIndexHandle,
        len: *mut usize,
    ) -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn RediSearch_ResultsIteratorFree(iter: *mut RSResultsIterator);
}
unsafe extern "C" {
    pub fn RediSearch_ResultsIteratorReset(iter: *mut RSResultsIterator);
}
unsafe extern "C" {
    pub fn RediSearch_ResultsIteratorGetScore(it: *const RSResultsIterator) -> f64;
}
unsafe extern "C" {
    pub fn RediSearch_IndexOptionsSetGCPolicy(
        options: *mut RSIndexOptions,
        policy: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn RediSearch_MemUsage(sp: *mut RSIndexHandle) -> usize;
}
unsafe extern "C" {
    pub fn RediSearch_TotalMemUsage() -> usize;
}
unsafe extern "C" {
    pub fn RediSearch_TotalInfo() -> TotalIndexesInfo;
}
unsafe extern "C" {
    pub fn RediSearch_GC_total() -> InfoGCStats;
}
unsafe extern "C" {
    #[doc = " Return an info struct"]
    #[doc = " @param sp the index"]
    #[doc = " @param info a pointer to RSIdxInfo struct with `.version = RS_INFO_CURRENT`"]
    pub fn RediSearch_IndexInfo(
        sp: *mut RSIndexHandle,
        info: *mut RSIdxInfo,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_IndexInfoFree(info: *mut RSIdxInfo);
}
unsafe extern "C" {
    #[doc = " Export the C API to be dynamically discoverable by other modules."]
    #[doc = " This is an internal function"]
    pub fn RediSearch_ExportCapi(ctx: *mut RedisModuleCtx) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn RediSearch_Init(
        ctx: *mut RedisModuleCtx,
        mode: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Cleans up all module-level globals (doc table, index options, trie,"]
    #[doc = " scoring functions, query expanders). Idempotent and only safe to call"]
    #[doc = " once Redis is shutting down and no more queries can arrive."]
    pub fn RediSearch_CleanupModule();
}
