# Base image
ARG BASE_IMAGE=falkordb/falkordb-compiler
ARG TARGETPLATFORM=linux/amd64

FROM $BASE_IMAGE AS compiler

# Define dependencies
ENV YUM_DEPS "automake libtool autoconf 2to3 python3-pip wget gcc make python3.11 python3.11-pip python3-devel m4 git cmake"

# Set up a build environment
RUN set -ex ;\
    RHEL_VERSION=$(rpm -E '%{rhel}') ;\
    dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-${RHEL_VERSION}.noarch.rpm; \
    yum update -y ;\
    yum install -y $YUM_DEPS ;\
    dnf install -y bzip2 glibc-devel ;\
    rm -f /usr/bin/python3 /usr/bin/pip3 ;\
    ln -s /usr/bin/python3.11 /usr/bin/python3 ;\
    ln -s /usr/bin/pip3.11 /usr/bin/pip3 ;\
    python3 --version ;\
    pip3 --version

# Build and install valgrind from source
RUN set -ex ;\
    cd /tmp ;\
    curl -LO https://sourceware.org/pub/valgrind/valgrind-3.22.0.tar.bz2 ;\
    tar -xjf valgrind-3.22.0.tar.bz2 ;\
    cd valgrind-3.22.0 ;\
    ./configure ;\
    make -j$(nproc) ;\
    make install ;\
    cd / ;\
    rm -rf /tmp/valgrind-3.22.0 /tmp/valgrind-3.22.0.tar.bz2

# Create virtual environment
RUN set -ex ;\
    python3 -m venv /venv

# Set path to include the virtual environment
ENV PATH=/venv/bin:$PATH

# Install Python dependencies
RUN set -ex ;\
    pip install --upgrade pip ;\
    pip install --upgrade setuptools

# Install Python packages from requirements.txt
RUN set -ex ;\
    pip install -r /FalkorDB/tests/requirements.txt
