# Base image
ARG BASE_IMAGE=falkordb/falkordb-compiler
ARG TARGETPLATFORM=linux/amd64

FROM $BASE_IMAGE AS compiler

# Define dependencies
ENV YUM_DEPS "automake libtool autoconf python3-pip wget gcc make python3.11 python3.11-pip python3-devel m4 git cmake"

# Set up a build environment
RUN set -ex ;\
    yum update -y ;\
    yum install -y $YUM_DEPS ;\
    yum install -y bzip2 glibc-devel ;\
    rm -f /usr/bin/python3 /usr/bin/pip3 ;\
    ln -s /usr/bin/python3.11 /usr/bin/python3 ;\
    ln -s /usr/bin/pip3.11 /usr/bin/pip3 ;\
    python3 --version ;\
    pip3 --version

# Redis: provided by the toolchain image
# (build/docker/builder/Dockerfile.amazonlinux2023) at
# /usr/local/bin/redis-server, pinned to 8.6.3.

# Create virtual environment
RUN set -ex ;\
    python3 -m venv /venv

# Set path to include the virtual environment
ENV PATH=/venv/bin:$PATH

# Install Python dependencies
RUN set -ex ;\
    pip install --upgrade pip ;\
    pip install --upgrade setuptools

# Install Python packages from requirements.txt
RUN set -ex ;\
    pip install -r /FalkorDB/tests/requirements.txt
