# Base image
ARG BASE_IMAGE=falkordb/falkordb-compiler
ARG TARGETPLATFORM=linux/amd64

FROM $BASE_IMAGE AS compiler

# Define dependencies
ENV YUM_DEPS "automake libtool autoconf 2to3 python3-pip wget gcc python3.11 python3.11-pip python3-devel m4 git valgrind cmake"

ENV DNF_DEPS "lsb-release"

# Set up a build environment
RUN set -ex ;\
    deps="$YUM_DEPS ";\
    yum update -y ;\
    yum install -y $deps ;

RUN set -ex ;\
    deps="$DNF_DEPS ";\
    dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm; \
    dnf install -y $deps

RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1; \
    alternatives --auto python3

# Create virtual environment
RUN set -ex ;\
    python3 -m venv /venv

# Set path to include the virtual environment
ENV PATH=/venv/bin:$PATH

# Install Python dependencies
RUN set -ex ;\
    pip install --upgrade pip ;\
    pip install --upgrade setuptools

# Install Python packages from requirements.txt
RUN set -ex ;\
    pip install -r /FalkorDB/tests/requirements.txt
