ARG BASE_IMAGE=falkordb/falkordb-compiler

ARG TARGETPLATFORM=linux/amd64

FROM $BASE_IMAGE AS compiler

ENV DEPS "curl lsb-release automake peg libtool autoconf python-is-python3 2to3 python3-venv python3-pip wget build-essential cmake m4 git valgrind gcc python3-dev clang"

# Set up a build environment
RUN set -ex ;\
    deps="$DEPS ";\
    apt-get update -qq ;\
    apt-get upgrade -y ;\
    apt-get install -y --no-install-recommends $deps ;

# Set up redis
RUN curl -fsSL https://packages.redis.io/gpg | gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg ;\
    echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/redis.list ;\
    apt-get update -qq ;\
    apt-get install -y redis

# Create venv
RUN set -ex ;\
    python3 -m venv /venv

ENV PATH=/venv/bin:$PATH

RUN set -ex ;\
    pip3 install --upgrade pip ;\
    pip3 install --upgrade setuptools

RUN set -ex ;\
    pip3 install -r /FalkorDB/tests/requirements.txt