-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [graph]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
module
public import Aeneas
public import IdList.Types
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open graph

/-- [core::io::error::{impl core::fmt::Debug for core::io::error::Error}::fmt]:
    Source: '/rustc/library/core/src/io/error.rs', lines 93:4-93:60
    Name pattern: [core::io::error::{core::fmt::Debug<core::io::error::Error>}::fmt]
    Visibility: public -/
@[rust_fun "core::io::error::{core::fmt::Debug<core::io::error::Error>}::fmt"]
axiom core.io.error.Error.Insts.CoreFmtDebug.fmt
  :
  core.io.error.Error → core.fmt.Formatter → Result ((core.result.Result
    Unit core.fmt.Error) × core.fmt.Formatter)

/-- [core::io::error::{impl core::fmt::Display for core::io::error::Error}::fmt]:
    Source: '/rustc/library/core/src/io/error.rs', lines 521:4-521:62
    Name pattern: [core::io::error::{core::fmt::Display<core::io::error::Error>}::fmt]
    Visibility: public -/
@[rust_fun
  "core::io::error::{core::fmt::Display<core::io::error::Error>}::fmt"]
axiom core.io.error.Error.Insts.CoreFmtDisplay.fmt
  :
  core.io.error.Error → core.fmt.Formatter → Result ((core.result.Result
    Unit core.fmt.Error) × core.fmt.Formatter)

/-- [core::io::impls::{impl core::io::write::Write for &'_0 mut W}::flush]:
    Source: '/rustc/library/core/src/io/impls.rs', lines 39:4-39:41
    Name pattern: [core::io::impls::{core::io::write::Write<&'0 mut @W>}::flush]
    Visibility: public -/
@[rust_fun "core::io::impls::{core::io::write::Write<&'0 mut @W>}::flush"]
axiom Mut0W.Insts.CoreIoWriteWrite.flush
  {W : Type} (writeWriteInst : core.io.write.Write W) :
  W → Result ((core.result.Result Unit core.io.error.Error) × W × (W →
    W))

/-- [core::io::impls::{impl core::io::write::Write for &'_0 mut W}::write]:
    Source: '/rustc/library/core/src/io/impls.rs', lines 24:4-24:56
    Name pattern: [core::io::impls::{core::io::write::Write<&'0 mut @W>}::write]
    Visibility: public -/
@[rust_fun "core::io::impls::{core::io::write::Write<&'0 mut @W>}::write"]
axiom Mut0W.Insts.CoreIoWriteWrite.write
  {W : Type} (writeWriteInst : core.io.write.Write W) :
  W → Slice Std.U8 → Result ((core.result.Result Std.Usize
    core.io.error.Error) × W × (W → W))

/-- [core::num::error::{impl core::fmt::Debug for core::num::error::TryFromIntError}::fmt]:
    Source: '/rustc/library/core/src/num/error.rs', lines 8:9-8:14
    Name pattern: [core::num::error::{core::fmt::Debug<core::num::error::TryFromIntError>}::fmt]
    Visibility: public -/
@[rust_fun
  "core::num::error::{core::fmt::Debug<core::num::error::TryFromIntError>}::fmt"]
axiom core.num.error.TryFromIntError.Insts.CoreFmtDebug.fmt
  :
  core.num.error.TryFromIntError → core.fmt.Formatter → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [core::f64::{f64}::to_le_bytes]:
    Source: '/rustc/library/core/src/num/f64.rs', lines 1409:4-1409:45
    Name pattern: [core::f64::{f64}::to_le_bytes]
    Visibility: public -/
@[rust_fun "core::f64::{f64}::to_le_bytes"]
axiom core.f64.F64.to_le_bytes : F64 → Result (Array Std.U8 8#usize)

/-- [core::num::{usize}::div_ceil]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3817:8-3817:54
    Name pattern: [core::num::{usize}::div_ceil]
    Visibility: public -/
@[rust_fun "core::num::{usize}::div_ceil"]
axiom core.num.Usize.div_ceil : Std.Usize → Std.Usize → Result Std.Usize

/-- [core::ops::range::{impl core::ops::range::RangeBounds<T> for core::ops::range::RangeInclusive<T>}::end_bound]:
    Source: '/rustc/library/core/src/ops/range.rs', lines 1146:4-1146:36
    Name pattern: [core::ops::range::{core::ops::range::RangeBounds<core::ops::range::RangeInclusive<@T>, @T>}::end_bound]
    Visibility: public -/
@[rust_fun
  "core::ops::range::{core::ops::range::RangeBounds<core::ops::range::RangeInclusive<@T>, @T>}::end_bound"]
axiom core.ops.range.RangeInclusive.Insts.CoreOpsRangeRangeBounds.end_bound
  {T : Type} :
  core.ops.range.RangeInclusive T → Result (core.ops.range.Bound T)

/-- [core::ops::range::{impl core::ops::range::RangeBounds<T> for core::ops::range::RangeInclusive<T>}::start_bound]:
    Source: '/rustc/library/core/src/ops/range.rs', lines 1143:4-1143:38
    Name pattern: [core::ops::range::{core::ops::range::RangeBounds<core::ops::range::RangeInclusive<@T>, @T>}::start_bound]
    Visibility: public -/
@[rust_fun
  "core::ops::range::{core::ops::range::RangeBounds<core::ops::range::RangeInclusive<@T>, @T>}::start_bound"]
axiom core.ops.range.RangeInclusive.Insts.CoreOpsRangeRangeBounds.start_bound
  {T : Type} :
  core.ops.range.RangeInclusive T → Result (core.ops.range.Bound T)

/-- [core::option::{impl core::fmt::Debug for core::option::Option<T>}::fmt]:
    Source: '/rustc/library/core/src/option.rs', lines 592:15-592:20
    Name pattern: [core::option::{core::fmt::Debug<core::option::Option<@T>>}::fmt]
    Visibility: public -/
@[rust_fun "core::option::{core::fmt::Debug<core::option::Option<@T>>}::fmt"]
axiom core.option.Option.Insts.CoreFmtDebug.fmt
  {T : Type} (fmtDebugInst : core.fmt.Debug T) :
  Option T → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [core::option::{core::option::Option<T>}::map]:
    Source: '/rustc/library/core/src/option.rs', lines 1160:4-1162:53
    Name pattern: [core::option::{core::option::Option<@T>}::map]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::map"]
axiom core.option.Option.map
  {T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) :
  Option T → F → Result (Option U)

/-- [core::option::{impl core::clone::Clone for core::option::Option<T>}::clone]:
    Source: '/rustc/library/core/src/option.rs', lines 2278:4-2278:27
    Name pattern: [core::option::{core::clone::Clone<core::option::Option<@T>>}::clone]
    Visibility: public -/
@[rust_fun
  "core::option::{core::clone::Clone<core::option::Option<@T>>}::clone"]
axiom core.option.Option.Insts.CoreCloneClone.clone
  {T : Type} (cloneCloneInst : core.clone.Clone T) :
  Option T → Result (Option T)

/-- [core::option::{impl core::default::Default for core::option::Option<T>}::default]:
    Source: '/rustc/library/core/src/option.rs', lines 2314:4-2314:29
    Name pattern: [core::option::{core::default::Default<core::option::Option<@T>>}::default]
    Visibility: public -/
@[rust_fun
  "core::option::{core::default::Default<core::option::Option<@T>>}::default"]
axiom core.option.Option.Insts.CoreDefaultDefault.default
  (T : Type) : Result (Option T)

/-- [core::option::{impl core::cmp::PartialEq<core::option::Option<T>> for core::option::Option<T>}::eq]:
    Source: '/rustc/library/core/src/option.rs', lines 2441:4-2441:38
    Name pattern: [core::option::{core::cmp::PartialEq<core::option::Option<@T>, core::option::Option<@T>>}::eq]
    Visibility: public -/
@[rust_fun
  "core::option::{core::cmp::PartialEq<core::option::Option<@T>, core::option::Option<@T>>}::eq"]
axiom core.option.Option.Insts.CoreCmpPartialEqOption.eq
  {T : Type} (cmpPartialEqInst : core.cmp.PartialEq T T) :
  Option T → Option T → Result Bool

/-- [core::slice::{[T]}::last]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 283:4-283:42
    Name pattern: [core::slice::{[@T]}::last]
    Visibility: public -/
@[rust_fun "core::slice::{[@T]}::last"]
axiom core.slice.Slice.last {T : Type} : Slice T → Result (Option T)

/-- [core::slice::{[T]}::last_mut]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 306:4-306:54
    Name pattern: [core::slice::{[@T]}::last_mut]
    Visibility: public -/
@[rust_fun "core::slice::{[@T]}::last_mut"]
axiom core.slice.Slice.last_mut
  {T : Type} : Slice T → Result ((Option T) × (Option T → Slice T))

/-- [core::str::{str}::len]:
    Source: '/rustc/library/core/src/str/mod.rs', lines 155:4-155:36
    Name pattern: [core::str::{str}::len]
    Visibility: public -/
@[rust_fun "core::str::{str}::len"]
axiom core.str.Str.len : Str → Result Std.Usize

/-- [core::str::{str}::as_bytes]:
    Source: '/rustc/library/core/src/str/mod.rs', lines 514:4-514:41
    Name pattern: [core::str::{str}::as_bytes]
    Visibility: public -/
@[rust_fun "core::str::{str}::as_bytes"]
axiom core.str.Str.as_bytes : Str → Result (Slice Std.U8)

/-- [alloc::string::{impl alloc::string::ToString for T}::to_string]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2965:4-2965:33
    Name pattern: [alloc::string::{alloc::string::ToString<@T>}::to_string]
    Visibility: public -/
@[rust_fun "alloc::string::{alloc::string::ToString<@T>}::to_string"]
axiom alloc.string.ToString.Blanket.to_string
  {T : Type} (corefmtDisplayInst : core.fmt.Display T) : T → Result String

/-- [roaring::treemap::fmt::{impl core::fmt::Debug for roaring::treemap::RoaringTreemap}::fmt]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/roaring-0.11.5/src/treemap/fmt.rs', lines 9:4-9:56
    Name pattern: [roaring::treemap::fmt::{core::fmt::Debug<roaring::treemap::RoaringTreemap>}::fmt]
    Visibility: public -/
@[rust_fun
  "roaring::treemap::fmt::{core::fmt::Debug<roaring::treemap::RoaringTreemap>}::fmt"]
axiom roaring.treemap.RoaringTreemap.Insts.CoreFmtDebug.fmt
  :
  roaring.treemap.RoaringTreemap → core.fmt.Formatter → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::new]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/roaring-0.11.5/src/treemap/inherent.rs', lines 23:4-23:34
    Name pattern: [roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::new]
    Visibility: public -/
@[rust_fun
  "roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::new"]
axiom roaring.treemap.inherent.RoaringTreemap.new
  : Result roaring.treemap.RoaringTreemap

/-- [roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::insert]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/roaring-0.11.5/src/treemap/inherent.rs', lines 51:4-51:48
    Name pattern: [roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::insert]
    Visibility: public -/
@[rust_fun
  "roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::insert"]
axiom roaring.treemap.inherent.RoaringTreemap.insert
  :
  roaring.treemap.RoaringTreemap → Std.U64 → Result (Bool ×
    roaring.treemap.RoaringTreemap)

/-- [roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::insert_range]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/roaring-0.11.5/src/treemap/inherent.rs', lines 71:4-71:72
    Name pattern: [roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::insert_range]
    Visibility: public -/
@[rust_fun
  "roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::insert_range"]
axiom roaring.treemap.inherent.RoaringTreemap.insert_range
  {R : Type} (coreopsrangeRangeBoundsRU64Inst : core.ops.range.RangeBounds R
  Std.U64) :
  roaring.treemap.RoaringTreemap → R → Result (Std.U64 ×
    roaring.treemap.RoaringTreemap)

/-- [roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::len]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/roaring-0.11.5/src/treemap/inherent.rs', lines 432:4-432:28
    Name pattern: [roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::len]
    Visibility: public -/
@[rust_fun
  "roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::len"]
axiom roaring.treemap.inherent.RoaringTreemap.len
  : roaring.treemap.RoaringTreemap → Result Std.U64

/-- [roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::optimize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/roaring-0.11.5/src/treemap/inherent.rs', lines 448:4-448:38
    Name pattern: [roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::optimize]
    Visibility: public -/
@[rust_fun
  "roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::optimize"]
axiom roaring.treemap.inherent.RoaringTreemap.optimize
  :
  roaring.treemap.RoaringTreemap → Result (Bool ×
    roaring.treemap.RoaringTreemap)

/-- [roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::min]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/roaring-0.11.5/src/treemap/inherent.rs', lines 479:4-479:36
    Name pattern: [roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::min]
    Visibility: public -/
@[rust_fun
  "roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::min"]
axiom roaring.treemap.inherent.RoaringTreemap.min
  : roaring.treemap.RoaringTreemap → Result (Option Std.U64)

/-- [roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::max]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/roaring-0.11.5/src/treemap/inherent.rs', lines 500:4-500:36
    Name pattern: [roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::max]
    Visibility: public -/
@[rust_fun
  "roaring::treemap::inherent::{roaring::treemap::RoaringTreemap}::max"]
axiom roaring.treemap.inherent.RoaringTreemap.max
  : roaring.treemap.RoaringTreemap → Result (Option Std.U64)

/-- [roaring::treemap::inherent::{impl core::clone::Clone for roaring::treemap::RoaringTreemap}::clone]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/roaring-0.11.5/src/treemap/inherent.rs', lines 572:4-572:27
    Name pattern: [roaring::treemap::inherent::{core::clone::Clone<roaring::treemap::RoaringTreemap>}::clone]
    Visibility: public -/
@[rust_fun
  "roaring::treemap::inherent::{core::clone::Clone<roaring::treemap::RoaringTreemap>}::clone"]
axiom roaring.treemap.RoaringTreemap.Insts.CoreCloneClone.clone
  : roaring.treemap.RoaringTreemap → Result roaring.treemap.RoaringTreemap

/-- [roaring::treemap::ops::{impl core::ops::bit::BitOrAssign<&'_0 roaring::treemap::RoaringTreemap> for roaring::treemap::RoaringTreemap}::bitor_assign]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/roaring-0.11.5/src/treemap/ops.rs', lines 173:4-173:52
    Name pattern: [roaring::treemap::ops::{core::ops::bit::BitOrAssign<roaring::treemap::RoaringTreemap, &'0 roaring::treemap::RoaringTreemap>}::bitor_assign]
    Visibility: public -/
@[rust_fun
  "roaring::treemap::ops::{core::ops::bit::BitOrAssign<roaring::treemap::RoaringTreemap, &'0 roaring::treemap::RoaringTreemap>}::bitor_assign"]
axiom
  roaring.treemap.RoaringTreemap.Insts.CoreOpsBitBitOrAssignShared0RoaringTreemap.bitor_assign
  :
  roaring.treemap.RoaringTreemap → roaring.treemap.RoaringTreemap → Result
    roaring.treemap.RoaringTreemap

/-- [roaring::treemap::serialization::{roaring::treemap::RoaringTreemap}::serialized_size]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/roaring-0.11.5/src/treemap/serialization.rs', lines 22:4-22:42
    Name pattern: [roaring::treemap::serialization::{roaring::treemap::RoaringTreemap}::serialized_size]
    Visibility: public -/
@[rust_fun
  "roaring::treemap::serialization::{roaring::treemap::RoaringTreemap}::serialized_size"]
axiom roaring.treemap.serialization.RoaringTreemap.serialized_size
  : roaring.treemap.RoaringTreemap → Result Std.Usize

/-- [roaring::treemap::serialization::{roaring::treemap::RoaringTreemap}::serialize_into]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/roaring-0.11.5/src/treemap/serialization.rs', lines 43:4-43:79
    Name pattern: [roaring::treemap::serialization::{roaring::treemap::RoaringTreemap}::serialize_into]
    Visibility: public -/
@[rust_fun
  "roaring::treemap::serialization::{roaring::treemap::RoaringTreemap}::serialize_into"]
axiom roaring.treemap.serialization.RoaringTreemap.serialize_into
  {W : Type} (coreiowriteWriteInst : core.io.write.Write W) :
  roaring.treemap.RoaringTreemap → W → Result (core.result.Result Unit
    core.io.error.Error)

/-- [roaring::treemap::serialization::{roaring::treemap::RoaringTreemap}::deserialize_from]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/roaring-0.11.5/src/treemap/serialization.rs', lines 71:4-71:71
    Name pattern: [roaring::treemap::serialization::{roaring::treemap::RoaringTreemap}::deserialize_from]
    Visibility: public -/
@[rust_fun
  "roaring::treemap::serialization::{roaring::treemap::RoaringTreemap}::deserialize_from"]
axiom roaring.treemap.serialization.RoaringTreemap.deserialize_from
  {R : Type} (allocioreadReadInst : alloc.io.read.Read R) :
  R → Result (core.result.Result roaring.treemap.RoaringTreemap
    core.io.error.Error)

/-- [smallvec::{smallvec::SmallVec<A, Clause0_Item>}::new]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.16.0/src/lib.rs', lines 828:4-828:31
    Name pattern: [smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::new]
    Visibility: public -/
@[rust_fun "smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::new"]
axiom smallvec.SmallVec.new
  {A : Type} {Clause0_Item : Type} (ArrayInst : smallvec.Array A Clause0_Item)
  :
  Result (smallvec.SmallVec A Clause0_Item)

/-- [smallvec::{smallvec::SmallVec<A, Clause0_Item>}::len]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.16.0/src/lib.rs', lines 1003:4-1003:30
    Name pattern: [smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::len]
    Visibility: public -/
@[rust_fun "smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::len"]
axiom smallvec.SmallVec.len
  {A : Type} {Clause0_Item : Type} (ArrayInst : smallvec.Array A Clause0_Item)
  :
  smallvec.SmallVec A Clause0_Item → Result Std.Usize

/-- [smallvec::{smallvec::SmallVec<A, Clause0_Item>}::push]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.16.0/src/lib.rs', lines 1188:4-1188:42
    Name pattern: [smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::push]
    Visibility: public -/
@[rust_fun "smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::push"]
axiom smallvec.SmallVec.push
  {A : Type} {Clause0_Item : Type} (ArrayInst : smallvec.Array A Clause0_Item)
  :
  smallvec.SmallVec A Clause0_Item → Clause0_Item → Result
    (smallvec.SmallVec A Clause0_Item)

/-- [smallvec::{smallvec::SmallVec<A, Clause0_Item>}::pop]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.16.0/src/lib.rs', lines 1205:4-1205:44
    Name pattern: [smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::pop]
    Visibility: public -/
@[rust_fun "smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::pop"]
axiom smallvec.SmallVec.pop
  {A : Type} {Clause0_Item : Type} (ArrayInst : smallvec.Array A Clause0_Item)
  :
  smallvec.SmallVec A Clause0_Item → Result ((Option Clause0_Item) ×
    (smallvec.SmallVec A Clause0_Item))

/-- [smallvec::{smallvec::SmallVec<A, Clause0_Item>}::truncate]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.16.0/src/lib.rs', lines 1379:4-1379:42
    Name pattern: [smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::truncate]
    Visibility: public -/
@[rust_fun "smallvec::{smallvec::SmallVec<@A, @Clause0_Item>}::truncate"]
axiom smallvec.SmallVec.truncate
  {A : Type} {Clause0_Item : Type} (ArrayInst : smallvec.Array A Clause0_Item)
  :
  smallvec.SmallVec A Clause0_Item → Std.Usize → Result (smallvec.SmallVec
    A Clause0_Item)

/-- [smallvec::{impl core::ops::deref::Deref<[Clause0_Item]> for smallvec::SmallVec<A, Clause0_Item>}::deref]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.16.0/src/lib.rs', lines 1942:4-1942:33
    Name pattern: [smallvec::{core::ops::deref::Deref<smallvec::SmallVec<@A, @Clause0_Item>, [@Clause0_Item]>}::deref]
    Visibility: public -/
@[rust_fun
  "smallvec::{core::ops::deref::Deref<smallvec::SmallVec<@A, @Clause0_Item>, [@Clause0_Item]>}::deref"]
axiom smallvec.SmallVec.Insts.CoreOpsDerefDerefSlice.deref
  {A : Type} {Clause0_Item : Type} (ArrayInst : smallvec.Array A Clause0_Item)
  :
  smallvec.SmallVec A Clause0_Item → Result (Slice Clause0_Item)

/-- [smallvec::{impl core::ops::deref::DerefMut<[Clause0_Item]> for smallvec::SmallVec<A, Clause0_Item>}::deref_mut]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.16.0/src/lib.rs', lines 1952:4-1952:45
    Name pattern: [smallvec::{core::ops::deref::DerefMut<smallvec::SmallVec<@A, @Clause0_Item>, [@Clause0_Item]>}::deref_mut]
    Visibility: public -/
@[rust_fun
  "smallvec::{core::ops::deref::DerefMut<smallvec::SmallVec<@A, @Clause0_Item>, [@Clause0_Item]>}::deref_mut"]
axiom smallvec.SmallVec.Insts.CoreOpsDerefDerefMutSlice.deref_mut
  {A : Type} {Clause0_Item : Type} (ArrayInst : smallvec.Array A Clause0_Item)
  :
  smallvec.SmallVec A Clause0_Item → Result ((Slice Clause0_Item) × (Slice
    Clause0_Item → smallvec.SmallVec A Clause0_Item))

/-- [smallvec::{impl core::ops::index::Index<I, Clause1_Output> for smallvec::SmallVec<A, Clause0_Item>}::index]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.16.0/src/lib.rs', lines 2152:4-2152:43
    Name pattern: [smallvec::{core::ops::index::Index<smallvec::SmallVec<@A, @Clause0_Item>, @I, @Clause1_Output>}::index]
    Visibility: public -/
@[rust_fun
  "smallvec::{core::ops::index::Index<smallvec::SmallVec<@A, @Clause0_Item>, @I, @Clause1_Output>}::index"]
axiom smallvec.SmallVec.Insts.CoreOpsIndexIndex.index
  {A : Type} {I : Type} {Clause0_Item : Type} {Clause1_Output : Type}
  (ArrayInst : smallvec.Array A Clause0_Item)
  (coresliceindexSliceIndexISliceClause1_OutputInst :
  core.slice.index.SliceIndex I (Slice Clause0_Item) Clause1_Output) :
  smallvec.SmallVec A Clause0_Item → I → Result Clause1_Output

/-- [smallvec::{impl core::default::Default for smallvec::SmallVec<A, Clause0_Item>}::default]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.16.0/src/lib.rs', lines 2219:4-2219:31
    Name pattern: [smallvec::{core::default::Default<smallvec::SmallVec<@A, @Clause0_Item>>}::default]
    Visibility: public -/
@[rust_fun
  "smallvec::{core::default::Default<smallvec::SmallVec<@A, @Clause0_Item>>}::default"]
axiom smallvec.SmallVec.Insts.CoreDefaultDefault.default
  {A : Type} {Clause0_Item : Type} (ArrayInst : smallvec.Array A Clause0_Item)
  :
  Result (smallvec.SmallVec A Clause0_Item)

/-- [smallvec::{impl core::clone::Clone for smallvec::SmallVec<A, Clause0_Item>}::clone]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.16.0/src/lib.rs', lines 2257:4-2257:34
    Name pattern: [smallvec::{core::clone::Clone<smallvec::SmallVec<@A, @Clause0_Item>>}::clone]
    Visibility: public -/
@[rust_fun
  "smallvec::{core::clone::Clone<smallvec::SmallVec<@A, @Clause0_Item>>}::clone"]
axiom smallvec.SmallVec.Insts.CoreCloneClone.clone
  {A : Type} {Clause0_Item : Type} (ArrayInst : smallvec.Array A Clause0_Item)
  (corecloneCloneInst : core.clone.Clone Clause0_Item) :
  smallvec.SmallVec A Clause0_Item → Result (smallvec.SmallVec A
    Clause0_Item)

/-- [smallvec::{impl core::iter::traits::collect::IntoIterator<&'a Clause0_Item, core::slice::iter::Iter<'a, Clause0_Item>> for &'a smallvec::SmallVec<A, Clause0_Item>}::into_iter]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.16.0/src/lib.rs', lines 2430:4-2430:40
    Name pattern: [smallvec::{core::iter::traits::collect::IntoIterator<&'a smallvec::SmallVec<@A, @Clause0_Item>, &'a @Clause0_Item, core::slice::iter::Iter<'a, @Clause0_Item>>}::into_iter]
    Visibility: public -/
@[rust_fun
  "smallvec::{core::iter::traits::collect::IntoIterator<&'a smallvec::SmallVec<@A, @Clause0_Item>, &'a @Clause0_Item, core::slice::iter::Iter<'a, @Clause0_Item>>}::into_iter"]
axiom
  SharedASmallVec.Insts.CoreIterTraitsCollectIntoIteratorSharedAClause0_ItemIter.into_iter
  {A : Type} {Clause0_Item : Type} (ArrayInst : smallvec.Array A Clause0_Item)
  :
  smallvec.SmallVec A Clause0_Item → Result (core.slice.iter.Iter
    Clause0_Item)

/-- [smallvec::{impl smallvec::Array<T> for [T; 2usize]}::size]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.16.0/src/lib.rs', lines 2550:16-2550:34
    Name pattern: [smallvec::{smallvec::Array<[@T; 2], @T>}::size]
    Visibility: public -/
@[rust_fun "smallvec::{smallvec::Array<[@T; 2], @T>}::size"]
axiom ArrayT2.Insts.SmallvecArray.size (T : Type) : Result Std.Usize

