-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [graph]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [core::io::error::Error]
    Source: '/rustc/library/core/src/io/error.rs', lines 87:0-87:16
    Name pattern: [core::io::error::Error]
    Visibility: public -/
@[rust_type "core::io::error::Error"]
axiom core.io.error.Error : Type

/-- [roaring::treemap::RoaringTreemap]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/roaring-0.11.5/src/treemap/mod.rs', lines 40:0-40:25
    Name pattern: [roaring::treemap::RoaringTreemap]
    Visibility: public -/
@[rust_type "roaring::treemap::RoaringTreemap"]
axiom roaring.treemap.RoaringTreemap : Type

/-- [smallvec::SmallVec]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.16.0/src/lib.rs', lines 815:0-815:29
    Name pattern: [smallvec::SmallVec]
    Visibility: public -/
@[rust_type "smallvec::SmallVec"]
axiom smallvec.SmallVec (A : Type) (Clause0_Item : Type) : Type

