-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [graph]: type definitions
module
public import Aeneas
public import IdList.TypesExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace graph

/-- Trait declaration: [core::io::write::Write]
    Source: '/rustc/library/core/src/io/write.rs', lines 52:0-52:15
    Name pattern: [core::io::write::Write]
    Visibility: public -/
@[rust_trait "core::io::write::Write"]
structure core.io.write.Write (Self : Type) where
  write : Self → Slice Std.U8 → Result ((core.result.Result Std.Usize
    core.io.error.Error) × Self)
  flush : Self → Result ((core.result.Result Unit core.io.error.Error) ×
    Self)

/-- [core::ops::range::Bound]
    Source: '/rustc/library/core/src/ops/range.rs', lines 710:0-710:17
    Name pattern: [core::ops::range::Bound]
    Visibility: public -/
@[discriminant isize, rust_type "core::ops::range::Bound"]
inductive core.ops.range.Bound (T : Type) where
| Included : T → core.ops.range.Bound T
| Excluded : T → core.ops.range.Bound T
| Unbounded : core.ops.range.Bound T

/-- Trait declaration: [core::ops::range::RangeBounds]
    Source: '/rustc/library/core/src/ops/range.rs', lines 838:0-838:38
    Name pattern: [core::ops::range::RangeBounds]
    Visibility: public -/
@[rust_trait "core::ops::range::RangeBounds"]
structure core.ops.range.RangeBounds (Self : Type) (T : Type) where
  start_bound : Self → Result (core.ops.range.Bound T)
  end_bound : Self → Result (core.ops.range.Bound T)

/-- Trait declaration: [alloc::io::read::Read]
    Source: '/rustc/library/alloc/src/io/read.rs', lines 87:0-87:14
    Name pattern: [alloc::io::read::Read]
    Visibility: public -/
@[rust_trait "alloc::io::read::Read"]
structure alloc.io.read.Read (Self : Type) where

/-- Trait declaration: [smallvec::Array]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/smallvec-1.16.0/src/lib.rs', lines 2444:0-2444:22
    Name pattern: [smallvec::Array]
    Visibility: public -/
@[rust_trait "smallvec::Array"]
structure smallvec.Array (Self : Type) (Self_Item : Type) where
  size : Result Std.Usize

/-- [graph::index::IndexType]
    Source: 'graph/src/index/mod.rs', lines 96:0-104:1
    Visibility: public -/
@[discriminant isize]
inductive index.IndexType where
| Range : index.IndexType
| Fulltext : index.IndexType
| Vector : index.IndexType

/-- [graph::effects::v3::BadFieldType]
    Source: 'graph/src/effects/v3/mod.rs', lines 305:0-324:1
    Visibility: public -/
@[discriminant isize]
inductive effects.v3.BadFieldType where
| UnknownBit : Std.U32 → Std.U32 → effects.v3.BadFieldType
| MixedKinds :
  Std.U32 →
  Std.U32 →
  index.IndexType →
  index.IndexType →
  effects.v3.BadFieldType

/-- [graph::effects::error::EncodeError]
    Source: 'graph/src/effects/error.rs', lines 23:0-87:1
    Visibility: public -/
@[discriminant isize]
inductive effects.error.EncodeError where
| EndpointColumnMisaligned :
  Str →
  Std.Usize →
  Std.Usize →
  effects.error.EncodeError
| OptionsFieldTypeMismatch : Std.U32 → effects.error.EncodeError
| BadFieldType : effects.v3.BadFieldType → effects.error.EncodeError
| EmptyIndexSchemaList : effects.error.EncodeError
| HeaderShapeMismatch : Std.U32 → effects.error.EncodeError
| BlockCountTooLarge : Str → Std.Usize → effects.error.EncodeError
| BitmapLengthLied : Std.Usize → Std.Usize → effects.error.EncodeError

/-- [graph::effects::error::DecodeError]
    Source: 'graph/src/effects/error.rs', lines 97:0-220:1
    Visibility: public -/
@[discriminant isize]
inductive effects.error.DecodeError where
| UnexpectedEof : Std.Usize → Std.Usize → effects.error.DecodeError
| ImplausibleCount : Std.U64 → Std.Usize → effects.error.DecodeError
| BadEncoding : Std.U8 → effects.error.DecodeError
| BadRoaring : String → effects.error.DecodeError
| CardinalityMismatch : Std.U64 → Std.U64 → effects.error.DecodeError
| RankOutOfRange : Std.U64 → Std.U64 → effects.error.DecodeError
| BadIndexWidth : Std.U8 → effects.error.DecodeError
| BadValueType : Std.U32 → effects.error.DecodeError
| BadString : effects.error.DecodeError
| UnsupportedVersion : Std.U8 → effects.error.DecodeError
| BadOpcode : Std.U32 → effects.error.DecodeError
| BadFieldType : effects.v3.BadFieldType → effects.error.DecodeError
| EmptyIndexSchemaList : effects.error.DecodeError
| UnknownFlags : Std.U8 → effects.error.DecodeError
| BadCompression : String → effects.error.DecodeError
| CompressedLengthMismatch :
  Std.Usize →
  Std.Usize →
  effects.error.DecodeError
| TrailingBytes : Std.Usize → effects.error.DecodeError
| EmptyRecord : Std.U32 → effects.error.DecodeError
| BadBool : Std.U64 → effects.error.DecodeError
| BadSimilarityFunction : Std.U64 → effects.error.DecodeError
| BadSchemaType : Std.U32 → effects.error.DecodeError
| BadConstraintType : Std.U32 → effects.error.DecodeError
| BadEntityType : Std.U32 → effects.error.DecodeError
| ChecksumMismatch : Std.U32 → Std.U32 → effects.error.DecodeError
| BadConstraintStatus : Std.U32 → effects.error.DecodeError
| BadRange : Std.U64 → Std.U64 → effects.error.DecodeError

/-- Trait declaration: [graph::effects::writer::EffectWrite]
    Source: 'graph/src/effects/writer.rs', lines 44:0-162:1
    Visibility: public -/
structure effects.writer.EffectWrite (Self : Type) where
  coreiowriteWriteInst : core.io.write.Write Self
  u8 : Self → Std.U8 → Result Self
  u16 : Self → Std.U16 → Result Self
  u32 : Self → Std.U32 → Result Self
  u64 : Self → Std.U64 → Result Self
  i64 : Self → Std.I64 → Result Self
  f64 : Self → F64 → Result Self
  schema_id : Self → Std.U32 → Result Self
  bytes : Self → Slice Std.U8 → Result Self
  written : Self → Result Std.Usize
  reserve : Self → Std.Usize → Result Self
  string : Self → Str → Result Self

/-- Trait declaration: [graph::effects::EffectEncode]
    Source: 'graph/src/effects/mod.rs', lines 321:0-332:1
    Visibility: public -/
structure effects.EffectEncode (Self : Type) (VERSION : Std.U8) where
  encode : forall {W : Type} (writerEffectWriteInst :
    effects.writer.EffectWrite W), Self → W → Result ((core.result.Result
    Unit effects.error.EncodeError) × W)

/-- [graph::effects::reader::Reader]
    Source: 'graph/src/effects/reader.rs', lines 11:0-14:1
    Visibility: public -/
structure effects.reader.Reader where
  buf : Slice Std.U8
  pos : Std.Usize

/-- [graph::effects::v3::id_list::Run]
    Source: 'graph/src/effects/v3/id_list.rs', lines 182:0-221:1 -/
structure effects.v3.id_list.Run where
  start : Std.Usize
  desc : Option Bool
  range_bytes : Std.Usize
  started : Bool
  closed_bitmaps : Std.Usize
  bitmap_key : Std.U64
  closed_buckets : Std.Usize
  closed_body : Std.Usize
  closed_has_run : Bool
  bucket : Std.U64
  bucket_ids : Std.U64
  bucket_runs : Std.U32

/-- [graph::effects::v3::id_list::Segment]
    Source: 'graph/src/effects/v3/id_list.rs', lines 450:0-512:1 -/
@[discriminant isize]
inductive effects.v3.id_list.Segment where
| Range : Std.U64 → Std.U32 → effects.v3.id_list.Segment
| Repeat : Std.U64 → Std.U32 → effects.v3.id_list.Segment
| RangeDescending : Std.U64 → Std.U32 → effects.v3.id_list.Segment
| Ascending :
  roaring.treemap.RoaringTreemap →
  Std.U32 →
  Std.U64 →
  Std.U64 →
  effects.v3.id_list.Segment
| Descending :
  roaring.treemap.RoaringTreemap →
  Std.U32 →
  Std.U64 →
  Std.U64 →
  effects.v3.id_list.Segment

/-- [graph::effects::v3::id_list::{graph::effects::v3::id_list::Segment}::decode::{closure}]
    Source: 'graph/src/effects/v3/id_list.rs', lines 686:25-686:67 -/
@[reducible]
def effects.v3.id_list.Segment.decode.closure := Unit

/-- [graph::effects::v3::id_list::IdList]
    Source: 'graph/src/effects/v3/id_list.rs', lines 783:0-793:1
    Visibility: public -/
structure effects.v3.id_list.IdList where
  segments : smallvec.SmallVec (Array effects.v3.id_list.Segment 2#usize)
    effects.v3.id_list.Segment
  len : Std.Usize
  run : effects.v3.id_list.Run

/-- [graph::effects::v3::id_list::{graph::effects::v3::id_list::IdList}::push::{closure}]
    Source: 'graph/src/effects/v3/id_list.rs', lines 994:46-994:68 -/
@[reducible]
def effects.v3.id_list.IdList.push.closure := Unit

end graph
