/* automatically generated by rust-bindgen 0.72.0 */

// Auto-generated LAGraph FFI bindings
#![allow(
    non_camel_case_types,
    non_upper_case_globals,
    non_snake_case,
    dead_code,
    improper_ctypes
)]
use super::{
    GrB_BinaryOp, GrB_Index, GrB_Info, GrB_Matrix, GrB_Mode, GrB_Monoid, GrB_Scalar, GrB_Semiring,
    GrB_Type, GrB_UnaryOp, GrB_Vector,
};

pub const LAGRAPH_DATE: &[u8; 13] = b"Sept 8, 2025\0";
pub const LAGRAPH_VERSION_MAJOR: u32 = 1;
pub const LAGRAPH_VERSION_MINOR: u32 = 2;
pub const LAGRAPH_VERSION_UPDATE: u32 = 1;
pub const LAGRAPH_VANILLA: u32 = 0;
pub const LAGRAPH_SUITESPARSE: u32 = 1;
pub const LAGRAPH_MAX_NAME_LEN: u32 = 128;
pub const LAGRAPH_INVALID_GRAPH: i32 = -1000;
pub const LAGRAPH_SYMMETRIC_STRUCTURE_REQUIRED: i32 = -1001;
pub const LAGRAPH_IO_ERROR: i32 = -1002;
pub const LAGRAPH_NOT_CACHED: i32 = -1003;
pub const LAGRAPH_NO_SELF_EDGES_ALLOWED: i32 = -1004;
pub const LAGRAPH_CONVERGENCE_FAILURE: i32 = -1005;
pub const LAGRAPH_CACHE_NOT_NEEDED: u32 = 1000;
pub const LAGRAPH_MSG_LEN: u32 = 256;
pub const LAGRAPH_UNKNOWN: i32 = -1;

// Opaque C FILE type (we don't use the FILE-based functions)
#[repr(C)]
pub struct FILE {
    _opaque: [u8; 0],
}

unsafe extern "C" {
    #[doc = " LAGraph_Malloc: allocates a block of memory.  Uses the ANSI C11 malloc\n function if LAGraph_Init was used, or the user_malloc_function passed to\n LAGr_Init.\n\n @param[out] p        handle to allocated memory.\n @param[in] nitems    number of items to allocate, each of size size_of_item.\n @param[in] size_of_item  bytes allocted = nitems*size_of_item.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_OUT_OF_MEMORY if out of memory.\n @retval GrB_NULL_POINTER if p is NULL on input."]
    pub fn LAGraph_Malloc(
        p: *mut *mut ::std::os::raw::c_void,
        nitems: usize,
        size_of_item: usize,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Calloc: allocates a block of memory and sets it to zero.  Uses the\n ANSI C11 malloc and memset functions if LAGraph_Init was used or if NULL\n was passed to LAGr_Init for the user_calloc_function, or the non-NULL\n user_calloc_function passed to LAGr_Init otherwise.\n\n @param[out] p        handle to allocated memory.\n @param[in] nitems    number of items to allocate, each of size size_of_item.\n @param[in] size_of_item  bytes allocted = nitems*size_of_item.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_OUT_OF_MEMORY if out of memory.\n @retval GrB_NULL_POINTER if p is NULL on input."]
    pub fn LAGraph_Calloc(
        p: *mut *mut ::std::os::raw::c_void,
        nitems: usize,
        size_of_item: usize,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Realloc: reallocates a block of memory.  Uses the ANSI C11 malloc,\n memcpy, and free functions if LAGraph_Init was used or if NULL was passed to\n LAGr_Init for the user_realloc_function, or the non-NULL\n user_realloc_function passed to LAGr_Init otherwise.  Note that unlike the\n ANSI C11 realloc function, this function requires the old size of block to\n be provided on input (nitems_old).  This size must be exact; behavior is\n undefined if the incorrect size is given.  The value nitems_old*size_of_item\n must be the same as nitems*size_of_item when the block of memory was\n allocated by LAGraph_Malloc or LAGraph_Calloc, or equal to\n nitems_new*size_of_item from the last call to LAGraph_Realloc.\n\n @param[in,out] p     handle to allocated memory.\n @param[in] nitems_new    new number of items to allocate.\n @param[in] nitems_old    prior number of items allocated.\n @param[in] size_of_item  size of each item.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_OUT_OF_MEMORY if out of memory.\n @retval GrB_NULL_POINTER if p is NULL on input."]
    pub fn LAGraph_Realloc(
        p: *mut *mut ::std::os::raw::c_void,
        nitems_new: usize,
        nitems_old: usize,
        size_of_item: usize,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Free: frees a block of memory.  The block must have been previously\n allocated by LAGraph_Malloc or LAGraph_Calloc.  If LAGraph_Malloc (&p, ...)\n is the pointer to the allocated block of memory, LAGraph_Free (&p, ...) is\n the method to free it.  The parameter is passed as &p so that p can be set\n to NULL on return, to guard against double-free.  LAGraph_Free does nothing\n if &p or p are NULL on input; this is not an error.\n\n @param[in,out] p     handle to allocated memory.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS in all cases."]
    pub fn LAGraph_Free(
        p: *mut *mut ::std::os::raw::c_void,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
#[repr(i32)]
#[doc = " LAGraph_Kind: the kind of a graph.  Currently, only two types of graphs are\n supported: undirected graphs and directed graphs.  Edge weights are assumed\n to be present.  Unweighted graphs can be represented by setting all entries\n present in the sparsity structure to the same value, typically 1.\n Additional types of graphs will be added in the future."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum LAGraph_Kind {
    #[doc = "< undirected graph.\n< G->A is square and symmetric; both upper and lower triangular parts\n< are present.  A(i,j) is the edge (i,j).  Results are undefined if\n< A is unsymmetric."]
    LAGraph_ADJACENCY_UNDIRECTED = 0,
    #[doc = "< directed graph.\n< G->A is square; A(i,j) is the edge (i,j)."]
    LAGraph_ADJACENCY_DIRECTED = 1,
    #[doc = "< unknown kind of graph (-1)."]
    LAGraph_KIND_UNKNOWN = -1,
}
#[repr(i32)]
#[doc = " LAGraph_Boolean: a boolean value (true or false) or unknown (-1)."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum LAGraph_Boolean {
    #[doc = "< the Boolean value is known to be false."]
    LAGraph_FALSE = 0,
    #[doc = "< the Boolean value is known to be true."]
    LAGraph_TRUE = 1,
    #[doc = "< Boolean value is unknown."]
    LAGraph_BOOLEAN_UNKNOWN = -1,
}
#[repr(i32)]
#[doc = " LAGraph_State describes the status of a cached property of a graph.  If the\n cached property is computed in floating-point arithmetic, it may have been\n computed with roundoff error, but it may still be declared as \"value\" if the\n roundoff error is expected to be small, or if the cached property was\n computed as carefully as possible (to within reasonable roundoff error).\n The \"bound\" state indicates that the cached property is an upper or lower\n bound, depending on the particular cached property.  If computed in\n floating-point arithmetic, an \"upper bound\" cached property may be actually\n slightly lower than the actual upper bound, because of floating-point\n roundoff."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum LAGraph_State {
    #[doc = "< cached property is a known value."]
    LAGraph_VALUE = 0,
    #[doc = "< cached property is a bound.\n< The bound is upper or lower, depending on the particular cached\n< property."]
    LAGraph_BOUND = 1,
    #[doc = "< the property is unknown."]
    LAGraph_STATE_UNKNOWN = -1,
}
#[repr(C)]
pub struct LAGraph_Graph_struct {
    #[doc = "< the adjacency matrix of the graph"]
    pub A: GrB_Matrix,
    #[doc = "< the kind of graph"]
    pub kind: LAGraph_Kind,
    #[doc = "< AT = A', the transpose of A, with the same type."]
    pub AT: GrB_Matrix,
    #[doc = "< a GrB_INT64 vector of length m, if A is m-by-n.\n< where out_degree(i) is the number of entries in A(i,:).  If\n< out_degree is sparse and the entry out_degree(i) is not present,\n< then it is assumed to be zero."]
    pub out_degree: GrB_Vector,
    #[doc = "< a GrB_INT64 vector of length n, if A is m-by-n.\n< where in_degree(j) is the number of entries in A(:,j).  If\n< in_degree is sparse and the entry in_degree(j) is not present,\n< then it is assumed to be zero.  If A is known to have a\n< symmetric structure, the convention is that the degree is held\n< in G->out_degree, and in G->in_degree is left as NULL."]
    pub in_degree: GrB_Vector,
    #[doc = "< For an undirected\n< graph, this cached property will always be implicitly true and\n< can be ignored.  The matrix A for a directed weighted graph\n< will typically be unsymmetric, but might have a symmetric\n< structure.  In that case, this scalar cached property can be\n< set to true. By default, this cached property is set to\n< LAGRAPH_UNKNOWN."]
    pub is_symmetric_structure: LAGraph_Boolean,
    #[doc = "< number of entries on the diagonal of A, or\n< LAGRAPH_UNKNOWN if unknown.  For the adjacency matrix of a\n< directed or undirected graph, this is the number of self-edges\n< in the graph."]
    pub nself_edges: i64,
    #[doc = "< minimum edge weight: value, lower bound, or unknown"]
    pub emin: GrB_Scalar,
    pub emin_state: LAGraph_State,
    #[doc = "< maximum edge weight: value, upper bound, or unknown"]
    pub emax: GrB_Scalar,
    pub emax_state: LAGraph_State,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LAGraph_Graph_struct"][::std::mem::size_of::<LAGraph_Graph_struct>() - 88usize];
    ["Alignment of LAGraph_Graph_struct"][::std::mem::align_of::<LAGraph_Graph_struct>() - 8usize];
    ["Offset of field: LAGraph_Graph_struct::A"]
        [::std::mem::offset_of!(LAGraph_Graph_struct, A) - 0usize];
    ["Offset of field: LAGraph_Graph_struct::kind"]
        [::std::mem::offset_of!(LAGraph_Graph_struct, kind) - 8usize];
    ["Offset of field: LAGraph_Graph_struct::AT"]
        [::std::mem::offset_of!(LAGraph_Graph_struct, AT) - 16usize];
    ["Offset of field: LAGraph_Graph_struct::out_degree"]
        [::std::mem::offset_of!(LAGraph_Graph_struct, out_degree) - 24usize];
    ["Offset of field: LAGraph_Graph_struct::in_degree"]
        [::std::mem::offset_of!(LAGraph_Graph_struct, in_degree) - 32usize];
    ["Offset of field: LAGraph_Graph_struct::is_symmetric_structure"]
        [::std::mem::offset_of!(LAGraph_Graph_struct, is_symmetric_structure) - 40usize];
    ["Offset of field: LAGraph_Graph_struct::nself_edges"]
        [::std::mem::offset_of!(LAGraph_Graph_struct, nself_edges) - 48usize];
    ["Offset of field: LAGraph_Graph_struct::emin"]
        [::std::mem::offset_of!(LAGraph_Graph_struct, emin) - 56usize];
    ["Offset of field: LAGraph_Graph_struct::emin_state"]
        [::std::mem::offset_of!(LAGraph_Graph_struct, emin_state) - 64usize];
    ["Offset of field: LAGraph_Graph_struct::emax"]
        [::std::mem::offset_of!(LAGraph_Graph_struct, emax) - 72usize];
    ["Offset of field: LAGraph_Graph_struct::emax_state"]
        [::std::mem::offset_of!(LAGraph_Graph_struct, emax_state) - 80usize];
};
pub type LAGraph_Graph = *mut LAGraph_Graph_struct;
unsafe extern "C" {
    #[doc = " LAGraph_Init: initializes GraphBLAS and LAGraph.  This method must be\n called before calling any other GrB* or LAGraph* method.  It initializes\n GraphBLAS with GrB_init and then performs LAGraph-specific initializations.\n In particular, the LAGraph semirings listed below are created.  GrB_init can\n also safely be called before calling @sphinxref{LAGr_Init} or LAGraph_Init.\n\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_INVALID_VALUE if LAGraph_Init or LAGr_Init has already been\n      called by the user application.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Init(msg: *mut ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Version: determines the version of LAGraph.  The version number and\n date can also be obtained via compile-time constants from LAGraph.h.\n However, it is possible to compile a user application that includes one\n version of LAGraph.h and then links with another version of the LAGraph\n library later on, so the version number and date may differ from the\n compile-time constants.\n\n The LAGraph_Version method allows the library itself to be queried, after it\n is linked in with the user application.\n\n The version_number array is set to LAGRAPH_VERSION_MAJOR,\n LAGRAPH_VERSION_MINOR, and LAGRAPH_VERSION_UPDATE, in that order.  The\n LAGRAPH_DATE string is copied into the user-provided version_date string,\n and is null-terminated.\n\n @param[out] version_number   an array of size 3; with the major, minor,\n      and update versions of LAGraph, in that order.\n @param[out] version_date     an array of size >= LAGraph_MSG_LEN, returned\n      with the date of this version of LAGraph.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if version_number or version_date are NULL."]
    pub fn LAGraph_Version(
        version_number: *mut ::std::os::raw::c_int,
        version_date: *mut ::std::os::raw::c_char,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Finalize: finish LAGraph and GraphBLAS.  Must be called as the last\n LAGraph method.  It calls GrB_finalize and frees any LAGraph objects created\n by @sphinxref{LAGraph_Init} or @sphinxref{LAGr_Init}.  After calling this\n method, no LAGraph or GraphBLAS methods may be used.\n\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Finalize(msg: *mut ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_New: creates a new graph G.  The cached properties G->AT,\n G->out_degree, and G->in_degree are set to NULL, and scalar cached\n properties are set to LAGRAPH_UNKNOWN.\n\n @param[out] G        handle to the newly created graph, as &G.\n @param[in,out] A     adjacency matrix.  A is moved into G as G->A, and A\n                      itself is set to NULL to denote that is now a part of\n                      G.  That is, { G->A = A ; A = NULL ; } is performed.\n                      When G is deleted, G->A is freed.  If A is NULL, the\n                      graph is invalid until G->A is set.\n @param[in] kind      the kind of graph to create.  This may be\n                      LAGRAPH_UNKNOWN, which must then be revised later\n                      before the graph can be used.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if G is null.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_New(
        G: *mut LAGraph_Graph,
        A: *mut GrB_Matrix,
        kind: LAGraph_Kind,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Delete: frees a graph G.  The adjacency matrix G->A and the cached\n properties G->AT, G->out_degree, and G->in_degree are all freed.\n\n @param[in,out] G     handle to the graph to be free. *G is NULL on output.\n                      To keep G->A while deleting the graph G, use:\n                      { A = G->A ; G->A = NULL ; LAGraph_Delete (&G, msg) ; }\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Delete(
        G: *mut LAGraph_Graph,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_DeleteCached: frees all cached properies of a graph G.  The graph is\n still valid.  This method should be used if G->A changes, since such changes\n will normally invalidate G->AT, G->out_degree, and/or G->in_degree.\n\n @param[in,out] G     handle to the graph to modified.  The graph G remains\n                      valid on output, but with all cached properties freed.\n                      G may be NULL, in which case nothing is done.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_DeleteCached(
        G: LAGraph_Graph,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Cached_AT: constructs G->AT, the transpose of G->A.  This matrix is\n required by some of the algorithms.  Basic algorithms may construct G->AT if\n they require it.  The matrix G->AT is then available for subsequent use.  If\n G->A changes, G->AT should be freed and recomputed.  If G->AT already\n exists, it is left unchanged (even if it is not equal to the transpose of\n G->A).  As a result, if G->A changes, G->AT should be explictly freed.\n\n @param[in,out] G     graph for which G->AT is computed.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if G is NULL.\n @retval LAGRAPH_CACHE_NOT_NEEDED if G->kind is LAGraph_ADJACENCY_UNDIRECTED.\n @retval LAGRAPH_INVALID_GRAPH if G is invalid (G->A missing, or G->kind\n      not a recognized kind).\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Cached_AT(
        G: LAGraph_Graph,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Cached_IsSymmetricStructure: determines if the sparsity structure of\n G->A is symmetric (ignoring its values).  If G->kind denotes that the graph\n is undirected, this cached property is implicitly true (and not checked).\n Otherwise, this method determines if the structure of G->A for a directed\n graph G has a symmetric sparsity structure.  No work is performed if the\n cached property is already known.\n\n @param[in,out] G     graph for which G->is_symmetric_structure is computed.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if G is NULL.\n @retval LAGRAPH_INVALID_GRAPH if G is invalid (G->A missing, or G->kind\n      not a recognized kind).\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Cached_IsSymmetricStructure(
        G: LAGraph_Graph,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Cached_OutDegree: computes G->out_degree.  No work is performed if\n it already exists in G.\n\n @param[in,out] G     graph for which G->out_degree is computed.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if G is NULL.\n @retval LAGRAPH_INVALID_GRAPH if G is invalid (G->A missing, or G->kind\n      not a recognized kind).\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Cached_OutDegree(
        G: LAGraph_Graph,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Cached_InDegree computes G->in_degree.  No work is performed if it\n already exists in G.  If G is undirected, G->in_degree is never computed and\n remains NULL (the method returns LAGRAPH_CACHE_NOT_NEEDED).  No work is\n performed if it is already exists in G.\n\n Performance note: for SuiteSparse:GraphBLAS, if G->A is held by row (the\n default format), then computing G->in_degree is fastest if G->AT is known.\n If G->AT will be needed anyway, compute it first with LAGraph_Cached_AT, and\n then call LAGraph_Cached_Indegree.  This is optional; if G->AT is not known,\n then G->in_degree is computed from G->A instead.\n\n @param[in,out] G     graph for which G->in_degree is computed.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if G is NULL.\n @retval LAGRAPH_CACHE_NOT_NEEDED if G->kind is LAGraph_ADJACENCY_UNDIRECTED.\n @retval LAGRAPH_INVALID_GRAPH if G is invalid (G->A missing, or G->kind\n      not a recognized kind).\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Cached_InDegree(
        G: LAGraph_Graph,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Cached_NSelfEdges: computes G->nself_edges, the number of diagonal\n entries that appear in the G->A matrix.  For an undirected or directed graph\n with an adjacency matrix G->A, these are the number of self-edges in G.  No\n work is performed it is already computed.\n\n @param[in,out] G     graph for which G->nself_edges is computed.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if G is NULL.\n @retval LAGRAPH_INVALID_GRAPH if G is invalid (G->A missing, or G->kind\n      not a recognized kind).\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Cached_NSelfEdges(
        G: LAGraph_Graph,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Cached_EMin: computes the G->emin, the smallest entry in G->A.\n Not computed if G->emin already exists.\n\n @param[in,out] G     graph for which G->emin is computed.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NOT_IMPLEMENTED if G does not have a built-in real type:\n      GrB_(BOOL, INT8, INT16, INT32, INT64, UINT8, UINT16, UINT32, UINT64,\n      FP32, OR FP64).\n @retval GrB_NULL_POINTER if G is NULL.\n @retval LAGRAPH_INVALID_GRAPH if G is invalid (G->A missing, or G->kind\n      not a recognized kind).\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Cached_EMin(
        G: LAGraph_Graph,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Cached_EMax: computes the G->emax, the largest entry in G->A.\n Not computed if G->emax already exists.\n\n @param[in,out] G     graph for which G->emax is computed.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NOT_IMPLEMENTED if G does not have a built-in real type:\n      GrB_(BOOL, INT8, INT16, INT32, INT64, UINT8, UINT16, UINT32, UINT64,\n      FP32, OR FP64).\n @retval GrB_NULL_POINTER if G is NULL.\n @retval LAGRAPH_INVALID_GRAPH if G is invalid (G->A missing, or G->kind\n      not a recognized kind).\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Cached_EMax(
        G: LAGraph_Graph,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_DeleteSelfEdges: removes any diagonal entries from G->A.  Most\n cached properties are cleared or set to LAGRAPH_UNKNOWN.  G->nself_edges is\n set to zero, and G->is_symmetric_structure is left unchanged.\n\n @param[in,out] G     graph for which G->A is modified.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if G is NULL.\n @retval LAGRAPH_INVALID_GRAPH if G is invalid (G->A missing, or G->kind\n      not a recognized kind).\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_DeleteSelfEdges(
        G: LAGraph_Graph,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_CheckGraph: determines if a graph is valid.  Only basic checks are\n performed on the cached properties, taking O(1) time.\n\n @param[in] G         graph to check.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if G is NULL.\n @retval LAGRAPH_INVALID_GRAPH if G is invalid: G->A missing, G->kind\n      not a recognized kind, G->AT present but has the wrong dimensions or\n      its type does not match G->A, G->in_degree/out_degree present but\n      with the wrong dimension or type (in/out_degree must be GrB_INT64).\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_CheckGraph(
        G: LAGraph_Graph,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_GetNumThreads determines the current number of OpenMP threads that\n can be used.  See LAGraph_SetNumThreads for a description of nthreads_outer\n and nthreads_inner.\n\n @param[out] nthreads_outer   number of threads for outer region.\n @param[out] nthreads_inner   number of threads for inner region,\n                              or for the underlying GraphBLAS library.\n @param[in,out] msg           any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if nthreads_outer or nthreads_inner are NULL."]
    pub fn LAGraph_GetNumThreads(
        nthreads_outer: *mut ::std::os::raw::c_int,
        nthreads_inner: *mut ::std::os::raw::c_int,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_SetNumThreads sets the current number of OpenMP threads that can be\n used by LAGraph and GraphBLAS.  Two thread counts can be controlled:\n\n @param[in] nthreads_outer\n    number of threads to be used in outer regions of a\n    nested parallel construct assuming that nthreads_inner is used in the\n    inner region.  The total number of threads used for an entire nested\n    region in LAGraph is given by nthreads_outer*nthreads_inner.  This\n    product is also the # of threads that a flat parallel region in LAGraph\n    may use.\n @param[in] nthreads_inner\n    number of threads to be used in an inner region of a\n    nested parallel construct, or for the # of threads to be used in each\n    call to the underlying GraphBLAS library.\n @param[in,out] msg           any error messages.\n\n @retval GrB_SUCCESS if successful.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_SetNumThreads(
        nthreads_outer: ::std::os::raw::c_int,
        nthreads_inner: ::std::os::raw::c_int,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_WallClockTime returns the current wall clock time.  Normally, this\n is simply a wrapper for omp_get_wtime, if OpenMP is in use.  Otherwise, an\n OS-specific timing function is called.  Note that unlike all other LAGraph\n functions, this function does not return an error condition, nor does it\n have a msg string parameter.  Instead, it returns the current wall clock\n time (in seconds) since some fixed point in the past.\n\n @returns the current wall clock time."]
    pub fn LAGraph_WallClockTime() -> f64;
}
unsafe extern "C" {
    /// LAGraph_MMRead: reads a matrix in MatrixMarket format.
    pub fn LAGraph_MMRead(
        A: *mut GrB_Matrix,
        f: *mut FILE,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    /// LAGraph_MMWrite: writes a matrix in MatrixMarket format.
    pub fn LAGraph_MMWrite(
        A: GrB_Matrix,
        f: *mut FILE,
        fcomments: *mut FILE,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Matrix_Structure: returns the sparsity structure of a matrix A as a\n boolean (GrB_BOOL) matrix C.  If A(i,j) appears in the sparsity structure of\n A, then C(i,j) is set to true.  The sparsity structure of A and C are\n identical.\n\n @param[out] C    A boolean matrix with same structure of A, with C(i,j)\n                  true if A(i,j) appears in the sparsity structure of A.\n @param[in]  A    matrix to compute the structure for.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if A or C are NULL.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Matrix_Structure(
        C: *mut GrB_Matrix,
        A: GrB_Matrix,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Vector_Structure: returns the sparsity structure of a vector u as a\n boolean (GrB_BOOL) vector w.  If u(i) appears in the sparsity structure of\n u, then w(i) is set to true.  The sparsity structure of u and w are\n identical.\n\n @param[out] w    A boolean vector with same structure of u, with w(i)\n                  true if u(i,j) appears in the sparsity structure of u.\n @param[in]  u    vector to compute the structure for.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if w or u are NULL.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Vector_Structure(
        w: *mut GrB_Vector,
        u: GrB_Vector,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_NameOfType returns the name of a GraphBLAS type as a string.  The\n names for the 11 built-in types (GrB_BOOL, GrB_INT8, etc) correspond to the\n names of the corresponding C types (bool, int8_t, etc).\n\n @param[out] name     name of the type: user provided array of size at\n                      least LAGRAPH_MAX_NAME_LEN.\n @param[in]  type     GraphBLAS type to find the name of.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if name or type are NULL.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_NameOfType(
        name: *mut ::std::os::raw::c_char,
        type_: GrB_Type,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_TypeFromName: returns the GrB_Type corresponding to its name.  That\n is, given the string \"bool\", this method returns GrB_BOOL.\n\n @param[out] type     GraphBLAS type corresponding to the given name string.\n @param[in]  name     name of the type: a null-terminated string.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if name or type are NULL.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_TypeFromName(
        type_: *mut GrB_Type,
        name: *mut ::std::os::raw::c_char,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_SizeOfType: returns sizeof(...) of a GraphBLAS GrB_Type.  For\n example, if given the GrB_Type of GrB_FP64, the value sizeof(double) is\n returned.\n\n @param[out] size     size of the type\n @param[in]  type     GraphBLAS type to find the size of.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if size or type are NULL.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_SizeOfType(
        size: *mut usize,
        type_: GrB_Type,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Matrix_TypeName: returns the name of the GrB_Type of a GrB_Matrix.\n\n @param[out] name     name of the type of the matrix: user provided array of\n                      size at least LAGRAPH_MAX_NAME_LEN.\n @param[in]  A        GraphBLAS matrix to find the type name of.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if name or A are NULL.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Matrix_TypeName(
        name: *mut ::std::os::raw::c_char,
        A: GrB_Matrix,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Vector_TypeName: returns the name of the GrB_Type of a GrB_Vector.\n\n @param[out] name     name of the type of the vector: user provided array of\n                      size at least LAGRAPH_MAX_NAME_LEN.\n @param[in]  v        GraphBLAS vector to find the type name of.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if name or v are NULL.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Vector_TypeName(
        name: *mut ::std::os::raw::c_char,
        v: GrB_Vector,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Scalar_TypeName: returns the name of the GrB_Type of a GrB_Scalar.\n\n @param[out] name     name of the type of the scalar: user provided array of\n                      size at least LAGRAPH_MAX_NAME_LEN.\n @param[in]  s        GraphBLAS scalar to find the type name of.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if name or s are NULL.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Scalar_TypeName(
        name: *mut ::std::os::raw::c_char,
        s: GrB_Scalar,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
#[repr(u32)]
#[doc = " LAGraph_PrintLevel:  an enum to control how much to print in\n LAGraph_*_Print methods."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum LAGraph_PrintLevel {
    #[doc = "< nothing is printed."]
    LAGraph_SILENT = 0,
    #[doc = "< print a terse summary."]
    LAGraph_SUMMARY = 1,
    #[doc = "< short description, about 30 entries."]
    LAGraph_SHORT = 2,
    #[doc = "< print the entire contents of the object."]
    LAGraph_COMPLETE = 3,
    #[doc = "< short, but with \"%.15g\" for doubles."]
    LAGraph_SHORT_VERBOSE = 4,
    #[doc = "< complete, but \"%.15g\" for doubles."]
    LAGraph_COMPLETE_VERBOSE = 5,
}
unsafe extern "C" {
    #[doc = " LAGraph_Graph_Print: prints the contents of a graph to a file in a human-\n readable form.  This method is not meant for saving a graph to a file; see\n @sphinxref{LAGraph_MMWrite} for that method.\n\n @param[in] G         graph to display.\n @param[in] pr        print level.\n @param[in,out] f     handle to an open file to write to.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if G or f are NULL.\n @retval LAGRAPH_INVALID_GRAPH if G is invalid\n              (@sphinxref{LAGraph_CheckGraph} failed).\n @retval GrB_NOT_IMPLEMENTED if G->A has a user-defined type.\n @retval LAGRAPH_IO_ERROR if the file could not be written to.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Graph_Print(
        G: LAGraph_Graph,
        pr: LAGraph_PrintLevel,
        f: *mut FILE,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Matrix_Print displays a matrix in a human-readable form.  This\n method is not meant for saving a GrB_Matrix to a file; see\n @sphinxref{LAGraph_MMWrite} for that method.\n\n @param[in] A         matrix to display.\n @param[in] pr        print level.\n @param[in,out] f     handle to an open file to write to.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if A or f are NULL.\n @retval GrB_NOT_IMPLEMENTED if A has a user-defined type.\n @retval LAGRAPH_IO_ERROR if the file could not be written to.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Matrix_Print(
        A: GrB_Matrix,
        pr: LAGraph_PrintLevel,
        f: *mut FILE,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Vector_Print displays a vector in a human-readable form.  This\n method is not meant for saving a GrB_Vector to a file.  To perform that\n operation, copy the GrB_Vector into an n-by-1 GrB_Matrix and use\n @sphinxref{LAGraph_MMWrite}.\n\n @param[in] v         vector to display.\n @param[in] pr        print level.\n @param[in,out] f     handle to an open file to write to.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if v or f are NULL.\n @retval GrB_NOT_IMPLEMENTED if v has a user-defined type.\n @retval LAGRAPH_IO_ERROR if the file could not be written to.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Vector_Print(
        v: GrB_Vector,
        pr: LAGraph_PrintLevel,
        f: *mut FILE,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Matrix_IsEqual compares two matrices for exact equality.  If the\n two matrices have different data types, the result is always false (no\n typecasting is performed).  Only the 11 built-in GrB* types are supported.\n If both A and B are NULL, the return value is true.  If A and/or B are\n floating-point types and contain NaN's, result is false.\n\n @param[out] result   true if A and B are exactly equal, false otherwise.\n @param[in] A         matrix to compare.\n @param[in] B         matrix to compare.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if result is NULL.\n @retval GrB_NOT_IMPLEMENTED if A or B has a user-defined type.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Matrix_IsEqual(
        result: *mut bool,
        A: GrB_Matrix,
        B: GrB_Matrix,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Matrix_IsEqualOp compares two matrices using the given binary\n operator.  The op may be built-in or user-defined.  The two matrices may\n have different types and still be determined to be equal.  To be equal, two\n matrices must have the same sparsity structure, and op(aij,bij) must return\n true for all pairs of entries aij and bij that appear in the structure of\n both A and B.  The matrices A and/or B can have any type, as long as they\n are valid inputs to the op.  If both A and B are NULL, the return value is\n true.\n\n @param[out] result   true if A and B are equal (per the op), false otherwise.\n @param[in] A         matrix to compare.\n @param[in] B         matrix to compare.\n @param[in] op        operator for the comparison.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if result or op are NULL.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Matrix_IsEqualOp(
        result: *mut bool,
        A: GrB_Matrix,
        B: GrB_Matrix,
        op: GrB_BinaryOp,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Vector_IsEqual compares two vectors for exact equality.  If the\n two vectors have different data types, the result is always false (no\n typecasting is performed).  Only the 11 built-in GrB* types are supported.\n If both u and v are NULL, the return value is true.  If u and/or v are\n floating-point types and contain NaN's, result is false.\n\n @param[out] result   true if u and v are exactly equal, false otherwise.\n @param[in] u         vector to compare.\n @param[in] v         vector to compare.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if result is NULL.\n @retval GrB_NOT_IMPLEMENTED if u or v has a user-defined type.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Vector_IsEqual(
        result: *mut bool,
        u: GrB_Vector,
        v: GrB_Vector,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Vector_IsEqualOp compares two vectors using the given binary\n operator.  The op may be built-in or user-defined.  The two vectors may\n have different types and still be determined to be equal.  To be equal, two\n vectors must have the same sparsity structure, and op(ui,vi) must return\n true for all pairs of entries ui and vi that appear in the structure of\n both u and v.  The vectors u and/or v can have any type, as long as they\n are valid inputs to the op.  If both u and v are NULL, the return value is\n true.\n\n @param[out] result   true if u and v are equal (per the op), false otherwise.\n @param[in] u         vector to compare.\n @param[in] v         vector to compare.\n @param[in] op        operator for the comparison.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if result or op are NULL.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Vector_IsEqualOp(
        result: *mut bool,
        u: GrB_Vector,
        v: GrB_Vector,
        op: GrB_BinaryOp,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Random_Seed creates a pseudo-random vector containing an array of\n different pseudo-random streams, one per entry.  On input, the values of the\n State vector are ignored but its structure is used.  On output, all entries\n that were in the original structure of the State vector are assigned random\n values, depending on the scalar seed value.  Each entry is considered its\n own pseudo-random number stream, with the overall seed value being revised\n for each entry in the vector, depending on their index in the vector.\n\n More precisely, if the entry State [i] is present in the State vector, it is\n initialized with the pseudo random number State [i] = splitmix64 (i + seed);\n see https://dl.acm.org/doi/10.1145/2714064.2660195 for details, or\n https://en.wikipedia.org/wiki/Xorshift .\n\n To call this method again with a new scalar seed, for subsequent iterations\n for the same State vector, it is advisable to advance the seed by at least\n n, where n is the dimension of the State vector.  Otherwise, the random\n number streams will be correlated.  For example, if seed++ is performed when\n this method is called again, then the new State [1] stream will be identical\n to the prior State [0] stream.\n\n The State vector should normally be of type GrB_UINT64, but this is not\n enforced.  Typecasting will be performed if it has a different type, which\n will affect the pseudo-random numbers generated and results are thus not\n guaranteed in this case.\n\n @param[in,out] State  vector to initialize with pseudo-random numbers.\n @param[in] seed       scalar seed value.\n @param[in,out] msg    any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if State is NULL.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Random_Seed(
        State: GrB_Vector,
        seed: u64,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_Random_Next takes as input a vector previously initialized by\n LAGraph_Random_Seed, and modifies all its entries so that they take on their\n next value in their respective pseudo-random number streams.\n\n Each stream in State [i] should be initialized by LAGraph_Random_Seed, and\n then advanced to the next pseudo-random value with LAGraph_Random_Next,\n which computes State [i] = xorshift64 (State [i]).  See\n https://doi.org/10.18637/jss.v008.i14 and\n https://en.wikipedia.org/wiki/Xorshift .\n\n @param[in,out] State  vector with random numbers to be advanced.\n @param[in,out] msg    any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if State is NULL.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_Random_Next(
        State: GrB_Vector,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGraph_TriangleCount: count the triangles in a graph.  This is a Basic\n algorithm (G->nself_edges, G->out_degree, G->is_symmetric_structure are\n computed, if not present).\n\n @param[out]    ntriangles    the number of triangles in G.\n @param[in,out] G             the graph, which must by undirected, or\n                              directed but with a symmetric structure.\n                              No self loops can be present.\n @param[in,out] msg           any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if G or ntriangles are NULL.\n @retval LAGRAPH_INVALID_GRAPH if G is invalid\n              (@sphinxref{LAGraph_CheckGraph} failed).\n @retval LAGRAPH_NO_SELF_EDGES_ALLOWED if G has any self-edges.\n @retval LAGRAPH_SYMMETRIC_STRUCTURE_REQUIRED if G is directed with an\n      unsymmetric G->A matrix.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGraph_TriangleCount(
        ntriangles: *mut u64,
        G: LAGraph_Graph,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGr_Init: initializes GraphBLAS and LAGraph.  LAGr_Init is identical to\n @sphinxref{LAGraph_Init}, except that it allows the user application to\n specify the GraphBLAS mode.  It also provides four memory management\n functions, replacing the standard `malloc`, `calloc`, `realloc`, and `free`.\n The functions `user_malloc_function`, `user_calloc_function`,\n `user_realloc_function`, and `user_free_function` have the same signature as\n the ANSI C malloc, calloc, realloc, and free functions, respectively.  Only\n user_malloc_function and user_free_function are required.\n user_calloc_function may be NULL, in which case `LAGraph_Calloc` uses\n `LAGraph_Malloc` and `memset`.  Likewise, user_realloc_function may be NULL,\n in which case `LAGraph_Realloc` uses `LAGraph_Malloc`, `memcpy`, and\n `LAGraph_Free`.\n\n @param[in] mode                      the mode for GrB_Init\n @param[in] user_malloc_function      pointer to a malloc function\n @param[in] user_calloc_function      pointer to a calloc function, or NULL\n @param[in] user_realloc_function     pointer to a realalloc function, or NULL\n @param[in] user_free_function        pointer to a free function\n @param[in,out] msg                   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_INVALID_VALUE if LAGraph_Init or LAGr_Init has already been\n      called by the user application.\n @retval GrB_NULL_POINTER if user_malloc_function or user_free_function\n      are NULL.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGr_Init(
        mode: GrB_Mode,
        user_malloc_function: ::std::option::Option<
            unsafe extern "C" fn(arg1: usize) -> *mut ::std::os::raw::c_void,
        >,
        user_calloc_function: ::std::option::Option<
            unsafe extern "C" fn(arg1: usize, arg2: usize) -> *mut ::std::os::raw::c_void,
        >,
        user_realloc_function: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut ::std::os::raw::c_void,
                arg2: usize,
            ) -> *mut ::std::os::raw::c_void,
        >,
        user_free_function: ::std::option::Option<
            unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void),
        >,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGr_SortByDegree sorts the nodes of a graph by their out or in degrees.\n The graph G->A itself is not changed.  Refer to LAGr_TriangleCount for an\n example of how to permute G->A after calling this function.  The output &P\n must be freed by LAGraph_Free.  This method requires G->out_degree or\n G->in_degree to already be computed.\n\n @param[out] P        permutation of the integers 0..n-1.\n @param[in] G         graph of n nodes.\n @param[in] byout     if true, sort by out-degree, else sort by in-degree.\n @param[in] ascending if true, sort in ascending order, else descending.\n @param[in,out] msg   any error messages.\n\n @retval GrB_NULL_POINTER if P or G are NULL.\n @retval LAGRAPH_NOT_CACHED if G->in_degree or G->out_degree is not computed\n      (whichever one is required).\n @retval LAGRAPH_INVALID_GRAPH if G is invalid\n              (@sphinxref{LAGraph_CheckGraph} failed).\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGr_SortByDegree(
        P: *mut *mut i64,
        G: LAGraph_Graph,
        byout: bool,
        ascending: bool,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGr_SampleDegree computes an estimate of the median and mean of the out or\n in degree, by randomly sampling the G->out_degree or G->in_degree vector.\n This method requires G->out_degree or G->in_degree to already be computed.\n\n @param[out] sample_mean      sampled mean of the degree.\n @param[out] sample_median    sampled median of the degree.\n @param[in] G         graph to sample.\n @param[in] byout     if true, sample out-degree, else sample in-degree.\n @param[in] nsamples  number of samples to take.\n @param[in] seed      random number seed.\n @param[in,out] msg   any error messages.\n\n @retval GrB_NULL_POINTER if sample_mean, sample_median, or G are NULL.\n @retval LAGRAPH_NOT_CACHED if G->in_degree or G->out_degree is not computed\n      (whichever one is required).\n @retval LAGRAPH_INVALID_GRAPH if G is invalid\n              (@sphinxref{LAGraph_CheckGraph} failed).\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGr_SampleDegree(
        sample_mean: *mut f64,
        sample_median: *mut f64,
        G: LAGraph_Graph,
        byout: bool,
        nsamples: i64,
        seed: u64,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGr_BreadthFirstSearch: breadth-first search of a graph, computing the\n breadth-first-search tree and/or the level of the nodes encountered.  This\n is an Advanced algorithm.  G->AT and G->out_degree are required to use the\n fastest push/pull method when using SuiteSparse:GraphBLAS.  If these cached\n properties are not present, or if a vanilla GraphBLAS library is being used,\n then a push-only method is used (which can be slower).  G is not modified;\n that is, G->AT and G->out_degree are not computed if not already cached.\n\n @param[out]    level      If non-NULL on input, on successful return, it\n                           contains the levels of each node reached. The\n                           src node is assigned level 0. If a node i is\n                           not reached, level(i) is not present.  The level\n                           vector is not computed if NULL.\n @param[out]    parent     If non-NULL on input, on successful return, it\n                           contains parent node IDs for each node\n                           reached, where parent(i) is the node ID of the\n                           parent of node i.  The src node will have itself\n                           as its parent. If a node i is not reached,\n                           parent(i) is not present.  The parent vector is\n                           not computed if NULL.\n @param[in]     G          The graph, directed or undirected.\n @param[in]     src        The index of the src node (0-based)\n @param[in,out] msg        any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_INVALID_INDEX if src is invalid.\n @retval GrB_NULL_POINTER if both level and parent are NULL, or if\n      G is NULL.\n @retval LAGRAPH_INVALID_GRAPH Graph is invalid\n              (@sphinxref{LAGraph_CheckGraph} failed).\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGr_BreadthFirstSearch(
        level: *mut GrB_Vector,
        parent: *mut GrB_Vector,
        G: LAGraph_Graph,
        src: GrB_Index,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGr_ConnectedComponents: connected components of an undirected graph.\n This is an Advanced algorithm (G->is_symmetric_structure must be known).\n\n @param[out] component    component(i)=s if node i is in the component whose\n                          representative node is s.  If node i has no edges,\n                          it is placed in its own component, and thus the\n                          component vector is always dense.\n @param[in] G             input graph to find the components for.\n                          The graph must be undirected, or\n                          G->is_symmetric_structure must be true.\n @param[in,out] msg       any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if G or component are NULL.\n @retval LAGRAPH_INVALID_GRAPH Graph is invalid\n              (@sphinxref{LAGraph_CheckGraph} failed).\n @retval LAGRAPH_SYMMETRIC_STRUCTURE_REQUIRED if G is directed with an\n      unsymmetric G->A matrix.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGr_ConnectedComponents(
        component: *mut GrB_Vector,
        G: LAGraph_Graph,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGr_SingleSourceShortestPath: single-source shortest paths.  This is an\n Advanced algorithm (G->emin is required for best performance).  The graph G\n must have an adjacency matrix of type GrB_INT32, GrB_INT64, GrB_UINT32,\n GrB_UINT64, GrB_FP32, or GrB_FP64.  If G->A has any other type,\n GrB_NOT_IMPLEMENTED is returned.\n\n @param[out] path_length  path_length (i) is the length of the shortest\n     path from the source node to node i.  The path_length vector is dense.\n     If node (i) is not reachable from the src node, then path_length (i) is\n     set to INFINITY for GrB_FP32 and FP32, or the maximum integer for\n     GrB_INT32, INT64, UINT32, or UINT64.\n @param[in] G         input graph.\n @param[in] src       source node.\n @param[in] Delta     for delta stepping.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if G or path_length are NULL.\n @retval GrB_INVALID_INDEX if src is invalid.\n @retval GrB_EMPTY_OBJECT if Delta does not contain a value.\n @retval GrB_NOT_IMPLEMENTED if the type is not supported.\n @retval LAGRAPH_INVALID_GRAPH Graph is invalid\n              (@sphinxref{LAGraph_CheckGraph} failed).\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGr_SingleSourceShortestPath(
        path_length: *mut GrB_Vector,
        G: LAGraph_Graph,
        src: GrB_Index,
        Delta: GrB_Scalar,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGr_Betweenness: betweeness centrality metric.  This methods computes an\n approximation of the betweeness-centrality metric of all nodes in the graph.\n Only a few given source nodes are used for the approximation.  This is an\n Advanced algorithm (G->AT is required).\n\n @param[out] centrality   centrality(i) is the metric for node i.\n @param[in] G         input graph.\n @param[in] sources   source vertices to compute shortest paths, size ns\n @param[in] ns        number of source vertices.\n @param[in,out] msg   any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if G, centrality, and/our sources are NULL.\n @retval GrB_INVALID_INDEX if any source node is invalid.\n @retval LAGRAPH_INVALID_GRAPH Graph is invalid\n              (@sphinxref{LAGraph_CheckGraph} failed).\n @retval LAGRAPH_NOT_CACHED if G->AT is required but not present.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGr_Betweenness(
        centrality: *mut GrB_Vector,
        G: LAGraph_Graph,
        sources: *const GrB_Index,
        ns: i32,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " LAGr_PageRank: computes the standard PageRank of a directed graph G.  Sinks\n (nodes with no out-going edges) are properly handled.  This method should be\n used for production, not for the GAP benchmark.  This is an Advanced\n algorithm (G->AT and G->out_degree are required).\n\n @param[out] centrality   centrality(i) is the PageRank of node i.\n @param[out] iters        number of iterations taken.\n @param[in] G             input graph.\n @param[in] damping       damping factor (typically 0.85).\n @param[in] tol           stopping tolerance (typically 1e-4).\n @param[in] itermax       maximum number of iterations (typically 100).\n @param[in,out] msg       any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if G, centrality, and/our iters are NULL.\n @retval LAGRAPH_NOT_CACHED if G->AT is required but not present,\n      or if G->out_degree is not present.\n @retval LAGRAPH_INVALID_GRAPH Graph is invalid\n              (@sphinxref{LAGraph_CheckGraph} failed).\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGr_PageRank(
        centrality: *mut GrB_Vector,
        iters: *mut ::std::os::raw::c_int,
        G: LAGraph_Graph,
        damping: f32,
        tol: f32,
        itermax: ::std::os::raw::c_int,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn LAGr_PageRankGAP(
        centrality: *mut GrB_Vector,
        iters: *mut ::std::os::raw::c_int,
        G: LAGraph_Graph,
        damping: f32,
        tol: f32,
        itermax: ::std::os::raw::c_int,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
#[repr(u32)]
#[doc = " LAGr_TriangleCount_Method: an enum to select the method used to count the\n number of triangles."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum LAGr_TriangleCount_Method {
    #[doc = "< auto selection of method"]
    LAGr_TriangleCount_AutoMethod = 0,
    #[doc = "< sum (sum ((A^2) .* A)) / 6"]
    LAGr_TriangleCount_Burkhardt = 1,
    #[doc = "< sum (sum ((L * U) .* A)) / 2"]
    LAGr_TriangleCount_Cohen = 2,
    #[doc = "< sum (sum ((L * L) .* L))"]
    LAGr_TriangleCount_Sandia_LL = 3,
    #[doc = "< sum (sum ((U * U) .* U))"]
    LAGr_TriangleCount_Sandia_UU = 4,
    #[doc = "< sum (sum ((L * U') .* L))"]
    LAGr_TriangleCount_Sandia_LUT = 5,
    #[doc = "< sum (sum ((U * L') .* U))"]
    LAGr_TriangleCount_Sandia_ULT = 6,
}
#[repr(i32)]
#[doc = " LAGr_TriangleCount_Presort: an enum to control if/how the matrix is sorted\n prior to counting triangles."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum LAGr_TriangleCount_Presort {
    #[doc = "< no sort"]
    LAGr_TriangleCount_NoSort = 2,
    #[doc = "< sort by degree, ascending."]
    LAGr_TriangleCount_Ascending = 1,
    #[doc = "< sort by degree, descending."]
    LAGr_TriangleCount_Descending = -1,
    #[doc = "< auto selection of presort:\n< No presort is done for the Burkhardt or Cohen methods, and\n< no sort is done for the Sandia_* methods if the sampled mean\n< out-degree is <= 4 * the sample median out-degree.\n< Otherwise: sort in ascending order for Sandia_LL and Sandia_LUT,\n< descending ordering for Sandia_UU and Sandia_ULT.  On output,\n< presort is modified to reflect the sorting method used (NoSort,\n< Ascending, or Descending)."]
    LAGr_TriangleCount_AutoSort = 0,
}
unsafe extern "C" {
    #[doc = " LAGr_TriangleCount: count the triangles in a graph (advanced API).\n\n @param[out] ntriangles   the number of triangles in G.\n @param[in]  G            The graph, which must be undirected or have\n                          G->is_symmetric_structure true, with no self loops.\n                          G->nself_edges, G->out_degree, and\n                          G->is_symmetric_structure are required.\n @param[in,out] method    specifies which algorithm to use, and returns\n                          the method chosen.  If NULL, the AutoMethod is\n                          used, and the method is not reported.  Also see the\n                          LAGr_TriangleCount_Method enum description.\n @param[in,out] presort   controls the presort of the graph, and returns the\n                          presort chosen.  If NULL, the AutoSort is used, and\n                          the presort method is not reported.  Also see the\n                          description of the LAGr_TriangleCount_Presort enum.\n @param[in,out] msg       any error messages.\n\n @retval GrB_SUCCESS if successful.\n @retval GrB_NULL_POINTER if G or ntriangles are NULL.\n @retval LAGRAPH_INVALID_GRAPH Graph is invalid\n              (@sphinxref{LAGraph_CheckGraph} failed).\n @retval LAGRAPH_NO_SELF_EDGES_ALLOWED if G has any self-edges, or if\n      G->nself_edges is not computed.\n @retval LAGRAPH_SYMMETRIC_STRUCTURE_REQUIRED if G is directed with an\n      unsymmetric G->A matrix.\n @retval LAGRAPH_NOT_CACHED if G->out_degree is not present in G.\n @retval GrB_INVALID_VALUE method or presort are invalid.\n @returns any GraphBLAS errors that may have been encountered."]
    pub fn LAGr_TriangleCount(
        ntriangles: *mut u64,
        G: LAGraph_Graph,
        method: *mut LAGr_TriangleCount_Method,
        presort: *mut LAGr_TriangleCount_Presort,
        msg: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
