//! `deps/native-deps.lock` -- the checked-in mirror of the submodule gitlinks.
//!
//! It exists because a Docker build context has no `.git` directory, so the dep
//! stages cannot read the gitlinks; and because it gives CI a plain file to hash
//! and to gate on (`native-deps lock --check`).

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use crate::error::Result;
use crate::util::capture;
use crate::{bail, err};

pub const LOCK_RELPATH: &str = "deps/native-deps.lock";

const HEADER: &str = "\
# native-deps lock file
#
# Generated by `native-deps lock`; verified in CI by `native-deps lock --check`.
# Regenerate whenever a gitlink under deps/ moves.
#
# This mirrors the gitlinks recorded in the superproject's index. It exists as a
# plain file because a Docker build context has no .git directory, so the dep
# stages cannot read the gitlinks directly -- and because it gives CI a stable
# path to hash. `rev` is what feeds the per-dep cache key; `pin` is the
# human-readable tag or branch the rev came from.
";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Entry {
    /// Short dep name (`graphblas`, `lagraph`, `redisearch`).
    pub name: String,
    /// Repo-relative submodule path (`deps/GraphBLAS`).
    pub path: String,
    pub url: String,
    /// Full 40-char commit the gitlink points at. This is the source component
    /// of the cache key.
    pub rev: String,
    /// Human-readable tag or branch `rev` came from. Informational only, and
    /// deliberately *not* part of the cache key.
    pub pin: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct LockFile {
    pub entries: Vec<Entry>,
}

impl LockFile {
    /// Read `<root>/deps/native-deps.lock`.
    pub fn load(root: &Path) -> Result<Self> {
        let path = root.join(LOCK_RELPATH);
        let text = fs::read_to_string(&path).map_err(|e| {
            err!(
                "cannot read {}: {e}\n\
                 hint: run `native-deps lock` from a FalkorDB checkout",
                path.display()
            )
        })?;
        Self::parse(&text, &path)
    }

    pub fn parse(
        text: &str,
        origin: &Path,
    ) -> Result<Self> {
        let mut entries: Vec<Entry> = Vec::new();
        let mut current: Option<(String, BTreeMap<String, String>)> = None;

        let flush =
            |cur: Option<(String, BTreeMap<String, String>)>, out: &mut Vec<Entry>| -> Result<()> {
                let Some((name, fields)) = cur else {
                    return Ok(());
                };
                let get = |k: &str| -> Result<String> {
                    fields
                        .get(k)
                        .cloned()
                        .ok_or_else(|| err!("{}: [{name}] is missing `{k}`", origin.display()))
                };
                out.push(Entry {
                    path: get("path")?,
                    url: get("url")?,
                    rev: get("rev")?,
                    pin: fields.get("pin").cloned().unwrap_or_default(),
                    name,
                });
                Ok(())
            };

        for (lineno, raw) in text.lines().enumerate() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some(name) = line.strip_prefix('[').and_then(|l| l.strip_suffix(']')) {
                flush(current.take(), &mut entries)?;
                current = Some((name.trim().to_owned(), BTreeMap::new()));
                continue;
            }
            let Some((k, v)) = line.split_once('=') else {
                bail!(
                    "{}:{}: expected `key = value`, got `{line}`",
                    origin.display(),
                    lineno + 1
                );
            };
            let Some((_, fields)) = current.as_mut() else {
                bail!(
                    "{}:{}: `{line}` appears before any [dep] section",
                    origin.display(),
                    lineno + 1
                );
            };
            fields.insert(k.trim().to_owned(), v.trim().to_owned());
        }
        flush(current.take(), &mut entries)?;

        if entries.is_empty() {
            bail!("{}: no dep sections found", origin.display());
        }
        entries.sort_by(|a, b| a.name.cmp(&b.name));
        Ok(Self { entries })
    }

    pub fn get(
        &self,
        name: &str,
    ) -> Result<&Entry> {
        self.entries
            .iter()
            .find(|e| e.name == name)
            .ok_or_else(|| err!("no `[{name}]` section in {LOCK_RELPATH}"))
    }

    /// Serialize in the canonical form `native-deps lock` writes.
    #[must_use]
    pub fn render(&self) -> String {
        let mut out = String::from(HEADER);
        for e in &self.entries {
            out.push_str(&format!(
                "\n[{}]\npath = {}\nurl = {}\nrev = {}\npin = {}\n",
                e.name, e.path, e.url, e.rev, e.pin
            ));
        }
        out
    }

    /// Absolute path to a dep's source tree.
    pub fn source_dir(
        &self,
        root: &Path,
        name: &str,
    ) -> Result<PathBuf> {
        Ok(root.join(&self.get(name)?.path))
    }
}

/// Where `native-deps lock` operates: the checkout holding the lock file, or,
/// since this is the one command that can run before the lock file exists, the
/// git toplevel.
pub fn root_for(cwd: &Path) -> Result<PathBuf> {
    // An explicit root is honoured even before it has a lock file -- that is
    // exactly when `lock` is first run.
    if let Some(explicit) = crate::util::env_opt("FALKORDB_REPO_ROOT") {
        return Ok(PathBuf::from(explicit));
    }
    crate::util::find_repo_root(cwd).or_else(|e| {
        capture("git", &["rev-parse", "--show-toplevel"], Some(cwd))
            .map(|t| PathBuf::from(t.trim()))
            .map_err(|_| e)
    })
}

/// Regenerate the lock file from the gitlinks, returning a summary.
pub fn write(root: &Path) -> Result<String> {
    let generated = from_git(root)?.render();
    let path = root.join(LOCK_RELPATH);
    fs::write(&path, &generated).map_err(|e| err!("cannot write {}: {e}", path.display()))?;
    let lock = LockFile::parse(&generated, &path)?;
    let mut out = format!("wrote {}", path.display());
    for e in &lock.entries {
        out.push_str(&format!(
            "\n  {} {} ({})",
            e.name,
            &e.rev[..e.rev.len().min(12)],
            e.pin
        ));
    }
    Ok(out)
}

/// Fail if the lock file no longer matches the gitlinks.
///
/// Compares path/url/rev, not the rendered text. `pin` is a human-readable
/// tag that `from_git` recovers with `git describe` *inside* the submodule, and
/// is not part of the cache key; a checkout without submodules -- which is all
/// the lint job has -- cannot run that describe and falls back to the short
/// rev, so comparing text would fail a correct lock file.
pub fn check(root: &Path) -> Result<()> {
    let path = root.join(LOCK_RELPATH);
    let generated = from_git(root)?.render();
    let current =
        fs::read_to_string(&path).map_err(|e| err!("cannot read {}: {e}", path.display()))?;
    let binding = |text: &str| -> Result<Vec<(String, String, String, String)>> {
        let mut v: Vec<_> = LockFile::parse(text, &path)?
            .entries
            .into_iter()
            .map(|e| (e.name, e.path, e.url, e.rev))
            .collect();
        v.sort();
        Ok(v)
    };
    if binding(&generated)? == binding(&current)? {
        return Ok(());
    }
    bail!(
        "{LOCK_RELPATH} is stale.\n\
         A gitlink under deps/ moved without the lock file being regenerated.\n\
         Run `native-deps lock` and commit the result.\n\n\
         expected:\n{}\n\ngot:\n{}",
        summarize(&generated),
        summarize(&current)
    )
}

/// Condense a lock file to its `name rev` pairs for a diffable error message.
fn summarize(text: &str) -> String {
    let mut out = Vec::new();
    let mut section = String::new();
    for line in text.lines() {
        let line = line.trim();
        if let Some(name) = line.strip_prefix('[').and_then(|l| l.strip_suffix(']')) {
            section = name.to_owned();
        } else if let Some((key, rev)) = line.split_once('=')
            && key.trim() == "rev"
        {
            out.push(format!("  {section} {}", rev.trim()));
        }
    }
    out.join("\n")
}

/// Rebuild the lock file's contents from the superproject's git state
/// (`.gitmodules` + the staged gitlinks).
pub fn from_git(root: &Path) -> Result<LockFile> {
    let config = capture(
        "git",
        &["config", "-f", ".gitmodules", "--list"],
        Some(root),
    )
    .map_err(|e| err!("cannot read .gitmodules: {e}"))?;

    // submodule.<name>.<field>=<value>
    let mut mods: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();
    for line in config.lines() {
        let Some((k, v)) = line.split_once('=') else {
            continue;
        };
        let Some(rest) = k.strip_prefix("submodule.") else {
            continue;
        };
        let Some((name, field)) = rest.rsplit_once('.') else {
            continue;
        };
        mods.entry(name.to_owned())
            .or_default()
            .insert(field.to_owned(), v.to_owned());
    }

    let mut entries = Vec::new();
    for fields in mods.values() {
        let Some(path) = fields.get("path") else {
            continue;
        };
        // Only deps/ submodules are native build inputs.
        if !path.starts_with("deps/") {
            continue;
        }
        let url = fields
            .get("url")
            .cloned()
            .ok_or_else(|| err!("submodule {path} has no url in .gitmodules"))?;

        // `<mode> <object> <stage>\t<path>`. Only a gitlink (mode 160000) at
        // stage 0 is a pin: a plain file has a blob id there, and a conflicted
        // index lists one line per side.
        let listing = capture("git", &["ls-files", "-s", "--", path], Some(root))?;
        let index_entry: Vec<&str> = listing.split_whitespace().collect();
        let rev = match index_entry.as_slice() {
            ["160000", rev, "0", _] => (*rev).to_owned(),
            [] => bail!("no gitlink recorded for {path}; run `git add {path}` first"),
            _ => bail!(
                "{path} is not a resolved submodule gitlink in the index: `{}`",
                listing.trim()
            ),
        };

        let pin = fields.get("branch").cloned().unwrap_or_else(|| {
            capture(
                "git",
                &["describe", "--tags", "--exact-match", "HEAD"],
                Some(&root.join(path)),
            )
            .map_or_else(
                |_| rev[..rev.len().min(12)].to_owned(),
                |t| t.trim().to_owned(),
            )
        });

        entries.push(Entry {
            name: dep_name_for_path(path),
            path: path.clone(),
            url,
            rev,
            pin,
        });
    }

    if entries.is_empty() {
        bail!("no deps/ submodules found in .gitmodules");
    }
    entries.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(LockFile { entries })
}

/// `deps/GraphBLAS` -> `graphblas`. The lock file keys on the short name so the
/// on-disk submodule path can change without touching every consumer.
fn dep_name_for_path(path: &str) -> String {
    path.rsplit('/').next().unwrap_or(path).to_ascii_lowercase()
}

#[cfg(test)]
mod tests {
    use super::{Entry, LockFile};
    use std::path::Path;

    fn sample() -> LockFile {
        LockFile {
            entries: vec![
                Entry {
                    name: "graphblas".into(),
                    path: "deps/GraphBLAS".into(),
                    url: "https://example.invalid/GraphBLAS.git".into(),
                    rev: "1fd54756ca57cae44e8cf91137ba5107824e8e7b".into(),
                    pin: "v10.3.1".into(),
                },
                Entry {
                    name: "lagraph".into(),
                    path: "deps/LAGraph".into(),
                    url: "https://example.invalid/LAGraph.git".into(),
                    rev: "94573af8c519d56852ea534c00bce08d859f7786".into(),
                    pin: "v1.3.x".into(),
                },
            ],
        }
    }

    #[test]
    fn render_round_trips() {
        let original = sample();
        let parsed = LockFile::parse(&original.render(), Path::new("<test>")).unwrap();
        assert_eq!(parsed, original);
    }

    #[test]
    fn parse_ignores_comments_and_blank_lines() {
        let text = "# hello\n\n[graphblas]\n\n  path = deps/GraphBLAS\n\
                    url = u\nrev = r\npin = p\n";
        let lock = LockFile::parse(text, Path::new("<test>")).unwrap();
        assert_eq!(lock.entries.len(), 1);
        assert_eq!(lock.get("graphblas").unwrap().rev, "r");
    }

    #[test]
    fn missing_field_is_an_error() {
        let text = "[graphblas]\npath = deps/GraphBLAS\nurl = u\n";
        assert!(LockFile::parse(text, Path::new("<test>")).is_err());
    }

    #[test]
    fn entries_are_sorted_by_name() {
        let text = "[redisearch]\npath=deps/RediSearch\nurl=u\nrev=r\n\
                    [graphblas]\npath=deps/GraphBLAS\nurl=u\nrev=r\n";
        let lock = LockFile::parse(text, Path::new("<test>")).unwrap();
        let names: Vec<&str> = lock.entries.iter().map(|e| e.name.as_str()).collect();
        assert_eq!(names, ["graphblas", "redisearch"]);
    }
}
