-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [falkor_aeneas_pilot]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace falkor_aeneas_pilot

/-- [core::ops::bit::{impl core::ops::bit::BitOrAssign<&'_0 u64> for u64}::bitor_assign]:
    Source: '/rustc/library/core/src/internal_macros.rs', lines 64:12-64:45
    Name pattern: [core::ops::bit::{core::ops::bit::BitOrAssign<u64, &'0 u64>}::bitor_assign]
    Visibility: public -/
@[rust_fun
  "core::ops::bit::{core::ops::bit::BitOrAssign<u64, &'0 u64>}::bitor_assign"]
axiom U64.Insts.CoreOpsBitBitOrAssignShared0U64.bitor_assign
  : Std.U64 → Std.U64 → Result Std.U64

/-- [core::iter::traits::iterator::Iterator::all]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 2840:4-2843:64
    Name pattern: [core::iter::traits::iterator::Iterator::all]
    Visibility: public -/
@[trait_default, rust_fun "core::iter::traits::iterator::Iterator::all"]
axiom core.iter.traits.iterator.Iterator.all.default
  {Self : Type} {F : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item)
  (opsfunctionFnMutFTupleClause0_ItemBoolInst : core.ops.function.FnMut F
  Clause0_Item Bool) :
  Self → F → Result (Bool × Self)

/-- [core::slice::iter::{impl core::iter::traits::iterator::Iterator<&'a mut T> for core::slice::iter::IterMut<'a, T>}::all]:
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 304:12-307:45
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::IterMut<'a, @T>, &'a mut @T>}::all]
    Visibility: public -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::IterMut<'a, @T>, &'a mut @T>}::all"]
axiom core.slice.iter.IterMut.Insts.CoreIterTraitsIteratorIteratorMutAT.all
  {T : Type} {F : Type} (opsfunctionFnMutFTupleMutATBoolInst :
  core.ops.function.FnMut F T Bool) :
  core.slice.iter.IterMut T → F → Result (Bool × (core.slice.iter.IterMut
    T) × (core.slice.iter.IterMut T → core.slice.iter.IterMut T))

/-- Trait implementation: [core::slice::iter::{impl core::iter::traits::iterator::Iterator<&'a mut T> for core::slice::iter::IterMut<'a, T>}]
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 153:8-153:45
    Name pattern: [core::iter::traits::iterator::Iterator<core::slice::iter::IterMut<'a, @T>, &'a mut @T>] -/
@[reducible, rust_trait_impl
  "core::iter::traits::iterator::Iterator<core::slice::iter::IterMut<'a, @T>, &'a mut @T>"]
impl_def core.slice.iter.IterMut.Insts.CoreIterTraitsIteratorIteratorMutAT (T :
  Type) : core.iter.traits.iterator.Iterator (core.slice.iter.IterMut T) T := {
  next := core.slice.iter.IteratorIterMut.next
  zip := fun {U : Type} {Clause0_Item : Type} {Clause0_IntoIter : Type}
    (collectIntoIteratorInst : core.iter.traits.collect.IntoIterator U
    Clause0_Item Clause0_IntoIter) =>
    core.iter.traits.iterator.Iterator.zip.trait_default
    (core.slice.iter.IterMut.Insts.CoreIterTraitsIteratorIteratorMutAT T)
    collectIntoIteratorInst
  all := fun {F : Type} (opsfunctionFnMutPTupleMut0FBoolInst :
    core.ops.function.FnMut F T Bool) =>
    core.slice.iter.IterMut.Insts.CoreIterTraitsIteratorIteratorMutAT.all
    opsfunctionFnMutPTupleMut0FBoolInst
}

/-- [core::slice::iter::{impl core::iter::traits::iterator::Iterator<&'a T> for core::slice::iter::Iter<'a, T>}::all]:
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 304:12-307:45
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::all]
    Visibility: public -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::all"]
axiom core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.all
  {T : Type} {F : Type} (opsfunctionFnMutFTupleSharedATBoolInst :
  core.ops.function.FnMut F T Bool) :
  core.slice.iter.Iter T → F → Result (Bool × (core.slice.iter.Iter T))

/-- [thin_vec::ThinVec]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thin-vec-0.2.20/src/lib.rs', lines 490:0-490:21
    Name pattern: [thin_vec::ThinVec]
    Visibility: public -/
@[rust_type "thin_vec::ThinVec"]
axiom thin_vec.ThinVec (T : Type) : Type

/-- [thin_vec::{thin_vec::ThinVec<T>}::len]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thin-vec-0.2.20/src/lib.rs', lines 735:4-735:30
    Name pattern: [thin_vec::{thin_vec::ThinVec<@T>}::len]
    Visibility: public -/
@[rust_fun "thin_vec::{thin_vec::ThinVec<@T>}::len"]
axiom thin_vec.ThinVec.len {T : Type} : thin_vec.ThinVec T → Result Std.Usize

/-- [thin_vec::{thin_vec::ThinVec<T>}::resize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thin-vec-0.2.20/src/lib.rs', lines 1954:4-1954:54
    Name pattern: [thin_vec::{thin_vec::ThinVec<@T>}::resize]
    Visibility: public -/
@[rust_fun "thin_vec::{thin_vec::ThinVec<@T>}::resize"]
axiom thin_vec.ThinVec.resize
  {T : Type} (corecloneCloneInst : core.clone.Clone T) :
  thin_vec.ThinVec T → Std.Usize → T → Result (thin_vec.ThinVec T)

/-- [thin_vec::{impl core::ops::deref::Deref<[T]> for thin_vec::ThinVec<T>}::deref]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thin-vec-0.2.20/src/lib.rs', lines 2074:4-2074:27
    Name pattern: [thin_vec::{core::ops::deref::Deref<thin_vec::ThinVec<@T>, [@T]>}::deref]
    Visibility: public -/
@[rust_fun
  "thin_vec::{core::ops::deref::Deref<thin_vec::ThinVec<@T>, [@T]>}::deref"]
axiom thin_vec.ThinVec.Insts.CoreOpsDerefDerefSlice.deref
  {T : Type} : thin_vec.ThinVec T → Result (Slice T)

/-- [thin_vec::{impl core::ops::deref::DerefMut<[T]> for thin_vec::ThinVec<T>}::deref_mut]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thin-vec-0.2.20/src/lib.rs', lines 2080:4-2080:39
    Name pattern: [thin_vec::{core::ops::deref::DerefMut<thin_vec::ThinVec<@T>, [@T]>}::deref_mut]
    Visibility: public -/
@[rust_fun
  "thin_vec::{core::ops::deref::DerefMut<thin_vec::ThinVec<@T>, [@T]>}::deref_mut"]
axiom thin_vec.ThinVec.Insts.CoreOpsDerefDerefMutSlice.deref_mut
  {T : Type} :
  thin_vec.ThinVec T → Result ((Slice T) × (Slice T → thin_vec.ThinVec T))

/-- [thin_vec::{impl core::clone::Clone for thin_vec::ThinVec<T>}::clone]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thin-vec-0.2.20/src/lib.rs', lines 2340:4-2340:33
    Name pattern: [thin_vec::{core::clone::Clone<thin_vec::ThinVec<@T>>}::clone]
    Visibility: public -/
@[rust_fun "thin_vec::{core::clone::Clone<thin_vec::ThinVec<@T>>}::clone"]
axiom thin_vec.ThinVec.Insts.CoreCloneClone.clone
  {T : Type} (corecloneCloneInst : core.clone.Clone T) :
  thin_vec.ThinVec T → Result (thin_vec.ThinVec T)

/-- [thin_vec::{impl core::default::Default for thin_vec::ThinVec<T>}::default]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/thin-vec-0.2.20/src/lib.rs', lines 2370:4-2370:30
    Name pattern: [thin_vec::{core::default::Default<thin_vec::ThinVec<@T>>}::default]
    Visibility: public -/
@[rust_fun
  "thin_vec::{core::default::Default<thin_vec::ThinVec<@T>>}::default"]
axiom thin_vec.ThinVec.Insts.CoreDefaultDefault.default
  (T : Type) : Result (thin_vec.ThinVec T)

/-- [falkor_aeneas_pilot::narrow_int::width_for]:
    Source: 'src/../../../../graph/src/narrow_int.rs', lines 19:0-26:1
    Visibility: public -/
def narrow_int.width_for (max : Std.U64) : Result Std.U8 := do
  if 0#u64 <= max
  then
    if max <= 255#u64
    then ok 1#u8
    else
      if 256#u64 <= max
      then
        if max <= 65535#u64
        then ok 2#u8
        else
          if 65536#u64 <= max
          then if max <= 4294967295#u64
               then ok 4#u8
               else ok 8#u8
          else ok 8#u8
      else
        if 65536#u64 <= max
        then if max <= 4294967295#u64
             then ok 4#u8
             else ok 8#u8
        else ok 8#u8
  else
    if 256#u64 <= max
    then
      if max <= 65535#u64
      then ok 2#u8
      else
        if 65536#u64 <= max
        then if max <= 4294967295#u64
             then ok 4#u8
             else ok 8#u8
        else ok 8#u8
    else
      if 65536#u64 <= max
      then if max <= 4294967295#u64
           then ok 4#u8
           else ok 8#u8
      else ok 8#u8

/-- [falkor_aeneas_pilot::bitset::BitSet]
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 25:0-28:1
    Visibility: public -/
structure bitset.BitSet where
  inline : Std.U64
  overflow : thin_vec.ThinVec Std.U64

/-- [falkor_aeneas_pilot::bitset::{impl core::default::Default for falkor_aeneas_pilot::bitset::BitSet}::default]:
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 24:9-24:16
    Visibility: public -/
def bitset.BitSet.Insts.CoreDefaultDefault.default : Result bitset.BitSet := do
  let tv ← thin_vec.ThinVec.Insts.CoreDefaultDefault.default Std.U64
  ok { inline := (core.default.DefaultU64.default), overflow := tv }

/-- Trait implementation: [falkor_aeneas_pilot::bitset::{impl core::default::Default for falkor_aeneas_pilot::bitset::BitSet}]
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 24:9-24:16 -/
@[reducible]
def bitset.BitSet.Insts.CoreDefaultDefault : core.default.Default bitset.BitSet
  := {
  default := bitset.BitSet.Insts.CoreDefaultDefault.default
}

/-- [falkor_aeneas_pilot::bitset::{impl core::clone::Clone for falkor_aeneas_pilot::bitset::BitSet}::clone]:
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 24:18-24:23
    Visibility: public -/
def bitset.BitSet.Insts.CoreCloneClone.clone
  (self : bitset.BitSet) : Result bitset.BitSet := do
  let i ← lift (core.clone.impls.CloneU64.clone self.inline)
  let tv ←
    thin_vec.ThinVec.Insts.CoreCloneClone.clone core.clone.CloneU64
      self.overflow
  ok { inline := i, overflow := tv }

/-- Trait implementation: [falkor_aeneas_pilot::bitset::{impl core::clone::Clone for falkor_aeneas_pilot::bitset::BitSet}]
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 24:18-24:23 -/
@[reducible]
def bitset.BitSet.Insts.CoreCloneClone : core.clone.Clone bitset.BitSet := {
  clone := bitset.BitSet.Insts.CoreCloneClone.clone
}

/-- [falkor_aeneas_pilot::bitset::{falkor_aeneas_pilot::bitset::BitSet}::set]:
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 31:4-46:5
    Visibility: public -/
def bitset.BitSet.set
  (self : bitset.BitSet) (bit : Std.Usize) : Result bitset.BitSet := do
  let word ← bit / 64#usize
  let i ← bit % 64#usize
  let mask ← 1#u64 <<< i
  if word = 0#usize
  then let i1 ← lift (self.inline ||| mask)
       ok { self with inline := i1 }
  else
    let idx ← word - 1#usize
    let i1 ← thin_vec.ThinVec.len self.overflow
    let tv ←
      if idx >= i1
      then
        do
        let i2 ← idx + 1#usize
        thin_vec.ThinVec.resize core.clone.CloneU64 self.overflow i2 0#u64
      else ok self.overflow
    let (s, deref_mut_back) ←
      thin_vec.ThinVec.Insts.CoreOpsDerefDerefMutSlice.deref_mut tv
    let i2 ← Slice.index_usize s idx
    let i3 ← lift (i2 ||| mask)
    let s1 ← Slice.update s idx i3
    let tv1 := deref_mut_back s1
    ok { self with overflow := tv1 }

/-- [falkor_aeneas_pilot::bitset::{falkor_aeneas_pilot::bitset::BitSet}::test]:
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 49:4-61:5
    Visibility: public -/
def bitset.BitSet.test
  (self : bitset.BitSet) (bit : Std.Usize) : Result Bool := do
  let word ← bit / 64#usize
  let i ← bit % 64#usize
  let mask ← 1#u64 <<< i
  if word = 0#usize
  then let i1 ← lift (self.inline &&& mask)
       ok (i1 != 0#u64)
  else
    let idx ← word - 1#usize
    let i1 ← thin_vec.ThinVec.len self.overflow
    if idx < i1
    then
      let s ←
        thin_vec.ThinVec.Insts.CoreOpsDerefDerefSlice.deref self.overflow
      let i2 ← Slice.index_usize s idx
      let i3 ← lift (i2 &&& mask)
      ok (i3 != 0#u64)
    else ok false

/-- [falkor_aeneas_pilot::bitset::{falkor_aeneas_pilot::bitset::BitSet}::union]: loop body 0:
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 71:8-73:9
    Visibility: public -/
@[rust_loop_body]
def bitset.BitSet.union_loop.body
  (iter : core.iter.adapters.zip.Zip (core.slice.iter.IterMut Std.U64)
  (core.slice.iter.Iter Std.U64))
  (back : core.iter.adapters.zip.Zip (core.slice.iter.IterMut Std.U64)
  (core.slice.iter.Iter Std.U64) → core.iter.adapters.zip.Zip
  (core.slice.iter.IterMut Std.U64) (core.slice.iter.Iter Std.U64)) :
  Result (ControlFlow ((core.iter.adapters.zip.Zip (core.slice.iter.IterMut
    Std.U64) (core.slice.iter.Iter Std.U64)) × (core.iter.adapters.zip.Zip
    (core.slice.iter.IterMut Std.U64) (core.slice.iter.Iter Std.U64) →
    core.iter.adapters.zip.Zip (core.slice.iter.IterMut Std.U64)
    (core.slice.iter.Iter Std.U64))) (core.iter.adapters.zip.Zip
    (core.slice.iter.IterMut Std.U64) (core.slice.iter.Iter Std.U64)))
  := do
  let (o, iter1, next_back) ←
    core.iter.adapters.zip.Zip.Insts.CoreIterTraitsIteratorIteratorPair.next
      (core.slice.iter.IterMut.Insts.CoreIterTraitsIteratorIteratorMutAT
      Std.U64) (core.iter.traits.iterator.IteratorSliceIter Std.U64) iter
  match o with
  | none => ok (done (let z := next_back iter1 none
                      back z))
  | some p =>
    let (a, b) := p
    let a1 ← U64.Insts.CoreOpsBitBitOrAssignShared0U64.bitor_assign a b
    ok (cont (iter1, fun z => let z1 := next_back z (some (a1, b))
                              back z1))

/-- [falkor_aeneas_pilot::bitset::{falkor_aeneas_pilot::bitset::BitSet}::union]: loop 0:
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 71:8-73:9
    Visibility: public -/
@[rust_loop]
def bitset.BitSet.union_loop
  (iter : core.iter.adapters.zip.Zip (core.slice.iter.IterMut Std.U64)
  (core.slice.iter.Iter Std.U64))
  (back : core.iter.adapters.zip.Zip (core.slice.iter.IterMut Std.U64)
  (core.slice.iter.Iter Std.U64) → core.iter.adapters.zip.Zip
  (core.slice.iter.IterMut Std.U64) (core.slice.iter.Iter Std.U64)) :
  Result (core.iter.adapters.zip.Zip (core.slice.iter.IterMut Std.U64)
    (core.slice.iter.Iter Std.U64))
  := do
  loop
    (fun (iter1, back1) => bitset.BitSet.union_loop.body iter1 back1)
    (iter, back)

/-- [falkor_aeneas_pilot::bitset::{falkor_aeneas_pilot::bitset::BitSet}::union]:
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 63:4-74:5
    Visibility: public -/
def bitset.BitSet.union
  (self : bitset.BitSet) (other : bitset.BitSet) : Result bitset.BitSet := do
  let i ← lift (self.inline ||| other.inline)
  let i1 ← thin_vec.ThinVec.len other.overflow
  let i2 ← thin_vec.ThinVec.len self.overflow
  let tv ←
    if i1 > i2
    then thin_vec.ThinVec.resize core.clone.CloneU64 self.overflow i1 0#u64
    else ok self.overflow
  let (s, deref_mut_back) ←
    thin_vec.ThinVec.Insts.CoreOpsDerefDerefMutSlice.deref_mut tv
  let (im, iter_mut_back) ← core.slice.Slice.iter_mut s
  let s1 ← thin_vec.ThinVec.Insts.CoreOpsDerefDerefSlice.deref other.overflow
  let i3 ← core.slice.Slice.iter s1
  let (iter, trait_default_back) ←
    core.iter.traits.iterator.Iterator.zip.trait_default
      (core.slice.iter.IterMut.Insts.CoreIterTraitsIteratorIteratorMutAT
      Std.U64) (core.iter.traits.collect.IntoIterator.Blanket
      (core.iter.traits.iterator.IteratorSliceIter Std.U64)) im i3
  let back ← bitset.BitSet.union_loop iter (fun z => z)
  let im1 := trait_default_back back
  let s2 := iter_mut_back im1
  let tv1 := deref_mut_back s2
  ok { inline := i, overflow := tv1 }

/-- [falkor_aeneas_pilot::bitset::{falkor_aeneas_pilot::bitset::BitSet}::clear]:
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 76:4-90:5
    Visibility: public -/
def bitset.BitSet.clear
  (self : bitset.BitSet) (bit : Std.Usize) : Result bitset.BitSet := do
  let word ← bit / 64#usize
  let i ← bit % 64#usize
  let mask ← 1#u64 <<< i
  if word = 0#usize
  then
    let i1 ← lift (~~~ mask)
    let i2 ← lift (self.inline &&& i1)
    ok { self with inline := i2 }
  else
    let idx ← word - 1#usize
    let i1 ← thin_vec.ThinVec.len self.overflow
    if idx < i1
    then
      let i2 ← lift (~~~ mask)
      let (s, deref_mut_back) ←
        thin_vec.ThinVec.Insts.CoreOpsDerefDerefMutSlice.deref_mut
          self.overflow
      let i3 ← Slice.index_usize s idx
      let i4 ← lift (i3 &&& i2)
      let s1 ← Slice.update s idx i4
      let tv := deref_mut_back s1
      ok { self with overflow := tv }
    else ok self

/-- [falkor_aeneas_pilot::bitset::{falkor_aeneas_pilot::bitset::BitSet}::is_empty::{closure}]
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 95:53-95:64 -/
@[reducible]
def bitset.BitSet.is_empty.closure := Unit

/-- [falkor_aeneas_pilot::bitset::{falkor_aeneas_pilot::bitset::BitSet}::is_empty::{impl core::ops::function::FnMut<(&'_0 u64,), bool> for falkor_aeneas_pilot::bitset::{falkor_aeneas_pilot::bitset::BitSet}::is_empty::{closure}}::call_mut]:
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 95:53-95:64 -/
def
  bitset.BitSet.is_empty.closure.Insts.CoreOpsFunctionFnMutTupleShared0U64Bool.call_mut
  (c : bitset.BitSet.is_empty.closure) (tupled_args : Std.U64) :
  Result (Bool × bitset.BitSet.is_empty.closure)
  := do
  ok (tupled_args = 0#u64, c)

/-- [falkor_aeneas_pilot::bitset::{falkor_aeneas_pilot::bitset::BitSet}::is_empty::{impl core::ops::function::FnOnce<(&'_0 u64,), bool> for falkor_aeneas_pilot::bitset::{falkor_aeneas_pilot::bitset::BitSet}::is_empty::{closure}}::call_once]:
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 95:53-95:64 -/
def
  bitset.BitSet.is_empty.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U64Bool.call_once
  (c : bitset.BitSet.is_empty.closure) (i : Std.U64) : Result Bool := do
  let (b, _) ←
    bitset.BitSet.is_empty.closure.Insts.CoreOpsFunctionFnMutTupleShared0U64Bool.call_mut
      c i
  ok b

/-- Trait implementation: [falkor_aeneas_pilot::bitset::{falkor_aeneas_pilot::bitset::BitSet}::is_empty::{impl core::ops::function::FnOnce<(&'_0 u64,), bool> for falkor_aeneas_pilot::bitset::{falkor_aeneas_pilot::bitset::BitSet}::is_empty::{closure}}]
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 95:53-95:64 -/
@[reducible]
def
  bitset.BitSet.is_empty.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U64Bool
  : core.ops.function.FnOnce bitset.BitSet.is_empty.closure Std.U64 Bool := {
  call_once :=
    bitset.BitSet.is_empty.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U64Bool.call_once
}

/-- Trait implementation: [falkor_aeneas_pilot::bitset::{falkor_aeneas_pilot::bitset::BitSet}::is_empty::{impl core::ops::function::FnMut<(&'_0 u64,), bool> for falkor_aeneas_pilot::bitset::{falkor_aeneas_pilot::bitset::BitSet}::is_empty::{closure}}]
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 95:53-95:64 -/
@[reducible]
def
  bitset.BitSet.is_empty.closure.Insts.CoreOpsFunctionFnMutTupleShared0U64Bool
  : core.ops.function.FnMut bitset.BitSet.is_empty.closure Std.U64 Bool := {
  FnOnceInst :=
    bitset.BitSet.is_empty.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U64Bool
  call_mut :=
    bitset.BitSet.is_empty.closure.Insts.CoreOpsFunctionFnMutTupleShared0U64Bool.call_mut
}

/-- [falkor_aeneas_pilot::bitset::{falkor_aeneas_pilot::bitset::BitSet}::is_empty]:
    Source: 'src/../../../../graph/src/runtime/bitset.rs', lines 94:4-96:5
    Visibility: public -/
def bitset.BitSet.is_empty (self : bitset.BitSet) : Result Bool := do
  if self.inline = 0#u64
  then
    let s ← thin_vec.ThinVec.Insts.CoreOpsDerefDerefSlice.deref self.overflow
    let i ← core.slice.Slice.iter s
    let (b, _) ←
      core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.all
        bitset.BitSet.is_empty.closure.Insts.CoreOpsFunctionFnMutTupleShared0U64Bool
        i ()
    ok b
  else ok false

end falkor_aeneas_pilot
