import Extracted.NarrowInt
/-!
# Aeneas feasibility pilot — proofs against Rust-EXTRACTED definitions

`Extracted/NarrowInt.lean` is generated by `./extract.sh` (Charon 0.1.270 +
Aeneas nightly-2026.09.24-557f7a1) straight from `graph/src/narrow_int.rs`,
which the pilot crate `rust/` includes by `#[path]` (no copy, so no drift).
It is type-checked unmodified; `import Aeneas` resolves to the local shim
`Aeneas.lean` (see its header: the real library needs Lean 4.31 + Mathlib).

| here                         | there                                             |
|------------------------------|---------------------------------------------------|
| `falkor_aeneas_pilot.narrow_int.width_for` (extracted) | `graph/src/narrow_int.rs:19` |
| `widthFor` (hand model, copied verbatim) | `proofs/id_list/FalkorIdList/Wire.lean:74` |

Bridge theorem `width_for_refines` shows the hand-written model used by
proofs/id_list is exactly the extracted Rust function, so every id_list theorem
about `widthFor` (e.g. `widthFor_fits`) transfers; `width_for_lossless` is
`widthFor_fits` re-proved directly against the extracted code.
If someone edits `width_for` in Rust, rerunning extract.sh changes the
extracted def and these proofs break — which is the point.

## Pilot findings (2026-09-24)

* **Install**: no opam/nix/sudo needed. Prebuilt macOS-arm64 nightlies
  (aeneas nightly-2026.09.24-557f7a1, bundling charon 0.1.270; the standalone
  charon release 0.1.271 emits LLBC this Aeneas rejects) + `rustup toolchain
  install nightly-2026-09-17 -c rustc-dev,llvm-tools,rust-src`. ~5 min total.
* **Lean version**: Aeneas' Lean library pins Lean **v4.31.0 + Mathlib v4.31.0**
  (we use 4.34.0, no Mathlib). Fetching Mathlib hit "No space left on device"
  (<9 GB free), so the full library was NOT built; hence the `Aeneas.lean` shim.
* **narrow_int**: extracts cleanly (65 lines); type-checks unmodified against
  the shim; 5 theorems proved here, incl. refinement to the id_list hand model.
  Drift check: mutating the Rust arm to `0..=0x1FF => 1` and re-extracting makes
  `width_for_refines` fail to build (verified in a scratch copy).
* **runtime::bitset**: extracts (full/Extracted/Bitset.lean) via charon on the
  pilot crate; `ThinVec` (external crate), `Iterator::all`/`zip`,
  `BitOrAssign<&u64>` come out as axioms (no Aeneas model). Not type-checked.
* **effects::v3::id_list**: charon runs on the WHOLE `graph` crate (2 min, 2 GB
  target; no GraphBLAS linking needed). Blockers: `Box<dyn Iterator>`
  (Segment::iter), `impl Iterator` returns (IdList::iter), higher-ranked
  lifetimes in the closure, early `return` inside a loop (read_ids),
  fixed-size-array symbolic expansion (Reader::take_array -> `sorry`),
  Iterator::copied/collect (From impls) crash Aeneas ("Internal error").
  With those excluded (extract.sh), push/claim_direction/maybe_collapse_run/
  Run::*/Segment::{encode,decode,encoded_len}/write_narrow/read_narrow extract:
  6.3k lines, 2 `sorry` (take_array; PartialEq instance of the excluded impl),
  47 axioms for roaring::RoaringTreemap, smallvec::SmallVec, io::Write, fmt.
  `--start-from` cannot name inherent methods, only modules/free items.
* **Re-targeting**: narrow_int — done (above). proofs/id_list models
  `IdList.push` over lists; the extracted `push` works over opaque SmallVec /
  RoaringTreemap axioms, so re-targeting needs Lean models of those two crates
  (or `-split-files` external defs) before any id_list theorem transfers.
-/
open Aeneas Aeneas.Std falkor_aeneas_pilot

namespace AeneasPilot

/-- Hand model from proofs/id_list/FalkorIdList/Wire.lean:74 (verbatim). -/
def widthFor (v : Nat) : Nat :=
  if v ≤ 0xFF then 1 else if v ≤ 0xFFFF then 2 else if v ≤ 0xFFFFFFFF then 4 else 8

@[simp] theorem U64.ofNat_val (n : Nat) (h : n < 2 ^ 64) : (U64.ofNat n h).val = n := by
  simp [U64.ofNat, UScalar.ofNat, UScalar.val, UScalarTy.numBits]; omega

@[simp] theorem U8.ofNat_val (n : Nat) (h : n < 2 ^ 8) : (U8.ofNat n h).val = n := by
  simp [U8.ofNat, UScalar.ofNat, UScalar.val, UScalarTy.numBits]; omega

theorem le_iff {ty} (a b : UScalar ty) : a ≤ b ↔ a.val ≤ b.val := Iff.rfl

theorem U64.val_lt (m : U64) : m.val < 2 ^ 64 := by
  have := m.bv.isLt; simpa [UScalar.val, UScalarTy.numBits] using this

/-- **Refinement**: the extracted Rust `width_for` never fails and returns
exactly the hand model `widthFor` of proofs/id_list. -/
theorem width_for_refines (m : U64) :
    ∃ w, narrow_int.width_for m = .ok w ∧ w.val = widthFor m.val := by
  have hm := U64.val_lt m
  unfold narrow_int.width_for widthFor
  simp only [le_iff, U64.ofNat_val]
  repeat' split
  all_goals first
    | omega
    | (refine ⟨_, rfl, ?_⟩; simp)

/-- `widthFor_fits` (proofs/id_list Wire.lean:93) re-proved against the
extracted code: the chosen width always holds the value (lossless). -/
theorem width_for_lossless (m : U64) (w : U8) (h : narrow_int.width_for m = .ok w) :
    m.val < 256 ^ w.val := by
  obtain ⟨w', h', hv⟩ := width_for_refines m
  rw [h] at h'; cases h'
  have hm := U64.val_lt m
  rw [hv]; unfold widthFor
  split <;> (try split) <;> (try split) <;> simp <;> omega

/-- Minimality: the width is the smallest power-of-two byte count that fits. -/
theorem width_for_minimal (m : U64) (w : U8) (h : narrow_int.width_for m = .ok w) :
    w.val = 1 ∨ 256 ^ (w.val / 2) ≤ m.val := by
  obtain ⟨w', h', hv⟩ := width_for_refines m
  rw [h] at h'; cases h'
  rw [hv]; unfold widthFor
  split <;> (try split) <;> (try split) <;> simp <;> omega

/-- `widthFor_cases` against the extracted code. -/
theorem width_for_cases (m : U64) (w : U8) (h : narrow_int.width_for m = .ok w) :
    w.val = 1 ∨ w.val = 2 ∨ w.val = 4 ∨ w.val = 8 := by
  obtain ⟨w', h', hv⟩ := width_for_refines m
  rw [h] at h'; cases h'
  rw [hv]; unfold widthFor
  split <;> (try split) <;> (try split) <;> simp

end AeneasPilot
