-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [falkor_aeneas_pilot]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace falkor_aeneas_pilot

/-- [falkor_aeneas_pilot::narrow_int::width_for]:
    Source: 'src/../../../../graph/src/narrow_int.rs', lines 19:0-26:1
    Visibility: public -/
def narrow_int.width_for (max : Std.U64) : Result Std.U8 := do
  if 0#u64 <= max
  then
    if max <= 255#u64
    then ok 1#u8
    else
      if 256#u64 <= max
      then
        if max <= 65535#u64
        then ok 2#u8
        else
          if 65536#u64 <= max
          then if max <= 4294967295#u64
               then ok 4#u8
               else ok 8#u8
          else ok 8#u8
      else
        if 65536#u64 <= max
        then if max <= 4294967295#u64
             then ok 4#u8
             else ok 8#u8
        else ok 8#u8
  else
    if 256#u64 <= max
    then
      if max <= 65535#u64
      then ok 2#u8
      else
        if 65536#u64 <= max
        then if max <= 4294967295#u64
             then ok 4#u8
             else ok 8#u8
        else ok 8#u8
    else
      if 65536#u64 <= max
      then if max <= 4294967295#u64
           then ok 4#u8
           else ok 8#u8
      else ok 8#u8

end falkor_aeneas_pilot
