/*
 * Copyright Redis Ltd. 2018 - present
 * Licensed under your choice of the Redis Source Available License 2.0 (RSALv2) or
 * the Server Side Public License v1 (SSPLv1).
 */

// Loader for the effects v3 conformance corpus in tests/fixtures/effects_v3.
//
// The corpus is the shared statement of the wire format that neither engine can
// move on its own; see that directory's README. A `.hex` file is a complete
// GRAPH.EFFECT payload written as hex, 32 bytes to a line, with '#' comments.
// This header turns one into bytes and nothing else -- it deliberately knows no
// part of the format, so a codec change cannot quietly change what the corpus
// is read as.

#pragma once

#include <stdio.h>
#include <ctype.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// where the corpus lives; CMake defines this to an absolute path so the tests
// do not depend on the directory they are run from. the environment variable
// overrides it, for running a binary against a regenerated corpus elsewhere.
#ifndef EFFECTS_V3_FIXTURES_DIR
#define EFFECTS_V3_FIXTURES_DIR "tests/fixtures/effects_v3"
#endif

#define EFFECTS_V3_CORPUS_MAX_BYTES (1 << 20)

// a decoded fixture
typedef struct {
	char name[64];       // case name, e.g. "seg_range"
	unsigned char *buf;  // payload bytes, malloc'd; NULL if load failed
	size_t len;          // number of payload bytes
	char err[256];       // failure reason, empty on success
} EffectsV3Fixture;

static inline const char *EffectsV3Corpus_Dir(void) {
	const char *d = getenv("EFFECTS_V3_FIXTURES_DIR");
	return (d != NULL && *d != '\0') ? d : EFFECTS_V3_FIXTURES_DIR;
}

static inline int _hex_nibble(int c) {
	if(c >= '0' && c <= '9') return c - '0';
	if(c >= 'a' && c <= 'f') return c - 'a' + 10;
	if(c >= 'A' && c <= 'F') return c - 'A' + 10;
	return -1;
}

// load one case by name; always returns a struct, check .buf / .err
//
// the documented reader rule is the whole of it: drop everything from a '#' to
// end of line, drop all whitespace, the rest is hex digit pairs. anything else
// in the file is an error rather than something to skip, so that a corrupted
// fixture fails loudly instead of decoding as a shorter payload.
static inline EffectsV3Fixture EffectsV3Corpus_Load
(
	const char *name  // case name, without the .hex suffix
) {
	EffectsV3Fixture f;
	memset(&f, 0, sizeof(f));
	snprintf(f.name, sizeof(f.name), "%s", name);

	char path[1024];
	snprintf(path, sizeof(path), "%s/%s.hex", EffectsV3Corpus_Dir(), name);

	FILE *fp = fopen(path, "rb");
	if(fp == NULL) {
		snprintf(f.err, sizeof(f.err), "cannot open %s", path);
		return f;
	}

	unsigned char *buf = (unsigned char*)malloc(EFFECTS_V3_CORPUS_MAX_BYTES);
	if(buf == NULL) {
		fclose(fp);
		snprintf(f.err, sizeof(f.err), "out of memory");
		return f;
	}

	size_t n        = 0;  // bytes decoded so far
	int    pending  = -1; // first nibble of a half-finished byte
	int    comment  = 0;  // inside a '#' comment
	long   line     = 1;
	int    c;

	while((c = fgetc(fp)) != EOF) {
		if(c == '\n') { comment = 0; line++; continue; }
		if(comment) continue;
		if(c == '#') { comment = 1; continue; }
		if(isspace(c)) continue;

		int v = _hex_nibble(c);
		if(v < 0) {
			snprintf(f.err, sizeof(f.err),
					"non-hex character '%c' at line %ld of %s.hex", c, line, name);
			free(buf);
			fclose(fp);
			return f;
		}

		if(pending < 0) {
			pending = v;
		} else {
			if(n == EFFECTS_V3_CORPUS_MAX_BYTES) {
				snprintf(f.err, sizeof(f.err), "%s.hex exceeds %d bytes",
						name, EFFECTS_V3_CORPUS_MAX_BYTES);
				free(buf);
				fclose(fp);
				return f;
			}
			buf[n++] = (unsigned char)((pending << 4) | v);
			pending  = -1;
		}
	}

	fclose(fp);

	if(pending >= 0) {
		snprintf(f.err, sizeof(f.err),
				"%s.hex has an odd number of hex digits", name);
		free(buf);
		return f;
	}

	f.buf = buf;
	f.len = n;
	return f;
}

static inline void EffectsV3Corpus_Free
(
	EffectsV3Fixture *f  // fixture to free
) {
	if(f == NULL) return;
	free(f->buf);
	f->buf = NULL;
	f->len = 0;
}

// FNV-1a 64, so the expected-bytes table below can pin content and not just
// length. no cryptographic claim is intended -- this catches drift, not a
// forged corpus.
static inline uint64_t EffectsV3Corpus_Hash
(
	const unsigned char *b,  // bytes to hash
	size_t n                 // number of bytes
) {
	uint64_t h = 0xcbf29ce484222325ULL;
	for(size_t i = 0; i < n; i++) {
		h ^= (uint64_t)b[i];
		h *= 0x100000001b3ULL;
	}
	return h;
}

//------------------------------------------------------------------------------
// the corpus index
//------------------------------------------------------------------------------

// Every case, its byte count and its FNV-1a 64 over the decoded payload.
//
// This table is the drift alarm: if any fixture's bytes change, these hashes
// stop matching and the build says so.
//
// WHERE THESE CAME FROM, AND WHAT OWNS THEM NOW. The bytes were generated by
// the Rust encoder's fixture builder and pulled onto a local branch. That
// builder was then dropped from the Rust stack as out of scope, so there is
// currently no upstream generator in any landing branch to sync against, and
// whether one comes back or this directory becomes the canonical copy is an
// open question. Until it is settled, this table checks the corpus against
// itself and nothing else -- which still catches an edited or truncated
// fixture, and is worth having on its own.
//
// The cross-side half, where both engines assert the same hashes over the same
// bytes so a drift fails whichever side moved, is deliberately not built yet:
// it needs a canonical side to be nominated first.
//
// A legitimate wire change updates this table in the same commit that refreshes
// the .hex files -- never on its own. When the hashes fail, do not edit them to
// match: find out which side moved. The corpus is not ground truth, C's format
// definition in src/effects/effects.{c,h} is, and a fixture that disagrees with
// it gets regenerated rather than accepted.
typedef struct {
	const char *name;  // case name
	size_t      len;   // expected payload bytes
	uint64_t    hash;  // expected FNV-1a 64 of the payload
} EffectsV3CorpusEntry;

static const EffectsV3CorpusEntry EFFECTS_V3_CORPUS[] = {
	{ "collapse_above",             87, 0x3d88a4f28aaea5c6ULL },
	{ "collapse_below",             87, 0x4cbabae90c29e859ULL },
	{ "count_width_2_bytes",        20, 0x2e56a849e29fe6c6ULL },
	{ "count_width_4_bytes",        22, 0x137b4e11fc6e717aULL },
	{ "create_edge_no_attrs",       37, 0x48219eb875266b98ULL },
	{ "create_node_no_attrs",       25, 0xa380f68f8358f25eULL },
	{ "dir_ascending",              19, 0x18053572baebfcb6ULL },
	{ "dir_descending",             19, 0xebe277717f6c4da9ULL },
	{ "dir_descending_bitmap",      87, 0xd718d146fbdfe506ULL },
	{ "dir_descending_to_zero",     19, 0xeca0d771800e19d1ULL },
	{ "payload_multi_record",      134, 0x4b42a1a40560cd7fULL },
	{ "rec_add_attribute",          21, 0xe895ecabfbee7822ULL },
	{ "rec_add_schema_edge",        28, 0x367993b4ce6b7fcdULL },
	{ "rec_add_schema_node",        29, 0xf1cf156b3fe44682ULL },
	{ "rec_create_constraint",      53, 0x0a3f2192f0fbfc5eULL },
	{ "rec_create_edge",           100, 0x694160732cea0798ULL },
	{ "rec_create_index",           69, 0xe4e1558ecc238602ULL },
	{ "rec_create_index_vector",    99, 0x2221577ba6bf4ec8ULL },
	{ "rec_create_node",            92, 0x54a9d4dce51ffafaULL },
	{ "rec_delete_edge",            35, 0x0813dda13240ab84ULL },
	{ "rec_delete_node",            31, 0xb6a5debbb2ebc057ULL },
	{ "rec_drop_constraint",        62, 0x860789c8b0554070ULL },
	{ "rec_drop_index",             48, 0x47d3037abc503541ULL },
	{ "rec_remove_labels",          23, 0x63c59350249081b7ULL },
	{ "rec_set_labels",             27, 0x458912d5224a18e1ULL },
	{ "rec_update_edge",            86, 0xb56c9d6ca2670354ULL },
	{ "rec_update_node",            88, 0xa1991dc9e8fcbdd1ULL },
	{ "seg_ascending",             209, 0xbdf061e5eb64ea35ULL },
	{ "seg_mixed",                  25, 0xff9f819dda272e28ULL },
	{ "seg_range",                  19, 0x16963d72b9b4429aULL },
	{ "seg_range_many",             28, 0x95536791a1408140ULL },
	{ "seg_range_single",           19, 0x924a553aae154321ULL },
	{ "seg_repeat",                 19, 0xc82cae94f8f4ed02ULL },
	{ "value_string_interior_nul",  59, 0x221b47f2ad9d6d3aULL },
	{ "value_width_4_bytes",        22, 0x7e8876e3c866984dULL },
	{ "value_width_8_bytes",        26, 0x0949db598e268f99ULL },
	{ "values_all_kinds",          265, 0x0a495fe579a3fc1aULL },
};

#define EFFECTS_V3_CORPUS_COUNT \
	(sizeof(EFFECTS_V3_CORPUS) / sizeof(EFFECTS_V3_CORPUS[0]))
