/*
 * Copyright Redis Ltd. 2018 - present
 * Licensed under your choice of the Redis Source Available License 2.0 (RSALv2) or
 * the Server Side Public License v1 (SSPLv1).
 */

// Guards the effects v3 conformance corpus itself.
//
// Nothing here touches a codec. These tests exist so that the corpus cannot rot
// without saying so: it is a set of byte fixtures that two engines have to agree
// on, and a file nothing checks is a file anyone can edit.
//
// The fixtures were generated by the Rust encoder's fixture builder, which has
// since been dropped from the Rust stack, so there is no upstream to diff
// against at the moment -- see the note on the manifest in effects_v3_corpus.h.
// These checks are therefore intra-C: they catch an edited, truncated or added
// fixture here, not a divergence between the two engines.
//
// The round-trip and truncation harnesses, which do need a codec, live in
// test_effects_v3_roundtrip.c.

#include "tests/unit/effects_v3_corpus.h"

#include <dirent.h>

#include "acutest.h"

//------------------------------------------------------------------------------
// the corpus is intact
//------------------------------------------------------------------------------

// every listed case loads, at the byte count and content the table records
//
// a hash mismatch is not a licence to update the table: it means the mirror and
// the generator disagree, and which one is wrong is settled against C's format
// definition in src/effects/effects.{c,h}
void test_effectsV3Corpus_matchesManifest(void) {
	for(size_t i = 0; i < EFFECTS_V3_CORPUS_COUNT; i++) {
		const EffectsV3CorpusEntry *e = EFFECTS_V3_CORPUS + i;

		EffectsV3Fixture f = EffectsV3Corpus_Load(e->name);
		TEST_CASE(e->name);

		TEST_ASSERT_(f.buf != NULL, "%s: %s", e->name, f.err);
		if(f.buf == NULL) continue;

		TEST_ASSERT_(f.len == e->len, "%s: %zu bytes, manifest says %zu",
				e->name, f.len, e->len);

		uint64_t h = EffectsV3Corpus_Hash(f.buf, f.len);
		TEST_ASSERT_(h == e->hash,
				"%s: content drifted from the manifest (0x%016llx, expected "
				"0x%016llx) -- the mirror and the Rust generator disagree",
				e->name, (unsigned long long)h, (unsigned long long)e->hash);

		EffectsV3Corpus_Free(&f);
	}
}

// the manifest lists every .hex in the directory, and nothing it does not
//
// the hashes above catch a fixture whose bytes changed. They cannot catch a
// fixture that was ADDED on the Rust side, because an unlisted file is simply
// never loaded -- a new case would be mirrored in and silently untested. This
// is the check that notices.
void test_effectsV3Corpus_manifestIsComplete(void) {
	const char *dir = EffectsV3Corpus_Dir();

	DIR *d = opendir(dir);
	TEST_ASSERT_(d != NULL, "cannot open corpus directory %s", dir);
	if(d == NULL) return;

	size_t seen = 0;
	struct dirent *ent;

	while((ent = readdir(d)) != NULL) {
		const char *n   = ent->d_name;
		size_t      len = strlen(n);
		if(len < 5 || strcmp(n + len - 4, ".hex") != 0) continue;

		char case_name[64];
		snprintf(case_name, sizeof(case_name), "%.*s", (int)(len - 4), n);

		bool listed = false;
		for(size_t i = 0; i < EFFECTS_V3_CORPUS_COUNT; i++) {
			if(strcmp(EFFECTS_V3_CORPUS[i].name, case_name) == 0) {
				listed = true;
				break;
			}
		}

		TEST_ASSERT_(listed,
				"%s.hex is in the corpus but not in the manifest -- it is "
				"mirrored in and never tested", case_name);
		seen++;
	}

	closedir(d);

	TEST_ASSERT_(seen == EFFECTS_V3_CORPUS_COUNT,
			"%zu .hex files on disk, %zu in the manifest",
			seen, EFFECTS_V3_CORPUS_COUNT);
}

// every payload declares version 3, uncompressed
//
// the corpus README states that payloads are uncompressed on purpose: pinning a
// compression choice here would bind the far side to a compressor rather than to
// a format. This asserts the corpus still honours that, which also means the
// truncation harness is exercising the reader and not a zstd frame.
void test_effectsV3Corpus_preamble(void) {
	for(size_t i = 0; i < EFFECTS_V3_CORPUS_COUNT; i++) {
		const EffectsV3CorpusEntry *e = EFFECTS_V3_CORPUS + i;

		EffectsV3Fixture f = EffectsV3Corpus_Load(e->name);
		TEST_CASE(e->name);
		if(f.buf == NULL) continue;

		TEST_ASSERT_(f.len >= 2, "%s: %zu bytes, too short for a preamble",
				e->name, f.len);
		if(f.len >= 2) {
			TEST_ASSERT_(f.buf[0] == 3, "%s: version byte is %u, expected 3",
					e->name, f.buf[0]);
			TEST_ASSERT_(f.buf[1] == 0, "%s: flags byte is 0x%02x, expected 0 "
					"(the corpus is uncompressed by design)",
					e->name, f.buf[1]);
		}

		EffectsV3Corpus_Free(&f);
	}
}

//------------------------------------------------------------------------------
// the loader honours the documented .hex rules
//------------------------------------------------------------------------------

static char _tmpdir[512];

// write a .hex file into a scratch directory and load it back through the real
// loader, by pointing the loader's directory override at the scratch directory
static EffectsV3Fixture _load_literal
(
	const char *name,     // case name to write
	const char *contents  // literal file contents
) {
	char path[1024];
	snprintf(path, sizeof(path), "%s/%s.hex", _tmpdir, name);

	FILE *fp = fopen(path, "wb");
	if(fp != NULL) {
		fputs(contents, fp);
		fclose(fp);
	}

	setenv("EFFECTS_V3_FIXTURES_DIR", _tmpdir, 1);
	EffectsV3Fixture f = EffectsV3Corpus_Load(name);
	unsetenv("EFFECTS_V3_FIXTURES_DIR");

	return f;
}

void test_effectsV3Corpus_hexReaderRules(void) {
	snprintf(_tmpdir, sizeof(_tmpdir), "%s", "/tmp/effects_v3_corpus_XXXXXX");
	TEST_ASSERT(mkdtemp(_tmpdir) != NULL);

	// a '#' comment runs to end of line and is dropped, as is all whitespace,
	// including hex split across lines and a byte split across a space
	{
		TEST_CASE("comments and whitespace are stripped");
		EffectsV3Fixture f = _load_literal("ok",
				"# a leading comment\n"
				"0300 0500\n"
				"\t0000  # a trailing comment\n"
				"00\n");
		TEST_ASSERT_(f.buf != NULL, "%s", f.err);
		if(f.buf != NULL) {
			TEST_ASSERT_(f.len == 7, "expected 7 bytes, got %zu", f.len);
			const unsigned char want[] =
				{ 0x03, 0x00, 0x05, 0x00, 0x00, 0x00, 0x00 };
			TEST_ASSERT(f.len == sizeof(want) &&
						memcmp(f.buf, want, sizeof(want)) == 0);
		}
		EffectsV3Corpus_Free(&f);
	}

	// a comment does not swallow the following line
	{
		TEST_CASE("a comment ends at the newline");
		EffectsV3Fixture f = _load_literal("cmt", "# ff\nab\n");
		TEST_ASSERT_(f.buf != NULL, "%s", f.err);
		if(f.buf != NULL) {
			TEST_ASSERT(f.len == 1 && f.buf[0] == 0xab);
		}
		EffectsV3Corpus_Free(&f);
	}

	// upper and lower case nibbles both decode
	{
		TEST_CASE("case insensitive");
		EffectsV3Fixture f = _load_literal("mixed", "AbcDeF\n");
		TEST_ASSERT_(f.buf != NULL, "%s", f.err);
		if(f.buf != NULL) {
			TEST_ASSERT(f.len == 3);
			TEST_ASSERT(f.buf[0] == 0xab && f.buf[1] == 0xcd &&
						f.buf[2] == 0xef);
		}
		EffectsV3Corpus_Free(&f);
	}

	// a half byte is an error, not a truncation to the shorter payload. this is
	// the failure that would otherwise feed the reader a subtly short buffer and
	// be read as the reader's bug
	{
		TEST_CASE("odd nibble count is rejected");
		EffectsV3Fixture f = _load_literal("odd", "030005\n0\n");
		TEST_ASSERT_(f.buf == NULL, "an odd digit count was accepted as %zu bytes",
				f.len);
		TEST_ASSERT(strstr(f.err, "odd") != NULL);
		EffectsV3Corpus_Free(&f);
	}

	// so is a stray non-hex character
	{
		TEST_CASE("non-hex character is rejected");
		EffectsV3Fixture f = _load_literal("junk", "0300zz\n");
		TEST_ASSERT_(f.buf == NULL, "a non-hex character was accepted");
		TEST_ASSERT(strstr(f.err, "non-hex") != NULL);
		EffectsV3Corpus_Free(&f);
	}

	// an empty payload loads as zero bytes rather than failing: it is a legal
	// thing to hand a decoder, and the truncation corpus starts there
	{
		TEST_CASE("comment-only file is an empty payload");
		EffectsV3Fixture f = _load_literal("empty", "# nothing here\n");
		TEST_ASSERT_(f.buf != NULL, "%s", f.err);
		TEST_ASSERT(f.len == 0);
		EffectsV3Corpus_Free(&f);
	}

	// a missing case is reported, not crashed on
	{
		TEST_CASE("missing file");
		setenv("EFFECTS_V3_FIXTURES_DIR", _tmpdir, 1);
		EffectsV3Fixture f = EffectsV3Corpus_Load("no_such_case");
		unsetenv("EFFECTS_V3_FIXTURES_DIR");
		TEST_ASSERT(f.buf == NULL);
		TEST_ASSERT(strstr(f.err, "cannot open") != NULL);
		EffectsV3Corpus_Free(&f);
	}
}

//------------------------------------------------------------------------------
// every gap case carries the bit its name claims
//------------------------------------------------------------------------------

// The manifest proves the corpus has not changed and that no file is unlisted.
// It cannot prove a file tests what its NAME says: a fixture called
// value_width_8_bytes that quietly encoded as width code 0 would hash
// consistently, be listed, and sit in the corpus looking like coverage while
// exercising the same path as every other case.
//
// So each gap case asserts the header byte it is named for. This is a byte
// comparison at a recorded offset rather than a parse -- the loader knows no
// format and neither does this, and the offset cannot drift silently because
// the manifest pins the bytes it points into.
//
// Segment header layout (graph/src/effects/v3/id_list.rs:512-519):
//   bits 0-1  kind: 0 Range, 1 Ascending, 2 Repeat
//   bits 2-3  value width code   0,1,2,3 -> 1,2,4,8 bytes
//   bits 4-5  count width code   same table
//   bit  6    descending
//   bit  7    reserved, rejected if set
typedef struct {
	const char    *name;     // case name
	size_t         hdr_off;  // offset of the segment header
	unsigned char  hdr;      // the byte it must be
	const char    *claims;   // what the name promises
} EffectsV3NamedShape;

static const EffectsV3NamedShape EFFECTS_V3_NAMED_SHAPES[] = {
	// direction, bit 6
	{ "dir_ascending",          16, 0x00, "Range, bit 6 CLEAR -- the control" },
	{ "dir_descending",         16, 0x40, "Range, bit 6 set" },
	{ "dir_descending_to_zero", 16, 0x40, "Range, bit 6 set, base runs to 0" },
	{ "dir_descending_bitmap",  16, 0x41, "Ascending, bit 6 set" },

	// value width, bits 2-3
	{ "value_width_4_bytes",    16, 0x08, "value width code 2 (4 bytes)" },
	{ "value_width_8_bytes",    16, 0x0c, "value width code 3 (8 bytes)" },

	// count width, bits 4-5
	{ "count_width_2_bytes",    16, 0x10, "count width code 1 (2 bytes)" },
	{ "count_width_4_bytes",    16, 0x20, "count width code 2 (4 bytes)" },

	// the one pre-existing case carrying a non-zero width, kept here because a
	// subset that drops it loses the whole value-width dimension for 2-byte ids
	{ "collapse_below",         19, 0x04, "second segment: value width code 1" },
};

#define EFFECTS_V3_NAMED_SHAPE_COUNT \
	(sizeof(EFFECTS_V3_NAMED_SHAPES) / sizeof(EFFECTS_V3_NAMED_SHAPES[0]))

void test_effectsV3Corpus_namedShapesAreOnTheWire(void) {
	for(size_t i = 0; i < EFFECTS_V3_NAMED_SHAPE_COUNT; i++) {
		const EffectsV3NamedShape *n = EFFECTS_V3_NAMED_SHAPES + i;

		EffectsV3Fixture f = EffectsV3Corpus_Load(n->name);
		TEST_CASE(n->name);
		TEST_ASSERT_(f.buf != NULL, "%s: %s", n->name, f.err);
		if(f.buf == NULL) continue;

		TEST_ASSERT_(f.len > n->hdr_off,
				"%s: %zu bytes, no header at offset %zu",
				n->name, f.len, n->hdr_off);

		if(f.len > n->hdr_off) {
			TEST_ASSERT_(f.buf[n->hdr_off] == n->hdr,
					"%s: header at offset %zu is 0x%02x, expected 0x%02x (%s). "
					"The case is not exercising what its name claims, so the "
					"coverage it looks like it provides is not there",
					n->name, n->hdr_off, f.buf[n->hdr_off], n->hdr, n->claims);
		}

		EffectsV3Corpus_Free(&f);
	}
}

//------------------------------------------------------------------------------
// the direction pairs
//------------------------------------------------------------------------------

// An engine that IGNORES bit 6 reads a descending payload as its ascending
// twin and returns the ids REVERSED rather than refusing the buffer. Nothing
// self-consistent catches that: decode-then-encode reproduces the bytes it
// thinks it read, so a round trip passes. Only a same-shape pair catches it,
// and only because the ascending control sits in the corpus beside it.
//
// This asserts the pairs differ in exactly the bytes direction is allowed to
// move, which is the assertion the pair exists to support.
typedef struct {
	const char *ascending;   // the control
	const char *descending;  // the same ids, other way
	size_t      off[4];      // the only offsets allowed to differ
	int         n_off;       // how many
	const char *why;         // what each differing byte is
} EffectsV3DirectionPair;

static const EffectsV3DirectionPair EFFECTS_V3_DIRECTION_PAIRS[] = {
	// a Range carries its base, which is the LOWEST id ascending and the
	// HIGHEST descending, so two bytes move: the header and the base
	{ "dir_ascending", "dir_descending", { 16, 17 }, 2,
	  "offset 16 is the header's bit 6; offset 17 is the base, 200 ascending "
	  "and 207 descending" },

	// a roaring blob is a SET and has no direction, so the payloads are
	// identical but for the bit itself. This is the strongest statement
	// available about bit 6: one byte apart, and the 66-byte blob untouched
	{ "collapse_above", "dir_descending_bitmap", { 16 }, 1,
	  "offset 16 alone -- the bitmap blob is byte-identical, so bit 6 is the "
	  "only thing carrying direction" },
};

#define EFFECTS_V3_DIRECTION_PAIR_COUNT \
	(sizeof(EFFECTS_V3_DIRECTION_PAIRS) / \
	 sizeof(EFFECTS_V3_DIRECTION_PAIRS[0]))

void test_effectsV3Corpus_directionPairs(void) {
	for(size_t i = 0; i < EFFECTS_V3_DIRECTION_PAIR_COUNT; i++) {
		const EffectsV3DirectionPair *p = EFFECTS_V3_DIRECTION_PAIRS + i;

		EffectsV3Fixture a = EffectsV3Corpus_Load(p->ascending);
		EffectsV3Fixture d = EffectsV3Corpus_Load(p->descending);

		TEST_CASE(p->ascending);

		if(a.buf == NULL || d.buf == NULL) {
			TEST_ASSERT_(false, "%s / %s: %s%s", p->ascending, p->descending,
					a.err, d.err);
			EffectsV3Corpus_Free(&a);
			EffectsV3Corpus_Free(&d);
			continue;
		}

		TEST_ASSERT_(a.len == d.len,
				"%s is %zu bytes and %s is %zu; a direction pair must be the "
				"same shape or it is not isolating the bit",
				p->ascending, a.len, p->descending, d.len);

		if(a.len == d.len) {
			// bit 6 set in the descending half, clear in the control
			TEST_ASSERT_((d.buf[p->off[0]] & 0x40) != 0 &&
						 (a.buf[p->off[0]] & 0x40) == 0,
					"%s/%s: bit 6 is not the difference at offset %zu "
					"(0x%02x vs 0x%02x)",
					p->ascending, p->descending, p->off[0],
					a.buf[p->off[0]], d.buf[p->off[0]]);

			for(size_t at = 0; at < a.len; at++) {
				bool allowed = false;
				for(int k = 0; k < p->n_off; k++) {
					if(at == p->off[k]) { allowed = true; break; }
				}

				if(a.buf[at] == d.buf[at]) continue;

				TEST_ASSERT_(allowed,
						"%s/%s differ at offset %zu (0x%02x vs 0x%02x), which "
						"direction is not allowed to move. %s",
						p->ascending, p->descending, at, a.buf[at], d.buf[at],
						p->why);
			}
		}

		EffectsV3Corpus_Free(&a);
		EffectsV3Corpus_Free(&d);
	}
}

TEST_LIST = {
	{ "EffectsV3Corpus.matchesManifest",    test_effectsV3Corpus_matchesManifest    },
	{ "EffectsV3Corpus.manifestIsComplete", test_effectsV3Corpus_manifestIsComplete },
	{ "EffectsV3Corpus.preamble",           test_effectsV3Corpus_preamble           },
	{ "EffectsV3Corpus.namedShapes",        test_effectsV3Corpus_namedShapesAreOnTheWire },
	{ "EffectsV3Corpus.directionPairs",     test_effectsV3Corpus_directionPairs     },
	{ "EffectsV3Corpus.hexReaderRules",     test_effectsV3Corpus_hexReaderRules     },
	{ NULL, NULL }
};
