name: browser tests trigger on new tag release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  post-release:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Print Tag
        run: |
          echo "Release published!"
          echo "Latest release tag: ${{ github.event.release.tag_name }}"