name: Spellcheck
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@26a39cd487140d628757554605a8ad02f9f7caf8 # 0.64.0
        with:
          config_path: .github/spellcheck-settings.yml
          task_name: Markdown
