name: Spellcheck
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@79c6662f156bc4faa184a458c39cd672783804b3 # 0.59.0
        with:
          config_path: .github/spellcheck-settings.yml
          task_name: Markdown
